
CREATE_MANPU_BY_PARTY_MEMBER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL00
	TAX
	JSL UNKNOWN_C4608C
	LDY @LOCAL00
	TYX
	JSL CREATE_MANPU
	END_C_FUNCTION
