
INIT_ENTITY_EXTRA_COMMON:
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$003C
	STA ENTITY_ALLOCATION_MAX_SLOT
@UNKNOWN0:
	LDX $88
	JSR MOVEMENT_DATA_READ16_COPY
	STA $96
	JSR MOVEMENT_DATA_READ16_COPY
	CLC
	ADC ENTITY_SCREEN_X_TABLE,X
	STA $98
	JSR MOVEMENT_DATA_READ16_COPY
	CLC
	ADC ENTITY_SCREEN_Y_TABLE,X
	STA $9A
	JSR MOVEMENT_DATA_READ16_COPY
	CLC
	ADC ENTITY_ABS_Z_TABLE,X
	STA NEW_ENTITY_POS_Z
	JSR MOVEMENT_DATA_READ16_COPY
	STA NEW_ENTITY_VAR0
	JSR MOVEMENT_DATA_READ16_COPY
	CLC
	ADC ENTITY_SCRIPT_VAR1_TABLE,X
	STA NEW_ENTITY_VAR1
	STX NEW_ENTITY_VAR2
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STY $94
	LDY $9A
	LDX $98
	LDA $96
	AND #$7FFF
	JMP INIT_ENTITY
	JSR MOVEMENT_DATA_READ16_COPY
	STA ENTITY_ALLOCATION_MIN_SLOT
	JSR MOVEMENT_DATA_READ16_COPY
	STA ENTITY_ALLOCATION_MAX_SLOT
	BRA @UNKNOWN0
	JSR MOVEMENT_DATA_READ16_COPY
	STA ENTITY_ALLOCATION_MIN_SLOT
	INC
	INC
	STA ENTITY_ALLOCATION_MAX_SLOT
	BRA @UNKNOWN0
	JSR MOVEMENT_DATA_READ8_COPY
	STA ENTITY_ALLOCATION_MIN_SLOT
	TAX
	INC
	INC
	STA ENTITY_ALLOCATION_MAX_SLOT
	STY $94
	JSR DELETE_ENTITY_OFFSET
	LDY $94
	JMP @UNKNOWN0
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$003C
	STA ENTITY_ALLOCATION_MAX_SLOT
	STZ NEW_ENTITY_VAR1
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STZ NEW_ENTITY_POS_Z
	JSR MOVEMENT_DATA_READ16_COPY
	TAX
	JSR MOVEMENT_DATA_READ16_COPY
	STY $94
	STA NEW_ENTITY_VAR0
	LDA $88
	STA NEW_ENTITY_VAR2
	TXA
	AND #$7FFF
	JMP INIT_ENTITY
