
UNKNOWN_EF0115: ;$EF0115
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDY a:window_stats::tilemap_address,X
	STY $10
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	TAX
	STX $0E
	BRA @UNKNOWN2
@UNKNOWN0:
	LDY $10
	LDA __BSS_START__,Y
	BEQ @UNKNOWN1
	JSL FREE_TILE_SAFE
@UNKNOWN1:
	LDA #$0040
	LDY $10
	STA __BSS_START__,Y
	INY
	INY
	STY $10
	LDX $0E
	DEX
	STX $0E
@UNKNOWN2:
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA REDRAW_ALL_WINDOWS
=======
	LDA #$0001
	STA UNKNOWN_7E9623
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C07C5B
	PLD
	RTL
