
<<<<<<< HEAD
UNKNOWN_EFD95E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
=======
UNKNOWN_EFD95E: ;$EFD95E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C200D9
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA DEBUG_MODE_NUMBER
	CMP #$0001
	BNE @UNKNOWN0
	JSL LOAD_WINDOW_GFX
	LDA #$0001
	JSL UNKNOWN_C44963
	JSL UNKNOWN_C47F87
	BRA @UNKNOWN2
@UNKNOWN0:
	COPY_TO_VRAM1 DEBUG_MENU_FONT, $6100, $1000, $00
	.A16
	LDA #$0000
	STA [$06]
	COPY_TO_VRAM1P $06, $7C00, $800, $03
	.A16
	LDA DEBUG_MODE_NUMBER
	CMP #$0003
	BEQ @UNKNOWN1
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA PALETTES+4
	BRA @UNKNOWN2
@UNKNOWN1:
	LOADPTR UNKNOWN_EFEF9F, @LOCAL00
	LDX #BPP2PALETTE_SIZE * 3
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY16
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$FFFF
	STA CUR_TEXT_PAL+4
	BRA @UNKNOWN2
@UNKNOWN1:
	LOADPTR UNKNOWN_EFEF9F, $0E
	LDX #$0018
	LDA #$0200
	JSL MEMCPY16
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
