
<<<<<<< HEAD
UNKNOWN_EFDA05:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
=======
UNKNOWN_EFDA05: ;$EFDA05
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C08726
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
<<<<<<< HEAD
	LDA #$2F
	STA SPRITEMAP_BANK
=======
	LDA #$002F
	STA UNKNOWN_7E000B
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	STZ UNREAD_7EB55D
	STZ DEBUG_MENU_BUTTONS_PRESSED
	STZ DEBUG_MENU_CURSOR_POSITION
<<<<<<< HEAD
	STZ UNREAD_7EB551
	STZ VIEW_ATTRIBUTE_MODE
	LDA #9
=======
	STZ UNKNOWN_7EB551
	STZ UNKNOWN_7EB55F
	LDA #$0009
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C08D79
	LDY #$0000
	LDX #$3800
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #$2000
	LDX #$5800
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG2_VRAM_LOCATION
	LDY #$6000
	LDX #$7C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LDA #$0002
	JSL SET_OAM_SIZE
	LDA #$0000
	STA [$06]
	MOVE_INT $06, $0E
	LDY #$0000
	TYX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	JSL PREPARE_VRAM_COPY
	.A16
<<<<<<< HEAD
	LOADPTR UNKNOWN_EFF1BB, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	LDA #.LOWORD(PALETTES)
=======
	LOADPTR UNKNOWN_EFF1BB, $0E
	LDX #$0200
	LDA #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	JSL UNKNOWN_EFD95E
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$0001
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #$0034
	TYX
	LDA #EVENT_SCRIPT::EVENT_000
	JSL INIT_ENTITY_WIPE
<<<<<<< HEAD
	STA DEBUG_CURSOR_ENTITY
	STZ NPC_SPAWNS_ENABLED
	STZ ENEMY_SPAWNS_ENABLED
	END_C_FUNCTION
=======
	STA UNKNOWN_7EB553
	STZ UNKNOWN_7E4A58
	STZ UNKNOWN_7E4A5A
	PLD
	RTS
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
