
UNKNOWN_EFE895: ;$EFE895
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	STX $0E
	JSL TEST_SRAM_SIZE
	CMP #$0000
	BEQ @GOOD_SRAM_SIZE
	MOVE_INT RAND_A, RAND_A_BACKUP
	LDA FRAME_COUNTER
	AND #$00FF
<<<<<<< HEAD
	STA FRAME_COUNTER_BACKUP
	LDX @LOCAL00
	STX REPLAY_TRANSITION_STYLE
=======
	STA UNKNOWN_7EB571
	LDX $0E
	STX UNKNOWN_7EB573
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@GOOD_SRAM_SIZE:
	PLD
	RTL
