
ALLOC_SPRITE_MEM: ;$C01C11
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TXY
	STA $0E
	LDX #$0000
	BRA @UNKNOWN3
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ORA #$0080
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA SPRITE_VRAM_TABLE,X
=======
	STA $02
	LDA UNKNOWN_7E4A00,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CMP $02
	BEQ @UNKNOWN1
	LDA $0E
	CMP #$8000
	BNE @UNKNOWN2
@UNKNOWN1:
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA SPRITE_VRAM_TABLE,X
@UNKNOWN2:
	INX
@UNKNOWN3:
	CPX #$0058
	BCC @UNKNOWN0
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
