
DISPLAY_FAULTY_GAMEPAK_SCREEN: ;$C30142
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	JSL UNKNOWN_C40B51
<<<<<<< HEAD
	LOADPTR FAULTY_GAME_PAK_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR FAULTY_GAME_PAK_ARRANGEMENT, @LOCAL00
	LOADPTR BUFFER + $4000, @LOCAL01
=======
	LOADPTR FAULTY_GAME_PAK_GRAPHICS, $0E
	LOADPTR UNKNOWN_7F0000, $12
	JSL DECOMP
	LOADPTR FAULTY_GAME_PAK_ARRANGEMENT, $0E
	LOADPTR UNKNOWN_7F4000, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	JSL UNKNOWN_C40B75
	PLD
	RTL
