
<<<<<<< HEAD
MEMCPY16:
	STX MEMCPY_WORDS_LEFT
	LSR MEMCPY_WORDS_LEFT
=======
MEMCPY16: ;$C08ED2
	STX UNKNOWN_7E00A5
	LSR UNKNOWN_7E00A5
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAX
	LDY #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA [$0E],Y
	STA __BSS_START__,X
	INX
	INX
	INY
	INY
@UNKNOWN1:
	DEC MEMCPY_WORDS_LEFT
	BPL @UNKNOWN0
	RTL
