
SAVE_GAME_BLOCK: ;$EF088F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 34
.IF .DEFINED(JPN)
	TAX
	STX $20
.ELSE
	TAY
	STY $20
.ENDIF
@UNKNOWN0:
	MOVE_INT TIMER, $06
	MOVE_INT $06, GAME_STATE+game_state::timer
.IF .DEFINED(JPN)
	LDY #$0500
	LDX $20
	TXA
.ELSE
	LDY $20
	TYA
	LDY #$0500
.ENDIF
	JSL MULT16
	STORE_INT1632 $0A
	MOVE_INT $0A, $06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + .SIZEOF(save_header), $06
	MOVE_INT $06, $1C
	PROMOTENEARPTR GAME_STATE, $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $16
.IF .DEFINED(JPN)
	LDA #.HIWORD(__BSS_START__)
	STA $18
.ELSE ; This is a stupid regression...
	TDC
	CLC
	ADC #$0018
	TAX
	STX $1A
	LDA #.HIWORD(__BSS_START__)
	STA __BSS_START__,X
.ENDIF
	MOVE_INT $1C, $06
	MOVE_INT $06, $0E
	MOVE_INT $16, $06
	MOVE_INT $06, $12
	LDA #.SIZEOF(game_state)
	JSL MEMCPY24
	LDA #.SIZEOF(game_state)
	MOVE_INTX $1C, $06
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL04+2
	PROMOTENEARPTR PARTY_CHARACTERS, @VIRTUAL06
=======
	ADC $06
	STA $06
	STA $1C
	LDA $08
	STA $1E
	PROMOTENEARPTR CHAR_STRUCT, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $16
	LDA #.HIWORD(__BSS_START__)
.IF .DEFINED(JPN)
	STA $18
.ELSE
	LDX $1A
	STA __BSS_START__,X
.ENDIF
	MOVE_INT $1C, $06
	MOVE_INT $06, $0E
	MOVE_INT $16, $06
	MOVE_INT $06, $12
	LDA #.SIZEOF(char_struct) * 6
	JSL MEMCPY24
	LDA #.SIZEOF(char_struct) * 6
	MOVE_INTX $1C, $06
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL04+2
	PROMOTENEARPTR EVENT_FLAGS, @VIRTUAL06
=======
	ADC $06
	STA $06
	STA $1C
	LDA $08
	STA $1E
	PROMOTENEARPTR EVENT_FLAG, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $16
	LDA #.HIWORD(__BSS_START__)
.IF .DEFINED(JPN)
	STA $18
.ELSE
	LDX $1A
	STA __BSS_START__,X
.ENDIF
	MOVE_INT $1C, $06
	MOVE_INT $06, $0E
	MOVE_INT $16, $06
	MOVE_INT $06, $12
	LDA #$0080
	JSL MEMCPY24
	MOVE_INT $0A, $06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + save_header::checksum, $06
.IF .DEFINED(JPN)
	LDX $20
	TXA
.ELSE
	LDY $20
	TYA
.ENDIF
	JSR CALC_SAVE_BLOCK_ADD_CHECKSUM
.IF .DEFINED(JPN)
	TAY
	STY $1A
	TYA
.ELSE
	TAX
	STX $1A
	TXA
.ENDIF
	STA [$06]
.IF .DEFINED(JPN)
	LDX $20
	TXA
.ELSE
	LDY $20
	TYA
.ENDIF
	JSR CALC_SAVE_BLOCK_ADD_CHECKSUM
	STA $02
.IF .DEFINED(JPN)
	LDY $1A
	TYA
.ELSE
	LDX $1A
	TXA
.ENDIF
	CMP $02
	BNEL @UNKNOWN0
	MOVE_INT $0A, $06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + save_header::checksum_complement, $06
.IF .DEFINED(JPN)
	LDX $20
	TXA
.ELSE
	LDY $20
	TYA
.ENDIF
	JSR CALC_SAVE_BLOCK_XOR_CHECKSUM
.IF .DEFINED(JPN)
	TAY
	STY $1A
	TYA
.ELSE
	TAX
	STX $1A
	TXA
.ENDIF
	STA [$06]
.IF .DEFINED(JPN)
	LDX $20
	TXA
.ELSE
	LDY $20
	TYA
.ENDIF
	JSR CALC_SAVE_BLOCK_XOR_CHECKSUM
	STA $02
.IF .DEFINED(JPN)
	LDY $1A
	TYA
.ELSE
	LDX $1A
	TXA
.ENDIF
	CMP $02
	BNEL @UNKNOWN0
	PLD
	RTS
