
<<<<<<< HEAD
DECOMP_NINTENDO_PRESENTATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
	LOADPTR NINTENDO_PRESENTATION_ARRANGEMENT, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
=======
DECOMP_NINTENDO_PRESENTATION: ;$C4DDD0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LOADPTR UNKNOWN_7F0000, $06
	LOADPTR NINTENDO_PRESENTATION_ARRANGEMENT, $0E
	MOVE_INT $06, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	JSR UNKNOWN_C4DCF6
	COPY_TO_VRAM1P $06, $7C00, $800, $00
	.A16
<<<<<<< HEAD
	LOADPTR BUFFER + $800, @VIRTUAL06
	LOADPTR NINTENDO_PRESENTATION_GRAPHICS, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
=======
	LOADPTR UNKNOWN_7F0800, $06
	LOADPTR NINTENDO_PRESENTATION_GRAPHICS, $0E
	MOVE_INT $06, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	COPY_TO_VRAM1P $06, $6000, $400, $00
	.A16
<<<<<<< HEAD
	LOADPTR NINTENDO_ITOI_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR NINTENDO_ITOI_PALETTE, $0E
	PROMOTENEARPTR $200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
<<<<<<< HEAD
	STZ PALETTES
	LDA #24
=======
	STZ CUR_TEXT_PAL
	LDA #$0018
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0856B
	PLD
	RTL
