
LOGO_SCREEN_LOAD: ;$C0EE68
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	STA $02
	LDA #$0001
	JSL UNKNOWN_C08D79
	LDY #$0000
	LDX #$4000
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA $02
	BEQ @UNKNOWN1
	CMP #$0001
	BEQ @UNKNOWN2
	CMP #$0002
	BEQL @UNKNOWN4
	JMP @UNKNOWN5
@UNKNOWN1:
<<<<<<< HEAD
	LOADPTR NINTENDO_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
=======
	LOADPTR NINTENDO_GRAPHICS, $0E
	LOADPTR UNKNOWN_7F0000, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	LOADPTR NINTENDO_ARRANGEMENT, $0E
	LOADPTR INTRO_BG2_BUFFER, $12
	JSL DECOMP
<<<<<<< HEAD
	LOADPTR NINTENDO_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR NINTENDO_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
	JMP @UNKNOWN5
@UNKNOWN2:
<<<<<<< HEAD
	LOADPTR APE_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
=======
	LOADPTR APE_GRAPHICS, $0E
	LOADPTR UNKNOWN_7F0000, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	LOADPTR APE_ARRANGEMENT, $0E
	LOADPTR INTRO_BG2_BUFFER, $12
	JSL DECOMP
<<<<<<< HEAD
	LOADPTR APE_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR APE_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
	BRA @UNKNOWN5
@UNKNOWN4:
<<<<<<< HEAD
	LOADPTR HALKEN_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
=======
	LOADPTR HALKEN_GRAPHICS, $0E
	LOADPTR UNKNOWN_7F0000, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
	LOADPTR HALKEN_ARRANGEMENT, $0E
	LOADPTR INTRO_BG2_BUFFER, $12
	JSL DECOMP
<<<<<<< HEAD
	LOADPTR HALKEN_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR HALKEN_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
@UNKNOWN5:
<<<<<<< HEAD
	COPY_TO_VRAM1 BUFFER, $0000, $8000, 0
=======
	COPY_TO_VRAM1 UNKNOWN_7F0000, $0000, $8000, $00
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	.A16
	COPY_TO_VRAM1 INTRO_BG2_BUFFER, $4000, $800, $00
	.A16
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
