
NAME_A_CHARACTER: ;$C1EC04
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	STY $14
	TXY
	STY $12
	STA $02
	LDX $28
	STX $04
	MOVE_INT $24, $06
	JSL SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_NAME_BOX
.IF .DEFINED(PROTOTYPE19950327)
.ELSE
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
.ENDIF
	LDY $12
	LDA __BSS_START__,Y
	AND #$00FF
<<<<<<< HEAD
	BEQ @UNKNOWN2
.IF .DEFINED(JPN)
	TYA
	PROMOTENEARPTRA @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA @VIRTUAL02
	JSR PRINT_STRING
	LDX #.LOWORD(WINDOW_STATS) + window_stats::text_x
	STX @LOCAL01
	STX @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	LDX @LOCAL03
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCS @UNKNOWN3
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX @LOCAL01
	STX @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
.ELSE
	LDX @VIRTUAL02
=======
	BEQ @UNKNOWN0
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	JSL UNKNOWN_C440B5
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA $02
	JSL UNKNOWN_C441B7
@UNKNOWN1:
	LDX #$0000
	TXA
	JSL UNKNOWN_C438A5
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_MESSAGE
.IF .DEFINED(PROTOTYPE19950327)
.ELSE
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
.ENDIF
	MOVE_INT $06, $0E
	LDA $04
	JSR PRINT_STRING
	LDX #$0000
	LDA #$0001
	JSR CC_13_14
	STZ $0E
	LDA $14
	STA $10
	LDY $12
	LDX $02
	LDA #$001A
	JSR TEXT_INPUT_DIALOG
	TAX
	STX $14
	LDA #$001C
	JSL CLOSE_WINDOW
	LDX $14
	TXA
	PLD
	RTS
