
SHOW_TITLE_SCREEN: ;$C3F3C5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 28
	TAX
<<<<<<< HEAD
	STX TITLE_SCREEN_QUICK_MODE
	LDA #0
	STA @VIRTUAL04
=======
	STX UNKNOWN_7E9F75
	LDA #$0000
	STA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C08726
	JSL UNKNOWN_C0927C
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
	LDA $1A
	INC
	STA $1A
	CMP #$001E
	BCC @UNKNOWN0
@UNKNOWN1:
	LDA #$000B
	JSL UNKNOWN_C08D79
	LDA #$0003
	JSL SET_OAM_SIZE
	LDY #$0000
	LDX #$5800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL UNKNOWN_C0EBE0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0011
	STA TM_MIRROR
	JSL OAM_CLEAR
	.A16
	LDY #$0000
	TYX
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
	LDA TITLE_SCREEN_QUICK_MODE
	BNEL @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
=======
	STZ $0E
	LDX #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0200
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C08744
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000F
	STA INIDISP_MIRROR
	JSL WAIT_UNTIL_NEXT_FRAME
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LOADPTR UNKNOWN_E1AE7C, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR UNKNOWN_E1AE7C, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0100
	CLC
	ADC $06
	STA $06
	STA $12
	LDA $08
	STA $14
	JSL DECOMP
	JSL UNKNOWN_C496F9
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
=======
	STZ $0E
	LDX #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0200
	JSL MEMSET16
	LDX #$0100
	LDA #$003C
	JSL UNKNOWN_C496E7
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDX #0
	STX @LOCAL03
=======
	LDA #$0018
	STA UNKNOWN_7E0030
	LDX #$0000
	STX $18
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN4
@UNKNOWN3:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL UNKNOWN_C1004E
	LDX $18
	INX
	STX $18
@UNKNOWN4:
	STX $02
	REP #PROC_FLAGS::ACCUM8
	LDA #$003C
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN3
	BRA @UNKNOWN11
@UNKNOWN7:
	LDX #$0001
	LDA #$0004
	JSL FADE_IN
	LDX #$0000
	STX $1A
	BRA @UNKNOWN9
@UNKNOWN8:
	JSL UNKNOWN_C1004E
	LDX $1A
	INX
	STX $1A
@UNKNOWN9:
	STX $02
	LDA #$003C
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN8
@UNKNOWN11:
	LDA #$0000
	STA $02
	BRA @UNKNOWN15
@UNKNOWN12:
	LDA $04
	BNE @UNKNOWN14
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @UNKNOWN13
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @UNKNOWN13
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @UNKNOWN14
@UNKNOWN13:
	LDA #$0001
	STA $02
	BRA @UNKNOWN16
@UNKNOWN14:
	JSL UNKNOWN_C1004E
@UNKNOWN15:
	LDA ACTIONSCRIPT_STATE
	BEQ @UNKNOWN12
<<<<<<< HEAD
	LDA ACTIONSCRIPT_STATE
	CMP #2
=======
	LDA UNKNOWN_7E9641
	CMP #$0002
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN12
@UNKNOWN16:
	LDA TITLE_SCREEN_QUICK_MODE
	BNE @UNKNOWN17
	LDA ACTIONSCRIPT_STATE
	BNE @UNKNOWN17
	JSL UNKNOWN_EF04DC
	STA $02
@UNKNOWN17:
	LDY #$0000
	LDX #$0004
	LDA #$0001
	JSL FADE_OUT_WITH_MOSAIC
	LDA $04
	BNE @UNKNOWN18
<<<<<<< HEAD
	STZ ACTIONSCRIPT_STATE
	LDA #0
=======
	STZ UNKNOWN_7E9641
	LDA #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C474A8
	JSL UNKNOWN_C0927C
	LDA $02
	BRA @UNKNOWN23
@UNKNOWN18:
	LDY #$0000
	STY $16
	BRA @UNKNOWN22
@UNKNOWN19:
	TYA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::TITLE_SCREEN_1
	BCC @UNKNOWN21
	CMP #EVENT_SCRIPT::TITLE_SCREEN_11
	BGT @UNKNOWN21
	TYA
	JSL UNKNOWN_C09C35
@UNKNOWN21:
	LDY $16
	TYA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	INY
	STY $16
@UNKNOWN22:
	CPY #$001E
	BCC @UNKNOWN19
	JSL UNKNOWN_C08726
	JSL RELOAD_MAP
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
	LDX #$0001
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL FADE_IN
@UNKNOWN23:
	PLD
	RTL
