
<<<<<<< HEAD
UNKNOWN_C435E4:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
=======
UNKNOWN_C435E4: ;$C435E4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA UNKNOWN_7E89CE
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN6
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN0
	LDX NUM_BATTLERS_IN_BACK_ROW
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX NUM_BATTLERS_IN_FRONT_ROW
@UNKNOWN1:
	STX $02
	LDX #$0000
	STX $0E
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN3
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
	BRA @UNKNOWN4
@UNKNOWN3:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
@UNKNOWN4:
	LDX $0E
	INX
	STX $0E
@UNKNOWN5:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP $02
	BCC @UNKNOWN2
<<<<<<< HEAD
	STZ ENEMY_TARGETTING_FLASHING
	LDA #.LOWORD(-1)
	STA CURRENT_FLASHING_ROW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
=======
	STZ UNKNOWN_7EADA2
	LDA #$FFFF
	STA UNKNOWN_7E89CE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7E9623
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
