
UNKNOWN_C43657: ;$C43657
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
<<<<<<< HEAD
	STX @LOCAL00
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
=======
	STX $0E
	LDA UNKNOWN_7E89CE
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN0
	JSL UNKNOWN_C435E4
@UNKNOWN0:
<<<<<<< HEAD
	LDX @LOCAL00
	STX CURRENT_FLASHING_ROW
	LDA CURRENT_FLASHING_ROW
=======
	LDX $0E
	STX UNKNOWN_7E89CE
	LDA UNKNOWN_7E89CE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN1
	LDA NUM_BATTLERS_IN_BACK_ROW
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA NUM_BATTLERS_IN_FRONT_ROW
@UNKNOWN2:
	STA $02
	LDX #$0000
	STX $0E
	BRA @UNKNOWN6
@UNKNOWN3:
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN4
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA BATTLERS_TABLE+74,X
	BRA @UNKNOWN5
@UNKNOWN4:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA BATTLERS_TABLE+74,X
@UNKNOWN5:
	LDX $0E
	INX
	STX $0E
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP $02
	BCC @UNKNOWN3
<<<<<<< HEAD
	LDA #1
	STA ENEMY_TARGETTING_FLASHING
=======
	LDA #$0001
	STA UNKNOWN_7EADA2
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
