
UNKNOWN_C43D24: ;$C43D24
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 17
	JSL REDIRECT_C438A5
	LDA NEW_TEXT_PIXEL_OFFSET
	AND #$00FF
	BEQ @UNKNOWN0
	LDA NEW_TEXT_PIXEL_OFFSET
	AND #$00FF
	CLC
	ADC VWF_X
	STA VWF_X
	LDA VWF_TILE
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	STA $0F
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA $0E
	LDX #$0020
	REP #PROC_FLAGS::ACCUM8
	LDA $0F
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA NEW_TEXT_PIXEL_OFFSET
	STA LAST_TEXT_PIXEL_OFFSET_SET
	STZ NEW_TEXT_PIXEL_OFFSET
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
