
UNKNOWN_C43E31: ;$C43E31
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	TAY
	STY $14
	MOVE_INT $24, $06
	LDX #$0000
	STX $12
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	STA @LOCAL01
.IF .DEFINED(PROTOTYPE19950327)
	BRA @UNKNOWN3
.ELSE
=======
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	STA $02
	STA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JMP @UNKNOWN3
@UNKNOWN0:
	DEY
	STY $14
	AND #$00FF
	SEC
	SBC #$0050
	AND #$007F
<<<<<<< HEAD
	STA @LOCAL00
	INC @VIRTUAL06
.IF !.DEFINED(PROTOTYPE19950327)
	LDA FORCE_NORMAL_FONT_FOR_LENGTH_CALCULATIONS
=======
	STA $0E
	INC $06
	LDA UNKNOWN_7EB4CE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BEQ @UNKNOWN1
	MOVE_INT FONT_PTR_TABLE, $0A
	LDA $0E
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	BRA @UNKNOWN2
@UNKNOWN1:
	LOADPTR FONT_PTR_TABLE, $0A
	LDA $10
	STA $02
	LDX $02
	LDA a:window_stats::font,X
	OPTIMIZED_MULT $04, .SIZEOF(font_table_entry)
	CLC
	ADC $0A
	STA $0A
	DEREFERENCE_PTR_TO $0A, $0A
	LDA $0E
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
@UNKNOWN2:
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA CHARACTER_PADDING
=======
	STA $02
	LDA UNKNOWN_7E5E6D
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CLC
	ADC $02
	STA $04
	LDX $12
	TXA
	CLC
	ADC $04
	TAX
	STX $12
@UNKNOWN3:
	LDA [$06]
	AND #$00FF
	BEQ @UNKNOWN4
	LDY $14
	BEQ @UNKNOWN4
	JMP @UNKNOWN0
@UNKNOWN4:
	LDX $12
	TXA
	PLD
	RTL
