
UNKNOWN_C440B5: ;$C440B5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $04
	STA $02
	SEP #PROC_FLAGS::ACCUM8
	STZ $0E
	LDX #$0018
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(KEYBOARD_INPUT_CHARACTER_WIDTHS)
	JSL MEMSET16
	LDY #$0000
	STY $10
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA $0F
	AND #$00FF
	SEC
	SBC #$0050
	AND #$007F
	TAX
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA @LOCAL01
	STA KEYBOARD_INPUT_CHARACTERS,Y
=======
	LDA $0F
	STA UNKNOWN_7E1B86,Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT FONT_PTR_TABLE, $06
	TXA
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	TAX
	SEP #PROC_FLAGS::ACCUM8
	CLC
<<<<<<< HEAD
	ADC CHARACTER_PADDING
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX @VIRTUAL02
=======
	ADC UNKNOWN_7E5E6D
	STA UNKNOWN_7E1B6E,Y
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	LDA #$0000
	JSL UNKNOWN_C44E61
	LDY $10
	INY
	STY $10
	INC $02
@UNKNOWN1:
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $0F
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN2
	TYA
	CMP $04
	BNE @UNKNOWN0
@UNKNOWN2:
	STY NEXT_KEYBOARD_INPUT_INDEX
	TYA
	CMP $04
	BCS @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #32
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	LDA #6
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX #112
=======
	LDA #$0020
	STA UNKNOWN_7E1B56,Y
	LDA #$0006
	STA UNKNOWN_7E1B6E,Y
	LDX #$0070
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL UNKNOWN_C44E61
	LDY $10
	TYX
	SEP #PROC_FLAGS::ACCUM8
	STZ KEYBOARD_INPUT_CHARACTERS,X
	INY
	STY $10
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	STY $04
	SEC
	SBC $04
	STA $02
	CLC
	SBC #$0000
	BRANCHLTEQS @UNKNOWN7
	BRA @UNKNOWN6
@UNKNOWN5:
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #3
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	LDX #83
=======
	LDA #$0003
	STA UNKNOWN_7E1B56,Y
	LDX #$0053
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL UNKNOWN_C44E61
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #3
	LDY @LOCAL02
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
=======
	LDA #$0003
	LDY $10
	STA UNKNOWN_7E1B6E,Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA $02
	DEC
	STA $02
	INY
	STY $10
@UNKNOWN6:
	LDA $02
	BNE @UNKNOWN5
@UNKNOWN7:
	PLD
	RTL
