
UNKNOWN_C441B7: ;$C441B7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 17
	STA $04
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA $0E
	LDX #$0680
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
<<<<<<< HEAD
	LDA #3
	STA @VIRTUAL02
	STZ NEXT_KEYBOARD_INPUT_INDEX
=======
	LDA #$0003
	STA $02
	STZ UNKNOWN_7E9662
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	STZ $0E
	LDX #$0018
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(KEYBOARD_INPUT_CHARACTERS)
	JSL MEMSET16
	LDX #$0070
	LDA #$0000
	JSL UNKNOWN_C44E61
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #32
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS
	LDY #1
	STY @LOCAL01
=======
	LDA #$0020
	STA UNKNOWN_7E1B56
	LDY #$0001
	STY $0F
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA $02
	SEP #PROC_FLAGS::ACCUM8
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT FONT_PTR_TABLE, $06
	LDA $02
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	TAX
	SEP #PROC_FLAGS::ACCUM8
	CLC
<<<<<<< HEAD
	ADC CHARACTER_PADDING
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX #83
=======
	ADC UNKNOWN_7E5E6D
	STA UNKNOWN_7E1B6E,Y
	LDX #$0053
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL UNKNOWN_C44E61
	LDY $0F
	INY
	STY $0F
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	TYA
	CMP $04
	BCC @UNKNOWN0
	PLD
	RTL
