
UNKNOWN_C4424A: ;$C4424A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	CMP #$0070
	BNE @UNKNOWN0
	LDX NEXT_KEYBOARD_INPUT_INDEX
	SEP #PROC_FLAGS::ACCUM8
	STZ KEYBOARD_INPUT_CHARACTERS,X
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDX NEXT_KEYBOARD_INPUT_INDEX
	STA KEYBOARD_INPUT_CHARACTERS,X
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	SEC
	SBC #$0050
	AND #$007F
	STA $0E
	SEP #PROC_FLAGS::ACCUM8
	LDX NEXT_KEYBOARD_INPUT_INDEX
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,X
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT FONT_PTR_TABLE, $06
	LDA $0E
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC CHARACTER_PADDING
	LDX NEXT_KEYBOARD_INPUT_INDEX
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,X
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
