
UNKNOWN_C466C1: ;$C466C1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	JSL UNKNOWN_C07C5B
<<<<<<< HEAD
	STZ PLAYER_INTANGIBILITY_FRAMES
	LDA @LOCAL01
=======
	STZ UNKNOWN_7E5D58
	LDA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	DEC
	STA SPAWNING_TRAVELLING_PHOTOGRAPHER_ID
	DISPLAY_TEXT_PTR MSG_EVT_PHOTOGRAPHER
	LDA $12
	JSL UNKNOWN_C4343E
	PLD
	RTL
