
UNKNOWN_C467E6: ;$C467E6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA #$0000
	STA $0E
	BRA @UNKNOWN2
@UNKNOWN0:
	ASL
	TAX
<<<<<<< HEAD
	LDA ENTITY_SPRITE_IDS,X
	CMP #OVERWORLD_SPRITE::LEAVES_FOR_TESSIE_SCENE
=======
	LDA ENTITY_TPT_ENTRY_SPRITES,X
	CMP #$016F
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN1
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
@UNKNOWN1:
	LDA $0E
	INC
	STA $0E
@UNKNOWN2:
	CMP #$001E
	BCC @UNKNOWN0
	PLD
	RTL
