
UNKNOWN_C4681A: ;$C4681A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
<<<<<<< HEAD
	LDA ENTITY_NPC_IDS,X
	STA @LOCAL01
	CMP #.LOWORD(-1)
=======
	LDA ENTITY_TPT_ENTRIES,X
	STA $12
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN1
	LOADPTR NPC_CONFIG_TABLE, $0A
	LDA $12
	OPTIMIZED_MULT $04, 17
	CLC
	ADC #$0009
	CLC
	ADC $0A
	STA $0A
	DEREFERENCE_PTR_TO $0A, $06
	MOVE_INT_CONSTANT NULL, $0A
	CMP32 $06, $0A
	BEQ @UNKNOWN1
	MOVE_INT $06, $0E
	LDA #$0008
	JSL UNKNOWN_C064E3
@UNKNOWN1:
	PLD
	RTL
