
<<<<<<< HEAD
UNKNOWN_C46D4B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY SPAWNING_TRAVELLING_PHOTOGRAPHER_ID
=======
UNKNOWN_C46D4B: ;$C46D4B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDY UNKNOWN_7E9E35
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LOADPTR PHOTOGRAPHER_CFG_TABLE, $06
	TYA
	LDY #.SIZEOF(photographer_config_entry)
	JSL MULT168
	STA $0E
	CLC
	ADC #photographer_config_entry::photographer_x
	MOVE_INTY $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	ASL
	ASL
	ASL
	STA ENTITY_ABS_X_TABLE,X
	LDA $0E
	CLC
	ADC #photographer_config_entry::photographer_y
	CLC
	ADC $06
	STA $06
	LDA [$06]
	ASL
	ASL
	ASL
	STA ENTITY_ABS_Y_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STZ ENTITY_ABS_Y_FRACTION_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STZ ENTITY_ABS_X_FRACTION_TABLE,X
	PLD
	RTL
