
<<<<<<< HEAD
UNKNOWN_C4733C:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA LOADED_MAP_TILE_COMBO
=======
UNKNOWN_C4733C: ;$C4733C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7E436E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	TAX
	LDA f:TILESET_TABLE,X
	JSL UNKNOWN_C006F2
	RTL
