
UNKNOWN_C4746B: ;$C4746B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $02
	LDY #$0000
	STY $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX $02
	TYA
	JSR UNKNOWN_C473D0
	LDY $0E
	INY
	STY $0E
@UNKNOWN1:
	CPY #$0010
	BCC @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
