
UNKNOWN_C47F87: ;$C47F87
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	TAX
	DEX
	LDA GAME_STATE+game_state::player_controlled_party_members,X
	AND #$00FF
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	LDA a:char_struct::afflictions,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN0
	CPX #STATUS_0::DIAMONDIZED
	BNE @UNKNOWN1
@UNKNOWN0:
	LDA DISABLED_TRANSITIONS
	BNE @UNKNOWN1
<<<<<<< HEAD
	LOADPTR TEXT_WINDOW_FLAVOUR_PALETTES+320, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 2
	LDA #.LOWORD(PALETTES)
=======
	LOADPTR TEXT_WINDOW_FLAVOUR_PALETTES+320, $0E
	LDX #$0040
	LDA #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	BRA @UNKNOWN2
@UNKNOWN1:
	LOADPTR TEXT_WINDOW_FLAVOUR_PALETTES, $06
	LDA GAME_STATE+game_state::text_flavour
	AND #$00FF
	DEC
	OPTIMIZED_MULT $04, 3
	TAX
	LDA f:TEXT_WINDOW_PROPERTIES,X
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #BPP4PALETTE_SIZE * 2
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY16
@UNKNOWN2:
	STZ PALETTES
	LDA #8
=======
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #$0040
	LDA #$0200
	JSL MEMCPY16
@UNKNOWN2:
	STZ CUR_TEXT_PAL
	LDA #$0008
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0856B
	PLD
	RTL
