
<<<<<<< HEAD
UNKNOWN_C48C97:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL01
	LDA AUTO_MOVEMENT_DEMO_INDEX
	BNE @UNKNOWN0
	LDX #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER+1)
	STX @LOCAL00
	STX @VIRTUAL02
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
=======
UNKNOWN_C48C97: ;$C48C97
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $04
	STA $10
	LDA UNKNOWN_7E9F18
	BNE @UNKNOWN0
	LDX #.LOWORD(UNKNOWN_7E9E58+1)
	STX $0E
	STX $02
	LDA UNKNOWN_7E9F18
	OPTIMIZED_MULT $04, 3
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	BNE @UNKNOWN0
	LDA $10
	STA $04
	LDX $0E
	STA __BSS_START__,X
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA AUTO_MOVEMENT_DEMO_BUFFER
	BRA @UNKNOWN4
@UNKNOWN0:
	.A16
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @LOCAL00
	LDA #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER+1)
	STA @VIRTUAL02
	LDA @LOCAL01
	STA @VIRTUAL04
	LDA @LOCAL00
=======
	LDA #$0001
	STA UNKNOWN_7E9E58
	BRA @UNKNOWN4
@UNKNOWN0:
	.A16
	LDA UNKNOWN_7E9F18
	OPTIMIZED_MULT $04, 3
	STA $0E
	LDA #.LOWORD(UNKNOWN_7E9E58+1)
	STA $02
	LDA $10
	STA $04
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	CMP $04
	BNE @UNKNOWN1
	LDA $0E
	CLC
	ADC #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	BRA @UNKNOWN4
@UNKNOWN1:
	LDA AUTO_MOVEMENT_DEMO_INDEX
	INC
<<<<<<< HEAD
	STA AUTO_MOVEMENT_DEMO_INDEX
	CMP #64
=======
	STA UNKNOWN_7E9F18
	CMP #$0040
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRK
	BNE @UNKNOWN3
@UNKNOWN2:
	BRA @UNKNOWN2
@UNKNOWN3:
	OPTIMIZED_MULT $04, 3
	CLC
	ADC $02
	TAX
	LDA $10
	STA $04
	STA __BSS_START__,X
<<<<<<< HEAD
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA AUTO_MOVEMENT_DEMO_BUFFER,X
=======
	LDA UNKNOWN_7E9F18
	OPTIMIZED_MULT $04, 3
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7E9E58,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
