
<<<<<<< HEAD
UNKNOWN_C48C69:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ AUTO_MOVEMENT_DEMO_INDEX
	LDA #0
	STA @LOCAL00
=======
UNKNOWN_C48C69: ;$C48C69
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	STZ UNKNOWN_7E9F18
	LDA #$0000
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	OPTIMIZED_MULT $04, 3
	TAX
	STZ AUTO_MOVEMENT_DEMO_BUFFER+1,X
	SEP #PROC_FLAGS::ACCUM8
	STZ AUTO_MOVEMENT_DEMO_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	INC
	STA $0E
@UNKNOWN1:
	CMP #$0040
	BCC @UNKNOWN0
	PLD
	RTL
