
<<<<<<< HEAD
UNKNOWN_C48E95:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA AUTO_MOVEMENT_DEMO_INDEX
	INC
	STA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
=======
UNKNOWN_C48E95: ;$C48E95
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA UNKNOWN_7E9F18
	INC
	STA UNKNOWN_7E9F18
	OPTIMIZED_MULT $04, 3
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ AUTO_MOVEMENT_DEMO_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	PROMOTENEARPTR AUTO_MOVEMENT_DEMO_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E9E58, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	JSL UNKNOWN_C0402B
	PLD
	RTL
