
<<<<<<< HEAD
UNKNOWN_C496F0:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	LDY #.LOWORD(MAP_PALETTE_BACKUP)
=======
UNKNOWN_C496F0: ;$C496F0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #.LOWORD(UNKNOWN_7E4476)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR UNKNOWN_C4958E
	RTL
