
UNKNOWN_C49CA8: ;$C49CA8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	AND #$00FF
	CLC
	ADC #$0008
	CLC
	ADC FLYOVER_PIXEL_OFFSET
	STA FLYOVER_PIXEL_OFFSET
	LSR
	LSR
	LSR
	ASL
	ASL
	ASL
	ASL
<<<<<<< HEAD
	STA FLYOVER_BYTE_OFFSET
	END_C_FUNCTION
=======
	STA UNKNOWN_7E9F31
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
