
UNKNOWN_C49C56: ;$C49C56
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
.IF .DEFINED(JPN)
	RESERVE_STACK_SPACE 20
.ELSE
	RESERVE_STACK_SPACE 15
.ENDIF
	CLC
	ADC UNKNOWN_7E3C16
	STA UNKNOWN_7E3C16
	STZ UNKNOWN_7E3C14
	LSR
	LSR
	LSR
.IF !.DEFINED(JPN)
	INC
.ENDIF
	CLC
<<<<<<< HEAD
	ADC FLYOVER_SCREEN_OFFSET
	STA FLYOVER_SCREEN_OFFSET
	CMP #32
	BCC @UNKNOWN0
	SEC
	SBC #32
	STA FLYOVER_SCREEN_OFFSET
=======
	ADC UNKNOWN_7E9F2D
	STA UNKNOWN_7E9F2D
	CMP #$0020
	BCC @UNKNOWN0
	SEC
	SBC #$0020
	STA UNKNOWN_7E9F2D
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
.IF .DEFINED(JPN)
	LDA UNKNOWN_7E3C16
	LSR
	LSR
	LSR
	STA $12
	LDY #$01A0
	JSL MULT16
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDY #$01A0
	LDA $12
	STA $02
	LDA #$0004
	SEC
	SBC $02
	JSL MULT16
	TAX
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMCPY16
	LDA UNKNOWN_7E3C16
	LSR
	LSR
	LSR
	STA $12
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA $0E
	LDY #$01A0
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	JSL MULT16
	TAX
	LDY #$01A0
	LDA $12
	STA $02
	LDA #$0004
	SEC
	SBC $02
	JSL MULT16
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
.ELSE
	JSL WAIT_DMA_FINISHED
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA $0E
	LDX #$0680
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
.ENDIF
	LDA UNKNOWN_7E3C16
	AND #$0007
	STA UNKNOWN_7E3C16
.IF !.DEFINED(JPN)
	STZ FLYOVER_PIXEL_OFFSET
	STZ FLYOVER_BYTE_OFFSET
.ENDIF
	PLD
	RTL
