
UNKNOWN_C4B329: ;$C4B329
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STX $0E
	CMP #$0001
	BEQ @UNKNOWN1
	CMP #$0004
	BEQ @UNKNOWN2
	CMP #$0002
	BEQ @UNKNOWN3
	CMP #$0005
	BEQL @UNKNOWN6
	CMP #$0003
	BEQ @UNKNOWN4
	CMP #$0006
	BEQ @UNKNOWN5
	BRA @UNKNOWN6
@UNKNOWN1:
	TXA
	ASL
	TAX
	LDA f:UNKNOWN_C42A41,X
	CLC
<<<<<<< HEAD
	ADC #8
	STA @VIRTUAL02
	LDA ACTIVE_MANPU_Y
	SEC
	SBC @VIRTUAL02
	STA ACTIVE_MANPU_Y
=======
	ADC #$0008
	STA $02
	LDA UNKNOWN_7EB3FA
	SEC
	SBC $02
	STA UNKNOWN_7EB3FA
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN2:
	LDX $0E
	TXA
	ASL
	TAX
	LDA f:UNKNOWN_C42A1F,X
	SEC
<<<<<<< HEAD
	SBC #8
	STA @VIRTUAL02
	LDA ACTIVE_MANPU_X
	SEC
	SBC @VIRTUAL02
	STA ACTIVE_MANPU_X
=======
	SBC #$0008
	STA $02
	LDA UNKNOWN_7EB3F8
	SEC
	SBC $02
	STA UNKNOWN_7EB3F8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN6
@UNKNOWN3:
	TXA
	ASL
	TAX
	LDA f:UNKNOWN_C42A41,X
	SEC
<<<<<<< HEAD
	SBC #8
	STA @VIRTUAL02
	LDA ACTIVE_MANPU_Y
	SEC
	SBC @VIRTUAL02
	STA ACTIVE_MANPU_Y
=======
	SBC #$0008
	STA $02
	LDA UNKNOWN_7EB3FA
	SEC
	SBC $02
	STA UNKNOWN_7EB3FA
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN6
@UNKNOWN4:
	TXA
	ASL
	TAX
	LDA f:UNKNOWN_C42A41,X
	CLC
<<<<<<< HEAD
	ADC #8
	STA @VIRTUAL02
	LDA ACTIVE_MANPU_Y
	SEC
	SBC @VIRTUAL02
	STA ACTIVE_MANPU_Y
=======
	ADC #$0008
	STA $02
	LDA UNKNOWN_7EB3FA
	SEC
	SBC $02
	STA UNKNOWN_7EB3FA
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN5:
	LDX $0E
	TXA
	ASL
	TAX
	LDA f:UNKNOWN_C42A1F,X
	CLC
<<<<<<< HEAD
	ADC #8
	STA @VIRTUAL02
	LDA ACTIVE_MANPU_X
	SEC
	SBC @VIRTUAL02
	STA ACTIVE_MANPU_X
=======
	ADC #$0008
	STA $02
	LDA UNKNOWN_7EB3F8
	SEC
	SBC $02
	STA UNKNOWN_7EB3F8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN6:
	PLD
	RTS
