
<<<<<<< HEAD
UNKNOWN_C4B59F:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	STX @VIRTUAL02
	STA @LOCAL12
	LDA @PARAM0B
	STA @LOCAL11
	LDY @PARAM0A
	STY @LOCAL10
	LDA @PARAM09
	STA @LOCAL0F
	LDA @PARAM08
	STA @LOCAL0E
	LDX @PARAM07
	STX @LOCAL0D
	LDA @PARAM06
	STA @LOCAL0C
	LDA @PARAM05
	STA @LOCAL0B
	LDX @PARAM04
	STX @LOCAL0A
	MOVE_INT @PARAM03, @VIRTUAL06
	STZ @LOCAL09
	LDA @VIRTUAL02
	STA PATH_HEAP_START
	LDA @VIRTUAL02
	STA PATH_HEAP_CURRENT
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL12
	STA PATH_HEAP_END
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	STA PATH_MATRIX_ROWS
	LDX @VIRTUAL04
	LDY __BSS_START__+2,X
	STY PATH_MATRIX_COLUMNS
	LDX @LOCAL0A
	STX PATH_MATRIX_BORDER
	JSL MULT16
	STA PATH_MATRIX_SIZE
	MOVE_INT @VIRTUAL06, PATH_MATRIX_BUFFER
	LDA @LOCAL11
=======
UNKNOWN_C4B59F: ;$C4B59F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 52
	STY $04
	STX $02
	STA $32
	LDA $54
	STA $30
	LDY $52
	STY $2E
	LDA $50
	STA $2C
	LDA $4E
	STA $2A
	LDX $4C
	STX $28
	LDA $4A
	STA $26
	LDA $48
	STA $24
	LDX $46
	STX $22
	MOVE_INT $42, $06
	STZ $20
	LDA $02
	STA UNKNOWN_7EB438
	LDA $02
	STA UNKNOWN_7EB43A
	LDA $02
	CLC
	ADC $32
	STA UNKNOWN_7EB43C
	LDX $04
	LDA __BSS_START__,X
	STA UNKNOWN_7EB400
	LDX $04
	LDY __BSS_START__+2,X
	STY UNKNOWN_7EB402
	LDX $22
	STX UNKNOWN_7EB404
	JSL MULT16
	STA UNKNOWN_7EB406
	MOVE_INT $06, UNKNOWN_7EB3FC
	LDA $30
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $02
	INC
	INC
	JSR UNKNOWN_C4B587
<<<<<<< HEAD
	STA @LOCAL08
	STA PATH_SEARCH_TEMP_START
	CLC
	ADC @VIRTUAL02
	STA PATH_SEARCH_TEMP_END
	LDA @LOCAL08
	STA PATH_SEARCH_TEMP_B
	STA PATH_SEARCH_TEMP_A
	LDA PATH_MATRIX_COLUMNS
	EOR #$FFFF
	INC
	STA PATH_CARDINAL_OFFSET
	LDA #1
	STA PATH_CARDINAL_OFFSET+2
	LDA PATH_MATRIX_COLUMNS
	STA PATH_CARDINAL_OFFSET+4
	LDA #.LOWORD(-1)
	STA PATH_CARDINAL_OFFSET+6
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::y_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::x_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::y_coord
	LDA #1
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::x_coord
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::y_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::x_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::y_coord
	LDA #.LOWORD(-1)
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::y_coord
	LDA #1
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::y_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::y_coord
	LDA #.LOWORD(-1)
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::y_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::x_coord
	LDA @LOCAL10
	CMP #251
=======
	STA $1E
	STA UNKNOWN_7EB408
	CLC
	ADC $02
	STA UNKNOWN_7EB40A
	LDA $1E
	STA UNKNOWN_7EB40E
	STA UNKNOWN_7EB40C
	LDA UNKNOWN_7EB402
	EOR #$FFFF
	INC
	STA UNKNOWN_7EB410
	LDA #$0001
	STA UNKNOWN_7EB412
	LDA UNKNOWN_7EB402
	STA UNKNOWN_7EB414
	LDA #$FFFF
	STA UNKNOWN_7EB416
	STA UNKNOWN_7EB418
	STZ UNKNOWN_7EB41A
	STZ UNKNOWN_7EB41C
	LDA #$0001
	STA UNKNOWN_7EB41E
	STA UNKNOWN_7EB420
	STZ UNKNOWN_7EB422
	STZ UNKNOWN_7EB424
	LDA #$FFFF
	STA UNKNOWN_7EB426
	STA UNKNOWN_7EB428
	LDA #$0001
	STA UNKNOWN_7EB42A
	STA UNKNOWN_7EB42C
	STA UNKNOWN_7EB42E
	STA UNKNOWN_7EB430
	LDA #$FFFF
	STA UNKNOWN_7EB432
	STA UNKNOWN_7EB434
	STA UNKNOWN_7EB436
	LDA $2E
	CMP #$00FB
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BCC @UNKNOWN0
	LDA #$00FB
	STA $2E
@UNKNOWN0:
	LDA $28
	ASL
	JSR UNKNOWN_C4B587
	STA $1C
	LDY $1C
	LDX $2A
	LDA $28
	JSR UNKNOWN_C4B859
	LDA $2E
	ASL
	ASL
	JSR UNKNOWN_C4B587
	STA $2A
	JSR UNKNOWN_C4B7A5
	STZ $1A
	STZ $18
	LDA #$0000
	STA $04
	JMP @UNKNOWN10
@UNKNOWN1:
	LDA $04
	ASL
	TAY
	LDA ($1C),Y
	STA $02
	STA $32
	LDX $02
	LDA __BSS_START__+2,X
	CMP $1A
	BNE @UNKNOWN2
	LDX $02
	LDA __BSS_START__+4,X
	CMP $18
	BEQ @UNKNOWN6
@UNKNOWN2:
	LDY #$0001
	STY $16
	LDX $02
	LDA __BSS_START__+2,X
	STA $1A
	LDX $02
	LDA __BSS_START__+4,X
	STA $18
	LDA $04
	INC
	STA $1E
	BRA @UNKNOWN4
@UNKNOWN3:
	ASL
	TAY
	LDA ($1C),Y
	TAX
	LDA __BSS_START__+2,X
	CMP $1A
	BNE @UNKNOWN5
	LDA __BSS_START__+4,X
	CMP $18
	BNE @UNKNOWN5
	LDY $16
	INY
	STY $16
	LDA $1E
	INC
	STA $1E
@UNKNOWN4:
	CMP $28
	BCC @UNKNOWN3
@UNKNOWN5:
	LDA $04
	ASL
	CLC
	ADC $1C
	TAX
	LDY $16
	TYA
	JSR UNKNOWN_C4B923
	LDY $16
	STY $0E
	LDA $2E
	STA $10
	LDA $2C
	STA $12
	LDY $02
	LDX $26
	LDA $24
	JSR UNKNOWN_C4BAF6
@UNKNOWN6:
	LDY $2A
	LDX $2E
	LDA $02
	CLC
	ADC #$0006
	JSR UNKNOWN_C4BD9A
	LDX $02
	STA __BSS_START__+14,X
	LDX $2A
	JSR UNKNOWN_C4BF7F
	STA $14
	ASL
	ASL
	JSR UNKNOWN_C4B587
	STA $22
	STZ $1E
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA $1E
	ASL
	ASL
	TAX
	STX $02
	LDA $22
	CLC
	ADC $02
	TAY
	TXA
	CLC
	ADC $2A
	TAX
	MOVE_INT_XPTRSRC_YPTRDEST __BSS_START__, __BSS_START__
	INC $1E
@UNKNOWN8:
	LDA $1E
	CMP $14
	BCC @UNKNOWN7
	LDA $14
	LDX $32
	STX $02
	STA __BSS_START__+10,X
	LDA $22
	LDX $02
	STA __BSS_START__+12,X
	LDA $14
	BEQ @UNKNOWN9
	INC $20
@UNKNOWN9:
	INC $04
@UNKNOWN10:
	LDA $04
	CMP $28
	BCCL @UNKNOWN1
	LDA $20
	PLD
	RTL
