
<<<<<<< HEAD
UNKNOWN_C4B595:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA PATH_HEAP_CURRENT
	SEC
	SBC PATH_HEAP_START
	END_C_FUNCTION
=======
UNKNOWN_C4B595: ;$C4B595
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7EB43A
	SEC
	SBC UNKNOWN_7EB438
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
