
<<<<<<< HEAD
UNKNOWN_C4B587:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX PATH_HEAP_CURRENT
=======
UNKNOWN_C4B587: ;$C4B587
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX UNKNOWN_7EB43A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC PATH_HEAP_CURRENT
	STA PATH_HEAP_CURRENT
	TXA
	RTS
