
UNKNOWN_C4B7A5: ;$C4B7A5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 15
	LDX #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FD
	STA $0E
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA PATH_MATRIX_COLUMNS
	DEC
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA UNKNOWN_7EB402
	DEC
	STA $02
	LDY UNKNOWN_7EB402
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDY PATH_MATRIX_COLUMNS
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDY UNKNOWN_7EB402
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	JSL MULT16
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	INX
@UNKNOWN1:
	CPX PATH_MATRIX_ROWS
	BCC @UNKNOWN0
	LDX #$0000
	BRA @UNKNOWN3
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FD
	STA $0E
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA PATH_MATRIX_ROWS
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	STX $02
	LDY UNKNOWN_7EB402
	LDA UNKNOWN_7EB400
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	DEC
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	INX
@UNKNOWN3:
	CPX PATH_MATRIX_COLUMNS
	BCC @UNKNOWN2
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
