
UNKNOWN_C4B923: ;$C4B923
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 24
	STX $16
	STA $04
	LDA #$0000
	STA $14
	BRA @UNKNOWN2
@UNKNOWN0:
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL03
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQ @UNKNOWN1
	LDA #$00FE
	STA [$06]
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	INC
	STA $14
@UNKNOWN2:
	CMP PATH_MATRIX_SIZE
	BCC @UNKNOWN0
	LDA #$0000
	STA $02
	STA $12
	JMP @UNKNOWN27
@UNKNOWN3:
	LDA $02
	ASL
	TAY
	LDA ($16),Y
	TAY
	STY $10
	LDA __BSS_START__,Y
	BNE @UNKNOWN5
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA a:pathfinder::origin + pathfinder_coords::y_coord,Y
	LDY PATH_MATRIX_COLUMNS
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA __BSS_START__+6,Y
	LDY UNKNOWN_7EB402
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MULT16
	LDY $10
	CLC
	ADC __BSS_START__+8,Y
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQL @UNKNOWN26
	LDA #$00FF
	STA [$06]
	JMP @UNKNOWN26
@UNKNOWN5:
	.A16
	LDA #$0000
	STA $0E
	BRA @UNKNOWN10
@UNKNOWN6:
	LDX #$0000
	BRA @UNKNOWN9
@UNKNOWN7:
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL00
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	STX $02
	LDY UNKNOWN_7EB402
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQ @UNKNOWN8
	LDA #$00FF
	STA [$06]
@UNKNOWN8:
	INX
@UNKNOWN9:
	CPX PATH_MATRIX_COLUMNS
	BCC @UNKNOWN7
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	INC
	STA $0E
@UNKNOWN10:
	CMP PATH_MATRIX_BORDER
	BCC @UNKNOWN6
	LDA PATH_MATRIX_ROWS
	SEC
<<<<<<< HEAD
	SBC PATH_MATRIX_BORDER
	STA @LOCAL00
=======
	SBC UNKNOWN_7EB404
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN15
@UNKNOWN11:
	LDX #$0000
	BRA @UNKNOWN14
@UNKNOWN12:
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL00
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	STX $02
	LDY UNKNOWN_7EB402
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQ @UNKNOWN13
	LDA #$00FF
	STA [$06]
@UNKNOWN13:
	INX
@UNKNOWN14:
	CPX PATH_MATRIX_COLUMNS
	BCC @UNKNOWN12
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	INC
	STA $0E
@UNKNOWN15:
	CMP PATH_MATRIX_ROWS
	BCC @UNKNOWN11
	LDX #$0000
	BRA @UNKNOWN20
@UNKNOWN16:
	LDA #$0000
	STA $14
	BRA @UNKNOWN19
@UNKNOWN17:
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL03
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	STX $02
	LDY UNKNOWN_7EB402
	LDA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQ @UNKNOWN18
	LDA #$00FF
	STA [$06]
@UNKNOWN18:
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	INC
	STA $14
@UNKNOWN19:
	CMP PATH_MATRIX_ROWS
	BCC @UNKNOWN17
	INX
@UNKNOWN20:
	CPX PATH_MATRIX_BORDER
	BCC @UNKNOWN16
	LDA PATH_MATRIX_COLUMNS
	SEC
	SBC PATH_MATRIX_BORDER
	TAX
	BRA @UNKNOWN25
@UNKNOWN21:
	LDA #$0000
	STA $14
	BRA @UNKNOWN24
@UNKNOWN22:
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL03
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	STX $02
	LDY UNKNOWN_7EB402
	LDA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MULT16
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BEQ @UNKNOWN23
	LDA #$00FF
	STA [$06]
@UNKNOWN23:
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	INC
	STA $14
@UNKNOWN24:
	CMP PATH_MATRIX_ROWS
	BCC @UNKNOWN22
	INX
@UNKNOWN25:
	CPX PATH_MATRIX_COLUMNS
	BCC @UNKNOWN21
	LDY $10
	TYX
	STZ __BSS_START__+6,X
	TYX
	STZ __BSS_START__+8,X
@UNKNOWN26:
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	STA $02
	INC $02
	LDA $02
	STA $12
@UNKNOWN27:
	LDA $02
	CMP $04
	BCCL @UNKNOWN3
	PLD
	RTS
