
<<<<<<< HEAD
UNKNOWN_C4BAF6:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0C
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL0B
	LDY @PARAM05
	STY @LOCAL0A
	LDA @PARAM04
	STA @LOCAL09
	LDX @PARAM03
	STX @LOCAL08
	LDY #2
	LDA (@LOCAL0C),Y
	STA @LOCAL07
	LDY #4
	LDA (@LOCAL0C),Y
	STA @LOCAL06
	STZ @LOCAL05
	STZ @LOCAL04
	LDX PATH_SEARCH_TEMP_START
	STX PATH_SEARCH_TEMP_B
	STX PATH_SEARCH_TEMP_A
	LDA #0
	STA @LOCAL03
=======
UNKNOWN_C4BAF6: ;$C4BAF6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 39
	STY $25
	STX $04
	STA $02
	STA $23
	LDY $39
	STY $21
	LDA $37
	STA $1F
	LDX $35
	STX $1D
	LDY #$0002
	LDA ($25),Y
	STA $1B
	LDY #$0004
	LDA ($25),Y
	STA $19
	STZ $17
	STZ $15
	LDX UNKNOWN_7EB408
	STX UNKNOWN_7EB40E
	STX UNKNOWN_7EB40C
	LDA #$0000
	STA $13
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN3
@UNKNOWN0:
	ASL
	ASL
	STA $02
	LDA $04
	CLC
	ADC $02
	TAX
	LDY PATH_MATRIX_COLUMNS
	LDA __BSS_START__,X
	JSL MULT16
	CLC
	ADC __BSS_START__+2,X
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @UNKNOWN1
	LDX PATH_SEARCH_TEMP_START
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX PATH_SEARCH_TEMP_B
	INX
	INX
@UNKNOWN2:
<<<<<<< HEAD
	STX PATH_SEARCH_TEMP_B
	LDA @LOCAL03
=======
	STX UNKNOWN_7EB40E
	LDA $13
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $13
@UNKNOWN3:
	LDX $23
	STX $02
	CMP $02
	BCC @UNKNOWN0
	JMP @UNKNOWN30
@UNKNOWN4:
	LDX PATH_SEARCH_TEMP_A
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA @VIRTUAL04
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_END
=======
	STA $04
	LDA UNKNOWN_7EB40C
	CMP UNKNOWN_7EB40A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN5
	LDX PATH_SEARCH_TEMP_START
	BRA @UNKNOWN6
@UNKNOWN5:
	LDX PATH_SEARCH_TEMP_A
	INX
	INX
@UNKNOWN6:
<<<<<<< HEAD
	STX PATH_SEARCH_TEMP_A
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
=======
	STX UNKNOWN_7EB40C
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $00
	CMP #$00FE
	BCCL @UNKNOWN30
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA $02
	STA $11
	LDY $04
	LDX #$0000
	BRA @UNKNOWN12
@UNKNOWN8:
	LDA #$0000
	STA $0F
	BRA @UNKNOWN11
@UNKNOWN9:
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL01
	STA @VIRTUAL02
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $0F
	STA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	CLC
	ADC $02
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BNE @UNKNOWN10
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA $02
	STA $11
	BRA @UNKNOWN13
@UNKNOWN10:
	REP #PROC_FLAGS::ACCUM8
	LDA $0F
	INC
	STA $0F
@UNKNOWN11:
	CMP $19
	BCC @UNKNOWN9
	TYA
	CLC
	ADC PATH_MATRIX_COLUMNS
	TAY
	INX
@UNKNOWN12:
	CPX $1B
	BCC @UNKNOWN8
@UNKNOWN13:
	LDA $11
	STA $02
	BNE @UNKNOWN14
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FC
	STA [$06]
	JMP @UNKNOWN30
@UNKNOWN14:
	SEP #PROC_FLAGS::ACCUM8
	LDA $00
	CMP #$00FF
	BNE @UNKNOWN15
	REP #PROC_FLAGS::ACCUM8
	INC $17
	LDA ($25)
	CMP #$0001
	BNE @UNKNOWN15
<<<<<<< HEAD
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #6
	STA (@LOCAL0C),Y
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL04
=======
	LDY UNKNOWN_7EB402
	LDA $04
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #$0006
	STA ($25),Y
	LDY UNKNOWN_7EB402
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MODULUS16
	LDY #$0008
	STA ($25),Y
@UNKNOWN15:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FC
	STA $00
	LDX #$0000
	STX $13
	BRA @UNKNOWN23
@UNKNOWN16:
	REP #PROC_FLAGS::ACCUM8
	TXA
	ASL
	TAX
	LDA $04
	CLC
<<<<<<< HEAD
	ADC PATH_CARDINAL_OFFSET,X
	STA @LOCAL01
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL01
=======
	ADC UNKNOWN_7EB410,X
	STA $0F
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $0F
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $01
	CMP #$00FE
	BCC @UNKNOWN21
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_START
	BNE @UNKNOWN17
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BEQ @UNKNOWN22
	BRA @UNKNOWN18
@UNKNOWN17:
	LDA PATH_SEARCH_TEMP_B
	INC
	INC
	CMP PATH_SEARCH_TEMP_A
	BEQ @UNKNOWN22
@UNKNOWN18:
<<<<<<< HEAD
	LDA @LOCAL01
	LDX PATH_SEARCH_TEMP_B
=======
	LDA $0F
	LDX UNKNOWN_7EB40E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @UNKNOWN19
	LDY PATH_SEARCH_TEMP_START
	BRA @UNKNOWN20
@UNKNOWN19:
	LDY PATH_SEARCH_TEMP_B
	INY
	INY
@UNKNOWN20:
	STY PATH_SEARCH_TEMP_B
	BRA @UNKNOWN22
@UNKNOWN21:
	LDA $00
	CMP $01
	BLTEQ @UNKNOWN22
	LDA $01
	STA $00
@UNKNOWN22:
	LDX $13
	INX
	STX $13
@UNKNOWN23:
	CPX #$0004
	BCCL @UNKNOWN16
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	CMP #$00FC
	BNE @UNKNOWN25
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA [$06]
	BRA @UNKNOWN29
@UNKNOWN25:
	SEP #PROC_FLAGS::ACCUM8
	LDA $00
	INC
	STA $0E
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP $1F
	BNE @UNKNOWN29
	LDA #$0000
	STA $0F
	BRA @UNKNOWN28
@UNKNOWN26:
	ASL
	TAX
	LDA $04
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	TAX
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FE
	BCC @UNKNOWN27
	LDA #$00FC
	STA [$06]
@UNKNOWN27:
	REP #PROC_FLAGS::ACCUM8
	LDA $0F
	INC
	STA $0F
@UNKNOWN28:
	CMP #$0004
	BCC @UNKNOWN26
@UNKNOWN29:
	REP #PROC_FLAGS::ACCUM8
	INC $15
	LDA $21
	CMP $15
	BLTEQ @UNKNOWN31
	LDA $17
	CMP $1D
	BEQ @UNKNOWN31
@UNKNOWN30:
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_B
	BNEL @UNKNOWN4
@UNKNOWN31:
	PLD
	RTS
