
<<<<<<< HEAD
UNKNOWN_C4BAF6:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0B
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL0A
	LDY @PARAM05
	STY @LOCAL09
	LDA @PARAM04
	STA @LOCAL08
	LDX @PARAM03
	STX @LOCAL07
	LDY #2
	LDA (@LOCAL0B),Y
	STA @LOCAL06
	LDY #4
	LDA (@LOCAL0B),Y
	STA @LOCAL05
	STZ @LOCAL04
	STZ @LOCAL03
	LDX PATH_SEARCH_TEMP_START
	STX PATH_SEARCH_TEMP_B
	STX PATH_SEARCH_TEMP_A
	LDA #0
	STA @LOCAL02
=======
UNKNOWN_C4BAF6: ;$C4BAF6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 37
	STY $23
	STX $04
	STA $02
	STA $21
	LDY $37
	STY $1F
	LDA $35
	STA $1D
	LDX $33
	STX $1B
	LDY #$0002
	LDA ($23),Y
	STA $19
	LDY #$0004
	LDA ($23),Y
	STA $17
	STZ $15
	STZ $13
	LDX UNKNOWN_7EB408
	STX UNKNOWN_7EB40E
	STX UNKNOWN_7EB40C
	LDA #$0000
	STA $11
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN3
@UNKNOWN0:
	ASL
	ASL
	STA $02
	LDA $04
	CLC
	ADC $02
	TAX
	LDY PATH_MATRIX_COLUMNS
	LDA __BSS_START__,X
	JSL MULT16
	CLC
	ADC __BSS_START__+2,X
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @UNKNOWN1
	LDX PATH_SEARCH_TEMP_START
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX PATH_SEARCH_TEMP_B
	INX
	INX
@UNKNOWN2:
<<<<<<< HEAD
	STX PATH_SEARCH_TEMP_B
	LDA @LOCAL02
=======
	STX UNKNOWN_7EB40E
	LDA $11
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $11
@UNKNOWN3:
	LDX $21
	STX $02
	CMP $02
	BCC @UNKNOWN0
	JMP @UNKNOWN30
@UNKNOWN4:
	LDX PATH_SEARCH_TEMP_A
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_END
=======
	STA $02
	LDA UNKNOWN_7EB40C
	CMP UNKNOWN_7EB40A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN5
	LDX PATH_SEARCH_TEMP_START
	BRA @UNKNOWN6
@UNKNOWN5:
	LDX PATH_SEARCH_TEMP_A
	INX
	INX
@UNKNOWN6:
<<<<<<< HEAD
	STX PATH_SEARCH_TEMP_A
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
=======
	STX UNKNOWN_7EB40C
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $00
	CMP #$00FE
	BCCL @UNKNOWN30
	LDY #$0001
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA $11
	BRA @UNKNOWN12
@UNKNOWN8:
	LDA #$0000
	STA $04
	BRA @UNKNOWN11
@UNKNOWN9:
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	CLC
	ADC $04
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FD
	BNE @UNKNOWN10
	LDY #$0000
	BRA @UNKNOWN13
@UNKNOWN10:
	REP #PROC_FLAGS::ACCUM8
	INC $04
@UNKNOWN11:
	LDA $04
	CMP $17
	BCC @UNKNOWN9
	TXA
	CLC
	ADC PATH_MATRIX_COLUMNS
	TAX
	LDA $11
	INC
	STA $11
@UNKNOWN12:
	CMP $19
	BCC @UNKNOWN8
@UNKNOWN13:
	CPY #$0000
	BNE @UNKNOWN14
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FC
	STA [$06]
	JMP @UNKNOWN30
@UNKNOWN14:
	SEP #PROC_FLAGS::ACCUM8
	LDA $00
	CMP #$00FF
	BNE @UNKNOWN15
	REP #PROC_FLAGS::ACCUM8
	INC $15
	LDA ($23)
	CMP #$0001
	BNE @UNKNOWN15
<<<<<<< HEAD
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL02
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #6
	STA (@LOCAL0B),Y
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL02
=======
	LDY UNKNOWN_7EB402
	LDA $02
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #$0006
	STA ($23),Y
	LDY UNKNOWN_7EB402
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MODULUS16
	LDY #$0008
	STA ($23),Y
@UNKNOWN15:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FC
	STA $00
	LDX #$0000
	STX $0F
	JMP @UNKNOWN23
@UNKNOWN16:
	REP #PROC_FLAGS::ACCUM8
	TXA
	ASL
	TAX
	LDA $02
	CLC
<<<<<<< HEAD
	ADC PATH_CARDINAL_OFFSET,X
	STA @LOCAL02
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL02
=======
	ADC UNKNOWN_7EB410,X
	STA $11
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $11
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $01
	CMP #$00FE
	BCC @UNKNOWN21
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_START
	BNE @UNKNOWN17
<<<<<<< HEAD
	LDY #0
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
=======
	LDY #$0000
	LDA UNKNOWN_7EB40E
	CMP UNKNOWN_7EB40A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN18
	LDY #$0001
	BRA @UNKNOWN18
@UNKNOWN17:
<<<<<<< HEAD
	LDY #0
	LDA PATH_SEARCH_TEMP_B
=======
	LDY #$0000
	LDA UNKNOWN_7EB40E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	INC
	CMP PATH_SEARCH_TEMP_A
	BNE @UNKNOWN18
	LDY #$0001
@UNKNOWN18:
	CPY #$0000
	BNE @UNKNOWN22
<<<<<<< HEAD
	LDA @LOCAL02
	LDX PATH_SEARCH_TEMP_B
=======
	LDA $11
	LDX UNKNOWN_7EB40E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @UNKNOWN19
	LDY PATH_SEARCH_TEMP_START
	BRA @UNKNOWN20
@UNKNOWN19:
	LDY PATH_SEARCH_TEMP_B
	INY
	INY
@UNKNOWN20:
	STY PATH_SEARCH_TEMP_B
	BRA @UNKNOWN22
@UNKNOWN21:
	LDA $00
	CMP $01
	BLTEQ @UNKNOWN22
	LDA $01
	STA $00
@UNKNOWN22:
	LDX $0F
	INX
	STX $0F
@UNKNOWN23:
	CPX #$0004
	BCCL @UNKNOWN16
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	CMP #$00FC
	BNE @UNKNOWN25
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA [$06]
	BRA @UNKNOWN29
@UNKNOWN25:
	SEP #PROC_FLAGS::ACCUM8
	LDA $00
	INC
	STA $0E
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA [$06]
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP $1D
	BNE @UNKNOWN29
	LDA #$0000
	STA $11
	BRA @UNKNOWN28
@UNKNOWN26:
	ASL
	TAX
	LDA $02
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	TAX
<<<<<<< HEAD
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
=======
	MOVE_INT UNKNOWN_7EB3FC, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	CMP #$00FE
	BCC @UNKNOWN27
	LDA #$00FC
	STA [$06]
@UNKNOWN27:
	REP #PROC_FLAGS::ACCUM8
	LDA $11
	INC
	STA $11
@UNKNOWN28:
	CMP #$0004
	BCC @UNKNOWN26
@UNKNOWN29:
	REP #PROC_FLAGS::ACCUM8
	INC $13
	LDA $1F
	CMP $13
	BLTEQ @UNKNOWN31
	LDA $15
	CMP $1B
	BEQ @UNKNOWN31
@UNKNOWN30:
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_B
	BNEL @UNKNOWN4
@UNKNOWN31:
	PLD
	RTS
