
<<<<<<< HEAD
UNKNOWN_C4C8A4:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	STZ ENTITY_FADE_STATES_BUFFER
	STZ ENTITY_FADE_STATES_LENGTH
	LOADPTR BUFFER + $7C00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, ENTITY_FADE_STATES
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #1024
=======
UNKNOWN_C4C8A4: ;$C4C8A4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	STZ UNKNOWN_7EB4A4
	STZ UNKNOWN_7EB4A6
	LOADPTR UNKNOWN_7F7C00, $06
	MOVE_INT $06, UNKNOWN_7EB4AA
	MOVE_INT $06, $0E
	LDX #$0400
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL MEMSET24
	PLD
	RTS
