
<<<<<<< HEAD
UNKNOWN_C4C8DB:
	BEGIN_C_FUNCTION
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX ENTITY_FADE_STATES_BUFFER
=======
UNKNOWN_C4C8DB: ;$C4C8DB
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX UNKNOWN_7EB4A4
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC ENTITY_FADE_STATES_BUFFER
	STA ENTITY_FADE_STATES_BUFFER
	TXA
	RTS
