
UNKNOWN_C4CB4F: ;$C4CB4F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
<<<<<<< HEAD
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL06
	LDY #0
=======
	MOVE_INT UNKNOWN_7EB4AA, @VIRTUAL06
	LDY #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$BFFF
	STA __BSS_START__,X
	LDA #$0014
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	INY
@UNKNOWN1:
	CPY ENTITY_FADE_STATES_LENGTH
	BCC @UNKNOWN0
	PLD
	RTL
