
UNKNOWN_C4CEB0: ;$C4CEB0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
<<<<<<< HEAD
	LOADPTR BUFFER + $7F00, @VIRTUAL06
	LDX #0
=======
	LOADPTR UNKNOWN_7F7F00, @VIRTUAL06
	LDX #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #$0000
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	INX
@UNKNOWN1:
	CPX #$0040
	BCC @UNKNOWN0
	PLD
	RTL
