
UNKNOWN_C4DCF6: ;$C4DCF6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
<<<<<<< HEAD
	LOADPTR BUFFER, @VIRTUAL0A
	LDX #0
=======
	LOADPTR UNKNOWN_7F0000, @VIRTUAL0A
	LDX #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	ORA #$2000
	STA [@VIRTUAL06]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INX
@UNKNOWN1:
	CPX #$0400
	BCC @UNKNOWN0
	PLD
	RTS
