
<<<<<<< HEAD
UNKNOWN_C4E51E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LOADPTR BUFFER + $7F00+$FE, @VIRTUAL06
=======
UNKNOWN_C4E51E: ;$C4E51E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LOADPTR UNKNOWN_7F7F00+$FE, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDY ENTITY_ABS_Y_TABLE,X
	STY BG3_Y_POS
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	STY $02
	CMP $02
	BCS @UNKNOWN0
	CLC
	ADC #$0008
	STA __BSS_START__,X
	LDA BG3_Y_POS
	LSR
	LSR
	LSR
	DEC
	AND #$001F
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$7C00
	STA $12
	LDA #$0000
	STA [$06]
	MOVE_INT $06, $0E
	LDA $12
	TAY
	LDX #$0040
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	JSL PREPARE_VRAM_COPY
@UNKNOWN0:
	PLD
	RTL
