<<<<<<< HEAD

UNKNOWN_C4ECAD:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "SPRITE_ID"
	STACK_RESERVE_PARAM_INT16 "ACTIONSCRIPT"
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	STA @LOCAL02
	LDA INITIAL_CAST_ENTITY_SLEEP_FRAMES
=======
; A = sprite ID, X = movement ID
UNKNOWN_C4ECAD: ;$C4ECAD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STX $02
	STA $12
	LDA UNKNOWN_7EB4D3
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$0003
	STA NEW_ENTITY_VAR0
	INC INITIAL_CAST_ENTITY_SLEEP_FRAMES
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA $0E
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	CLC
	ADC BG3_Y_POS
	STA $10
	LDY #$FFFF
	LDX $02
	LDA $12
	JSL CREATE_ENTITY
	PLD
	RTL
