
UNKNOWN_C4EC6E: ;$C4EC6E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	ASL
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 $06
	CLC
<<<<<<< HEAD
	VAR_ADD_CONST_INT_ASSIGN BUFFER + $7000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 1
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 12
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::OBJ_ONLY
	STA PALETTE_UPLOAD_MODE
=======
	VAR_ADD_CONST_INT_ASSIGN $7F7000, $06
	MOVE_INT $06, $0E
	LDX #$0020
	LDA #$0380
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0010
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
