
UNKNOWN_C4EFC4: ;$C4EFC4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 15
	STY $02
	TXY
	SEP #PROC_FLAGS::ACCUM8
	STA $0E
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT @PARAM03, @VIRTUAL06
	LDA CREDITS_DMA_QUEUE_START
	OPTIMIZED_MULT @VIRTUAL04, 9
=======
	MOVE_INT $1D, $06
	LDA UNKNOWN_7EB4F5
	OPTIMIZED_MULT $04, 9
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	STA __BSS_START__+1,X
	TXY
	INY
	INY
	INY
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA $02
	STA __BSS_START__+7,X
	LDA CREDITS_DMA_QUEUE_START
	INC
	STA CREDITS_DMA_QUEUE_START
	AND #$007F
<<<<<<< HEAD
	STA CREDITS_DMA_QUEUE_START
	END_C_FUNCTION
=======
	STA UNKNOWN_7EB4F5
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
