
<<<<<<< HEAD
UNKNOWN_C4F01D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CREDITS_DMA_QUEUE_START
	CMP CREDITS_DMA_QUEUE_END
	BEQ @RETURN
	LDA CREDITS_DMA_QUEUE_END
	OPTIMIZED_MULT @VIRTUAL04, 9
=======
UNKNOWN_C4F01D: ;$C4F01D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA UNKNOWN_7EB4F5
	CMP UNKNOWN_7EB4F3
	BEQ @RETURN
	LDA UNKNOWN_7EB4F3
	OPTIMIZED_MULT $04, 9
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA $14
	TAY
	INY
	INY
	INY
	MOVE_INT_YPTRSRC __BSS_START__, $06
	MOVE_INT $06, $0E
	LDA $14
	TAX
	LDY __BSS_START__+7,X
	TAX
	LDA __BSS_START__+1,X
	TAX
	STX $12
	LDA $14
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	LDX $12
	JSL PREPARE_VRAM_COPY
	.A16
	LDA CREDITS_DMA_QUEUE_END
	INC
	STA CREDITS_DMA_QUEUE_END
	AND #$007F
	STA CREDITS_DMA_QUEUE_END
@RETURN:
	PLD
	RTL
