
UNKNOWN_C4F264: ;$C4F264
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 32
	STA $1E
	LDX #$0000
	STX $1C
	LOADPTR PHOTOGRAPHER_CFG_TABLE, $0A
	LDA $1E
	LDY #.SIZEOF(photographer_config_entry)
	JSL MULT168
	CLC
	ADC $0A
	STA $0A
	STA $06
	LDA $0C
	STA $08
	LDA [$06]
	JSL GET_EVENT_FLAG
	CMP #$0000
	BEQL @RETURN
<<<<<<< HEAD
	LDA #1
	STA PHOTOGRAPH_MAP_LOADING_MODE
	LDA @LOCAL06
	STA CUR_PHOTO_DISPLAY
	LDA ENEMY_SPAWNS_ENABLED
	STA @VIRTUAL02
	STZ ENEMY_SPAWNS_ENABLED
	LDY #0
=======
	LDA #$0001
	STA UNKNOWN_7EB4EF
	LDA $1E
	STA CUR_PHOTO_DISPLAY
	LDA UNKNOWN_7E4A5A
	STA $02
	STZ UNKNOWN_7E4A5A
	LDY #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDX #$2000
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA #$0000
	STA __BSS_START__,X
	INX
	INX
	INY
@UNKNOWN2:
	CPY #$0400
	BCC @UNKNOWN1
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LOADPTR UNKNOWN_E1E924+6, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 1
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 1
=======
	LOADPTR UNKNOWN_E1E924+6, $0E
	LDX #$0020
	LDA #$0220
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	LDY #$0004
	LDA [$0A],Y
	ASL
	ASL
	ASL
	TAX
	LDY #$0002
	LDA [$0A],Y
	ASL
	ASL
	ASL
	JSL LOAD_MAP_AT_POSITION
<<<<<<< HEAD
	LDA @VIRTUAL02
	STA ENEMY_SPAWNS_ENABLED
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ PHOTOGRAPH_MAP_LOADING_MODE
	STZ @LOCAL04
	LDA #0
	STA @VIRTUAL02
=======
	LDA $02
	STA UNKNOWN_7E4A5A
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ UNKNOWN_7EB4EF
	STZ $1A
	LDA #$0000
	STA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN5
@UNKNOWN3:
	LDA $02
	OPTIMIZED_MULT $04, 6
	STA $18
	CLC
	ADC #$002A
	MOVE_INTX $0A, $06
	CLC
	ADC $06
	STA $06
	STA $14
	LDA $08
	STA $16
	LDA [$06]
	BEQ @UNKNOWN4
	LDA $1A
	STA NEW_ENTITY_VAR0
	INC $1A
	LDA $18
	CLC
	ADC #photographer_config_entry::object_config + photographer_config_entry_object::tile_x
	MOVE_INTX $0A, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	ASL
	ASL
	ASL
	STA $0E
	LDA $18
	CLC
	ADC #photographer_config_entry::object_config + photographer_config_entry_object::tile_y
	MOVE_INTX $0A, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	ASL
	ASL
	ASL
	STA $10
	LDY #$FFFF
	LDX #EVENT_SCRIPT::EVENT_799
	MOVE_INT $14, $06
	LDA [$06]
	JSL CREATE_ENTITY
@UNKNOWN4:
	INC $02
@UNKNOWN5:
	LDA $02
	CMP #$0004
	BCCL @UNKNOWN3
	LDA #$0000
	STA $04
	JMP @UNKNOWN9
@UNKNOWN7:
	LDA $1E
	ASL
	ASL
	ASL
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC $04
	TAX
	LDA a:game_state::saved_photo_states + photo_state::party,X
.ELSE
	ADC $04
	TAX
	LDA GAME_STATE + game_state::saved_photo_states + photo_state::party,X
.ENDIF
	AND #$00FF
	STA $02
	BEQ @UNKNOWN8
	LDA $02
	AND #$001F
	CMP #$0012
	BCS @UNKNOWN8
	CMP #$0000
	BEQ @UNKNOWN8
	LDA $1A
	STA NEW_ENTITY_VAR0
	INC $1A
	LDA $04
	ASL
	ASL
	TAX
	STX $1C
	LDA $02
	JSL UNKNOWN_C079EC
	STA $12
	LDX $1C
	TXA
	CLC
	ADC #$000E
	MOVE_INTY $0A, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	ASL
	ASL
	ASL
	STA $0E
	TXA
	CLC
	ADC #$0010
	MOVE_INTX $0A, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	ASL
	ASL
	ASL
	STA $10
	LDY #$FFFF
	LDX #EVENT_SCRIPT::EVENT_800
	LDA $12
	JSL CREATE_ENTITY
	TAY
	LDX $02
	TYA
	JSL UNKNOWN_C07A31
@UNKNOWN8:
	INC $04
@UNKNOWN9:
	LDA $04
	CMP #$0006
	BCCL @UNKNOWN7
	LDX #$0001
	STX $1C
@RETURN:
	LDX $1C
	TXA
	PLD
	RTL
