
<<<<<<< HEAD
UNKNOWN_C4FB42:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDA #.LOWORD(-1)
	STA SEQUENCE_PACK_MASK
	LDA @LOCAL00
=======
UNKNOWN_C4FB42: ;$C4FB42
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	LDA #$FFFF
	STA UNKNOWN_7EB547
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
.IF .DEFINED(JPN)
	CLC
	ADC #$00E2
.ENDIF
	PLD
	RTS
