
CLEAR_INSTANT_PRINTING: ;$C3E4CA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	SEP #PROC_FLAGS::ACCUM8
	STZ INSTANT_PRINTING
	REP #PROC_FLAGS::ACCUM8
.IFDEF JPN
	RTS
.ELSE
	RTL
.ENDIF
