
FIX_ATTACKER_NAME: ;$C23BCF
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 24
	TAY
	STY $16
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
.IF .DEFINED(USA)
	STZ PRINT_ATTACKER_ARTICLE
.ENDIF
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(enemy_data::name) + .SIZEOF(char_struct::name) - 2
=======
	STZ UNKNOWN_7E5E77
	STZ $0E
	LDX #$001C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(ATTACKER_NAME_ADJUST_SCRATCH)
	JSL MEMSET16
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN0
	LDX CURRENT_ATTACKER
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQL @UNKNOWN4
@UNKNOWN0:
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	INC
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #$0019
	LDA #.LOWORD(ATTACKER_NAME_ADJUST_SCRATCH)
	JSR COPY_ENEMY_NAME
	TAX
	STX $14
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN2
	LDY $16
	BNE @UNKNOWN2
	LDX CURRENT_ATTACKER
	LDA a:battler::the_flag,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN1
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+76,X
	JSL UNKNOWN_C2B66A
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #$0002
	BEQ @UNKNOWN2
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0050
	LDX $14
	STA __BSS_START__,X
	INX
<<<<<<< HEAD
	LDA #118
	STA __BSS_START__,X
.ELSE
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	LDX @LOCAL02
	STA __BSS_START__,X
	INX
	STX @LOCAL03
	LDA #1
	STA PRINT_ATTACKER_ARTICLE
=======
	STX $16
	LDA #$0001
	STA UNKNOWN_7E5E77
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDX CURRENT_ATTACKER
	LDA a:battler::the_flag,X
	CLC
	ADC #$0070
	LDX $16
	STA __BSS_START__,X
@UNKNOWN2:
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CMP #$00A0
	BNE @UNKNOWN3
	PROMOTENEARPTR GAME_STATE + game_state::pet_name, $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$0006
	LDA #.LOWORD(ATTACKER_NAME_ADJUST_SCRATCH)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ ATTACKER_NAME_ADJUST_SCRATCH+6
@UNKNOWN3:
	LDX #$001B
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(ATTACKER_NAME_ADJUST_SCRATCH)
	JSL REDIRECT_C1AC4A
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA ATTACKER_ENEMY_ID
.ENDIF
=======
	STA UNKNOWN_7E9658
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN6
@UNKNOWN4:
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	CMP #$0004
	BGT @UNKNOWN6
	LDX #.SIZEOF(char_struct::name)
	STX $12
	LDX CURRENT_ATTACKER
	LDA a:battler::row,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PARTY_CHARACTERS)
	LDX @LOCAL01
=======
	ADC #.LOWORD(CHAR_STRUCT)
	LDX $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL REDIRECT_C1AC4A
@UNKNOWN6:
	PLD
	RTL
