
PRINT_STRING: ;$C10EFC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
<<<<<<< HEAD
	STX @LOCAL01
	MOVE_INT @PARAM00, @VIRTUAL06
	LDA FORCE_CENTRE_TEXT_ALIGNMENT
=======
	STX $12
	MOVE_INT $22, $06
	LDA UNKNOWN_7E5E74
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BEQ @UNKNOWN1
	MOVE_INT $06, $0E
	TXA
	JSL UNKNOWN_C43EF8
	BRA @UNKNOWN1
@UNKNOWN0:
	DEX
	STX $12
	AND #$00FF
	INC $06
	JSR PRINT_LETTER
@UNKNOWN1:
	LDA [$06]
	AND #$00FF
	BEQ @UNKNOWN2
	LDX $12
	BNE @UNKNOWN0
@UNKNOWN2:
	PLD
	RTS
