
SHOW_HPPP_WINDOWS: ;$C10A04
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSR UNKNOWN_C3E6F8
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA RENDER_HPPP_WINDOWS
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(-1)
	STA CURRENTLY_DRAWN_HPPP_WINDOWS
	END_C_FUNCTION
=======
	LDA #$0001
	STA UNKNOWN_7E89C9
	STA UNKNOWN_7E9623
	REP #PROC_FLAGS::ACCUM8
	LDA #$FFFF
	STA UNKNOWN_7E9647
	RTS
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
