
<<<<<<< HEAD
UNKNOWN_C3E450:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA FRAME_COUNTER
=======
UNKNOWN_C3E450: ;$C3E450
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA UNKNOWN_7E0002
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	AND #$0004
	BEQ @UNKNOWN0
	LOADPTR TEXT_WINDOW_FLAVOUR_PALETTES, $06
	LDA GAME_STATE+game_state::text_flavour
	AND #$00FF
	DEC
	OPTIMIZED_MULT $04, 3
	TAX
	LDA f:TEXT_WINDOW_PROPERTIES,X
	CLC
	ADC #$0008
	CLC
	ADC $06
	STA $06
	BRA @UNKNOWN1
@UNKNOWN0:
	LOADPTR TEXT_WINDOW_FLAVOUR_PALETTES, $06
	LDA GAME_STATE+game_state::text_flavour
	AND #$00FF
	DEC
	OPTIMIZED_MULT $04, 3
	TAX
	LDA f:TEXT_WINDOW_PROPERTIES,X
	CLC
	ADC #$0028
	CLC
	ADC $06
	STA $06
@UNKNOWN1:
<<<<<<< HEAD
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP2PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP2PALETTE_SIZE * 5
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	MOVE_INT $06, $0E
	LDX #$0008
	LDA #$0228
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
