
UNKNOWN_C3E75D: ;$C3E75D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	BNE @UNKNOWN1
<<<<<<< HEAD
	LDA ATTACKER_ENEMY_ID
	CMP #.LOWORD(-1)
=======
	LDA UNKNOWN_7E9658
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STZ PRINT_ATTACKER_ARTICLE
	BRA @RETURN
@UNKNOWN0:
	.A16
	LDA PRINT_ATTACKER_ARTICLE
	AND #$00FF
	BNE @RETURN
	LDA ATTACKER_ENEMY_ID
	BRA @UNKNOWN3
@UNKNOWN1:
	.A16
<<<<<<< HEAD
	LDA TARGET_ENEMY_ID
	CMP #.LOWORD(-1)
=======
	LDA UNKNOWN_7E965A
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN2
	SEP #PROC_FLAGS::ACCUM8
	STZ PRINT_TARGET_ARTICLE
	BRA @RETURN
@UNKNOWN2:
	.A16
	LDA PRINT_TARGET_ARTICLE
	AND #$00FF
	BNE @RETURN
	LDA TARGET_ENEMY_ID
@UNKNOWN3:
	LDY #$005E
	JSL MULT168
	.A16
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BEQ @RETURN
	LDA LAST_PRINTED_CHARACTER
	AND #$00FF
	CMP #$0070
	BNE @LOWERCASE_THE
	LOADPTR THETHE, $0E
	LDA #$0004
	JSL UNKNOWN_C447FB
	BRA @RETURN
@LOWERCASE_THE:
	LOADPTR THETHE+4, $0E
	LDA #$0004
	JSL UNKNOWN_C447FB
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
