
UNKNOWN_C3EE4D: ;$C3EE4D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL UPDATE_PARTY
	JSL UNKNOWN_C07B52
	JSL UNKNOWN_C1004E
	JSL UNKNOWN_C0943C
<<<<<<< HEAD
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
=======
	LDA UNKNOWN_7EB4A8
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN0
	LDA ENTITY_FADE_ENTITY
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
@UNKNOWN0:
	RTL
