
UNKNOWN_C3F1EC: ;$C3F1EC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	LDA #$0003
	JSL UNKNOWN_C2239D
	CMP #$0000
	BNE @UNKNOWN0
	LDA #$0000
	JMP @UNKNOWN6
@UNKNOWN0:
	LDA #$0000
	STA $02
	JMP @UNKNOWN4
@UNKNOWN1:
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	TAX
	STX $10
	TXA
	CLC
	ADC #item::type
	MOVE_INTY $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	CMP #$0008
	BNE @UNKNOWN3
	TXA
	CLC
	ADC #$0020
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA [@VIRTUAL0A]
	CMP PARTY_CHARACTERS+(.SIZEOF(char_struct) * ITEM_FIXING_CHARACTER) + char_struct::iq
=======
	LDA [$0A]
	CMP CHAR_STRUCT+(.SIZEOF(char_struct) * ITEM_FIXING_CHARACTER) + char_struct::iq
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BGT @UNKNOWN3
	REP #PROC_FLAGS::ACCUM8
	LDA #$0063
	JSL RAND_MOD
	CMP $12
	BCS @UNKNOWN3
	LDX $10
	TXA
	CLC
	ADC #$0021
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	LDX $04
	STA __BSS_START__,X
	LDY $0E
	REP #PROC_FLAGS::ACCUM8
	TYA
	BRA @UNKNOWN6
@UNKNOWN3:
	REP #PROC_FLAGS::ACCUM8
	INC $02
@UNKNOWN4:
	LDA $02
	CMP #$000E
	BCS @UNKNOWN5
	LDA $02
	CLC
<<<<<<< HEAD
.IF .DEFINED(JPN)
	ADC #.LOWORD(PARTY_CHARACTERS)
	CLC
	ADC #(.SIZEOF(char_struct) * ITEM_FIXING_CHARACTER) + char_struct::items
.ELSE
	ADC #.LOWORD(PARTY_CHARACTERS)+(.SIZEOF(char_struct) * ITEM_FIXING_CHARACTER) + char_struct::items
.ENDIF
	STA @VIRTUAL04
.IF .DEFINED(JPN)
	STA @LOCAL00
.ENDIF
	LDX @VIRTUAL04
=======
	ADC #.LOWORD(CHAR_STRUCT)+(.SIZEOF(char_struct) * ITEM_FIXING_CHARACTER) + char_struct::items
	STA $04
	LDX $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	AND #$00FF
	TAY
	STY $0E
	BNEL @UNKNOWN1
@UNKNOWN5:
	LDA #$0000
@UNKNOWN6:
	PLD
	RTL
