
<<<<<<< HEAD
UNKNOWN_C3F5F9:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL04
	LDA TILEMAP_UPDATE_TILE_COUNT
=======
UNKNOWN_C3F5F9: ;$C3F5F9
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA #$0000
	STA $04
	LDA UNKNOWN_7E9F7E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $16
	LDA #$0000
	STA $02
	STA $14
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA TILEMAP_UPDATE_TILE_X
	AND #$001F
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA TILEMAP_UPDATE_TILE_Y
=======
	STA $02
	LDA UNKNOWN_7E9F7C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC TILEMAP_UPDATE_BASE_ADDRESS
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL02
	STA @LOCAL01
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	LDA @VIRTUAL04
=======
	ADC $02
	STA $12
	MOVE_INT UNKNOWN_7E9F86, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA $12
	TAY
	LDX $16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL PREPARE_VRAM_COPY
	LDA $04
	CLC
<<<<<<< HEAD
	ADC TILEMAP_UPDATE_TILE_WIDTH
	STA @VIRTUAL04
	LDX TILEMAP_UPDATE_TILE_Y
	INX
	STX TILEMAP_UPDATE_TILE_Y
	CPX #32
=======
	ADC UNKNOWN_7E9F82
	STA $04
	LDX UNKNOWN_7E9F7C
	INX
	STX UNKNOWN_7E9F7C
	CPX #$0020
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN1
	STZ TILEMAP_UPDATE_TILE_Y
@UNKNOWN1:
	LDA $14
	STA $02
	INC $02
	LDA $02
	STA $14
@UNKNOWN2:
<<<<<<< HEAD
	LDA @VIRTUAL02
	CMP TILEMAP_UPDATE_TILE_HEIGHT
=======
	LDA $02
	CMP UNKNOWN_7E9F80
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BCC @UNKNOWN0
	PLD
	RTS
