
<<<<<<< HEAD
UNKNOWN_C3F67D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA TILEMAP_UPDATE_TILE_HEIGHT
=======
UNKNOWN_C3F67D: ;$C3F67D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA UNKNOWN_7E9F80
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $04
	LDA #$0000
	STA $02
	BRA @UNKNOWN3
@UNKNOWN0:
<<<<<<< HEAD
	LDA TILEMAP_UPDATE_TILE_Y
	OPTIMIZED_MULT @VIRTUAL04, 32
=======
	LDA UNKNOWN_7E9F7C
	ASL
	ASL
	ASL
	ASL
	ASL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC TILEMAP_UPDATE_BASE_ADDRESS
	CLC
<<<<<<< HEAD
	ADC TILEMAP_UPDATE_TILE_X
	STA @LOCAL01
	INC TILEMAP_UPDATE_TILE_X
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
=======
	ADC UNKNOWN_7E9F7A
	STA $12
	INC UNKNOWN_7E9F7A
	MOVE_INT UNKNOWN_7E9F86, $06
	MOVE_INT $06, $0E
	LDA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAY
	LDX $04
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL PREPARE_VRAM_COPY
	.A16
<<<<<<< HEAD
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	LDA TILEMAP_UPDATE_TILE_WIDTH
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA TILEMAP_UPDATE_REMAINING_TILES
	LDA @VIRTUAL06+2
	STA TILEMAP_UPDATE_REMAINING_TILES+2
	LDA TILEMAP_UPDATE_TILE_X
	CMP #32
	BEQ @UNKNOWN1
	LDA TILEMAP_UPDATE_TILE_X
	CMP #64
=======
	MOVE_INT UNKNOWN_7E9F86, $06
	LDA UNKNOWN_7E9F82
	ASL
	CLC
	ADC $06
	STA $06
	STA UNKNOWN_7E9F86
	LDA $08
	STA UNKNOWN_7E9F88
	LDA UNKNOWN_7E9F7A
	CMP #$0020
	BEQ @UNKNOWN1
	LDA UNKNOWN_7E9F7A
	CMP #$0040
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN2
@UNKNOWN1:
	LDA TILEMAP_UPDATE_BASE_ADDRESS
	EOR #$0400
	STA TILEMAP_UPDATE_BASE_ADDRESS
@UNKNOWN2:
	INC $02
@UNKNOWN3:
<<<<<<< HEAD
	LDA @VIRTUAL02
	CMP TILEMAP_UPDATE_TILE_COUNT
=======
	LDA $02
	CMP UNKNOWN_7E9F7E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BCC @UNKNOWN0
	PLD
	RTS
