
<<<<<<< HEAD
UNKNOWN_C3F705:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STA @LOCAL04
	MOVE_INT @PARAM01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, TILEMAP_UPDATE_REMAINING_TILES
	LDA @LOCAL04
	AND #$003F
	TAY
	STY @LOCAL02
	STY TILEMAP_UPDATE_TILE_X
	TXA
	AND #$001F
	STA @VIRTUAL02
	STA @LOCAL01
	LDA @VIRTUAL02
	STA TILEMAP_UPDATE_TILE_Y
=======
UNKNOWN_C3F705: ;$C3F705
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 26
	STA $18
	MOVE_INT $28, $06
	MOVE_INT $06, $14
	INC $06
	INC $06
	MOVE_INT $06, UNKNOWN_7E9F86
	LDA $18
	AND #$003F
	TAY
	STY $12
	STY UNKNOWN_7E9F7A
	TXA
	AND #$001F
	STA $02
	STA $10
	LDA $02
	STA UNKNOWN_7E9F7C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	AND #$001F
	BEQ @UNKNOWN0
	LDX #$3C00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX #$3800
@UNKNOWN1:
<<<<<<< HEAD
	STX TILEMAP_UPDATE_BASE_ADDRESS
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
=======
	STX UNKNOWN_7E9F84
	MOVE_INT $14, $06
	LDA [$06]
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	XBA
	AND #$00FF
	STA $18
	TAX
<<<<<<< HEAD
	STX @LOCAL00
	STX TILEMAP_UPDATE_TILE_COUNT
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @VIRTUAL04
	STA TILEMAP_UPDATE_TILE_HEIGHT
	LDA @LOCAL04
	STA @VIRTUAL02
=======
	STX $0E
	STX UNKNOWN_7E9F7E
	LDA [$06]
	AND #$00FF
	STA $04
	STA UNKNOWN_7E9F80
	LDA $18
	STA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	CLC
	ADC $02
	AND #$FFE0
	STA $04
	TYA
	AND #$FFE0
	CMP $04
	BNE @UNKNOWN2
<<<<<<< HEAD
	LDA @LOCAL04
	STA TILEMAP_UPDATE_TILE_WIDTH
=======
	LDA $18
	STA UNKNOWN_7E9F82
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR UNKNOWN_C3F5F9
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA $18
	STA $04
	LDY $12
	TYA
	CLC
	ADC $04
	AND #$FFE0
	SEC
<<<<<<< HEAD
	SBC TILEMAP_UPDATE_TILE_X
	STA TILEMAP_UPDATE_TILE_COUNT
	LDA @LOCAL04
	STA TILEMAP_UPDATE_TILE_WIDTH
=======
	SBC UNKNOWN_7E9F7A
	STA UNKNOWN_7E9F7E
	LDA $18
	STA UNKNOWN_7E9F82
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR UNKNOWN_C3F5F9
	LDA TILEMAP_UPDATE_BASE_ADDRESS
	EOR #$0400
<<<<<<< HEAD
	STA TILEMAP_UPDATE_BASE_ADDRESS
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	LDA TILEMAP_UPDATE_TILE_COUNT
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA TILEMAP_UPDATE_REMAINING_TILES
	LDA @VIRTUAL06+2
	STA TILEMAP_UPDATE_REMAINING_TILES+2
	STZ TILEMAP_UPDATE_TILE_X
	LDA @LOCAL01
	STA @VIRTUAL02
	STA TILEMAP_UPDATE_TILE_Y
	LDA @LOCAL04
	SEC
	SBC TILEMAP_UPDATE_TILE_COUNT
	STA @LOCAL04
	CMP #32
	BCS @UNKNOWN2
	STA TILEMAP_UPDATE_TILE_COUNT
	LDX @LOCAL00
	STX TILEMAP_UPDATE_TILE_WIDTH
=======
	STA UNKNOWN_7E9F84
	MOVE_INT UNKNOWN_7E9F86, $06
	LDA UNKNOWN_7E9F7E
	ASL
	CLC
	ADC $06
	STA $06
	STA UNKNOWN_7E9F86
	LDA $08
	STA UNKNOWN_7E9F88
	STZ UNKNOWN_7E9F7A
	LDA $10
	STA $02
	STA UNKNOWN_7E9F7C
	LDA $18
	SEC
	SBC UNKNOWN_7E9F7E
	STA $18
	CMP #$0020
	BCS @UNKNOWN2
	STA UNKNOWN_7E9F7E
	LDX $0E
	STX UNKNOWN_7E9F82
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR UNKNOWN_C3F5F9
@UNKNOWN3:
	PLD
	RTL
