
<<<<<<< HEAD
ENEMY_FLASHING_ON:
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	BEGIN_C_FUNCTION_FAR
.ELSE
	BEGIN_C_FUNCTION
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int enemy
	STACK_RESERVE_PARAM_INT16 ;int row
	END_STACK_VARS
	STX @LOCAL01
	STA @LOCAL00
	LDA CURRENT_FLASHING_ENEMY
=======
ENEMY_FLASHING_ON: ;$EF0052
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $10
	STA $0E
	LDA UNKNOWN_7E89D0
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CMP #$FFFF
	BEQ @UNKNOWN0
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	JSL ENEMY_FLASHING_OFF
.ELSE
	JSR ENEMY_FLASHING_OFF
.ENDIF
@UNKNOWN0:
<<<<<<< HEAD
	LDX @LOCAL01
	STX CURRENT_FLASHING_ENEMY
	LDA @LOCAL00
	STA CURRENT_FLASHING_ENEMY_ROW
=======
	LDX $10
	STX UNKNOWN_7E89D0
	LDA $0E
	STA UNKNOWN_7E89D2
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN1
	LDX CURRENT_FLASHING_ENEMY
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA BATTLERS_TABLE+74,X
	BRA @UNKNOWN2
@UNKNOWN1:
	.A16
	LDX CURRENT_FLASHING_ENEMY
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA BATTLERS_TABLE+74,X
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA ENEMY_TARGETTING_FLASHING
=======
	LDA #$0001
	STA UNKNOWN_7EADA2
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	PLD
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	RTL
.ELSE
	RTS
.ENDIF
