
FIND_STEALABLE_ITEMS: ;$C241DC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 26
	STZ $18
	STZ $16
	JMP @UNKNOWN12
@UNKNOWN0:
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA ($16),Y
	AND #$00FF
	STA $14
	CMP #$0001
	BCCL @UNKNOWN11
	LDA $14
	CMP #$0004
	BGTL @UNKNOWN11
	LDA #$0000
	STA $12
	BRA @UNKNOWN5
@UNKNOWN3:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN4
	LDA BATTLERS_TABLE,X
	CMP $14
	BNE @UNKNOWN4
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @UNKNOWN4
	LDA BATTLERS_TABLE+7,X
	AND #$00FF
	STA $10
@UNKNOWN4:
	LDA $12
	INC
	STA $12
@UNKNOWN5:
	CMP #$0006
	BCC @UNKNOWN3
	STZ $0E
	JMP @UNKNOWN10
@UNKNOWN6:
	LDA $0E
	STA $02
	INC $02
	LDA $02
	CMP $10
	BEQL @UNKNOWN9
	LDA $14
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAY
<<<<<<< HEAD
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @LOCAL00
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCALM2
	LDA @VIRTUAL04
.ELSE
	STY @LOCAL02
=======
	STY $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC $0E
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA $04
	BEQL @UNKNOWN9
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDA $04
	LDY #.SIZEOF(item)
	JSL MULT168
	TAX
	CLC
	ADC #item::cost
	MOVE_INTY $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	BEQ @UNKNOWN9
	CMP #$0122
	BCS @UNKNOWN9
	TXA
	CLC
	ADC #item::type
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	AND #$0030
	CMP #$0020
	BNE @UNKNOWN9
<<<<<<< HEAD
.IF .DEFINED(USA)
	LDY @LOCAL02
.ENDIF
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,Y
=======
	LDY $12
	LDA CHAR_STRUCT+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CMP $02
	BEQ @UNKNOWN9
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,Y
	AND #$00FF
	CMP $02
	BEQ @UNKNOWN9
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,Y
	AND #$00FF
	CMP $02
	BEQ @UNKNOWN9
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,Y
	AND #$00FF
	CMP $02
	BEQ @UNKNOWN9
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDY #.LOWORD(STEALABLE_ITEM_CANDIDATES)
	STA (@LOCAL05),Y
=======
	LDY #.LOWORD(UNKNOWN_7EA9D4)
	STA ($18),Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	INC $18
@UNKNOWN9:
	INC $0E
@UNKNOWN10:
	LDA $0E
	CMP #$000E
	BCCL @UNKNOWN6
@UNKNOWN11:
	INC $16
@UNKNOWN12:
	LDA $16
	CMP #$0006
	BCCL @UNKNOWN0
	LDA $18
	PLD
	RTS
