
INSTANT_WIN_CHECK: ;$C26634
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 36
	LDA BATTLE_INITIATIVE
	CMP #INITIATIVE::ENEMIES_FIRST
	BNE @UNKNOWN0
	LDA #$0000
	JMP @UNKNOWN37
@UNKNOWN0:
	STZ $22
	STZ $20
	LDA #$FFFF
	STA $02
	STA $1E
	LDA $02
	STA $04
	LDY #$0000
	STY $1C
	JMP @UNKNOWN7
@UNKNOWN1:
	LDA GAME_STATE + game_state::party_members,Y
	AND #$00FF
	TAX
	STX $1A
	CPX #$0001
	BCCL @UNKNOWN6
	CPX #$0004
	BGTL @UNKNOWN6
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::speed,X
	AND #$00FF
	CMP $04
	BCS @UNKNOWN4
	STA $04
@UNKNOWN4:
	LDX $1A
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::offense,X
	AND #$00FF
	CMP $02
	BCS @UNKNOWN5
	STA $02
	STA $1E
@UNKNOWN5:
	LDX $1A
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA $18
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	STA $16
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::DIAMONDIZED
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::PARALYZED
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::NAUSEOUS
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::POISONED
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::SUNSTROKE
	BEQ @UNKNOWN6
	LDA $16
	CMP #STATUS_0::COLD
	BEQ @UNKNOWN6
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_1::MUSHROOMIZED
	BEQ @UNKNOWN6
	CPX #STATUS_1::POSSESSED
	BEQ @UNKNOWN6
	LDA $20
	ASL
	PHA
	LDA $18
	TAX
	LDA PARTY_CHARACTERS+char_struct::offense,X
	AND #$00FF
	PLX
<<<<<<< HEAD
	STA INSTANT_WIN_SORTED_OFFENSE,X
	INC @LOCAL08
=======
	STA UNKNOWN_7EAA76,X
	INC $20
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN6:
	LDY $1C
	INY
	STY $1C
@UNKNOWN7:
	CPY #$0006
	BCCL @UNKNOWN1
	LDA ENEMIES_IN_BATTLE
	CMP $20
	BLTEQ @UNKNOWN9
	LDA #$0000
	JMP @UNKNOWN37
@UNKNOWN9:
	LDA BATTLE_INITIATIVE
	BNEL @UNKNOWN18
	LDA #$0000
	STA $1A
	BRA @UNKNOWN13
@UNKNOWN11:
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::speed
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	TAX
	CPX $22
	BLTEQ @UNKNOWN12
	STX $22
@UNKNOWN12:
	LDA $1A
	INC
	STA $1A
@UNKNOWN13:
	CMP ENEMIES_IN_BATTLE
	BCC @UNKNOWN11
	LDA $04
	CMP $22
	BCS @UNKNOWN14
	LDA #$0000
	JMP @UNKNOWN37
@UNKNOWN14:
	LDA #$0000
	STA $16
	BRA @UNKNOWN17
@UNKNOWN15:
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	MOVE_INT $06, $12
	LDA $16
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	TAX
	CLC
	ADC #enemy_data::defense
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $02
	TXA
	CLC
	ADC #enemy_data::hp
	MOVE_INTX $12, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	CLC
	ADC $02
	STA $04
	LDA $1E
	STA $02
	ASL
	CMP $04
	BCS @UNKNOWN16
	LDA #$0000
	JMP @UNKNOWN37
@UNKNOWN16:
	LDA $16
	INC
	STA $16
@UNKNOWN17:
	CMP ENEMIES_IN_BATTLE
	BCC @UNKNOWN15
	LDA #$0001
	JMP @UNKNOWN37
@UNKNOWN18:
	LDA #$0000
	STA $16
	BRA @UNKNOWN20
@UNKNOWN19:
	ASL
	TAY
	STY $1A
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	TYA
	CLC
	ADC #.LOWORD(ENEMIES_IN_BATTLE_IDS)
	TAX
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	MOVE_INTY $06, $0A
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	LDY @LOCAL05
	STA INSTANT_WIN_SORTED_HP,Y
=======
	ADC $0A
	STA $0A
	LDA [$0A]
	LDY $1A
	STA UNKNOWN_7EAA7E,Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::defense
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	LDY @LOCAL05
	STA INSTANT_WIN_SORTED_DEFENSE,Y
	LDA @LOCAL03
=======
	ADC $06
	STA $06
	LDA [$06]
	LDY $1A
	STA UNKNOWN_7EAA86,Y
	LDA $16
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $16
@UNKNOWN20:
	CMP ENEMIES_IN_BATTLE
	BCC @UNKNOWN19
@UNKNOWN21:
	LDY #$0001
	LDX #$0000
	STX $22
	BRA @UNKNOWN26
@UNKNOWN22:
	TXA
	INC
	STA $1C
	BRA @UNKNOWN25
@UNKNOWN23:
	LDX $22
	TXA
	ASL
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(INSTANT_WIN_SORTED_OFFENSE)
	STA @LOCAL07
	LDA (@LOCAL07)
	STA @LOCAL01
	LDA @LOCAL06
	ASL
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_OFFENSE)
	STA @VIRTUAL04
	LDX @VIRTUAL04
=======
	ADC #.LOWORD(UNKNOWN_7EAA76)
	STA $1E
	LDA ($1E)
	STA $10
	LDA $1C
	ASL
	CLC
	ADC #.LOWORD(UNKNOWN_7EAA76)
	STA $04
	LDX $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	STA $02
	CMP $10
	BLTEQ @UNKNOWN24
	LDY #$0000
	LDA $02
	STA ($1E)
	LDA $10
	LDX $04
	STA __BSS_START__,X
@UNKNOWN24:
	LDA $1C
	INC
	STA $1C
@UNKNOWN25:
	CMP $20
	BCC @UNKNOWN23
	LDX $22
	INX
	STX $22
@UNKNOWN26:
	LDA $20
	DEC
	STA $02
	TXA
	CMP $02
	BCC @UNKNOWN22
	CPY #$0000
	BEQ @UNKNOWN21
@UNKNOWN27:
	LDA #$0001
	STA $1E
	LDA #$0000
	STA $02
	BRA @UNKNOWN32
@UNKNOWN28:
	LDY $02
	INY
	BRA @UNKNOWN31
@UNKNOWN29:
	LDA $02
	ASL
	TAX
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @LOCAL05
	LDA (@LOCAL05)
	STA @LOCAL00
=======
	ADC #.LOWORD(UNKNOWN_7EAA7E)
	STA $1A
	LDA ($1A)
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	ASL
	STA $22
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @LOCAL03
	LDA (@LOCAL03)
	STA @VIRTUAL04
	CMP @LOCAL00
=======
	ADC #.LOWORD(UNKNOWN_7EAA7E)
	STA $16
	LDA ($16)
	STA $04
	CMP $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BLTEQ @UNKNOWN30
	STZ $1E
	LDA $04
	STA ($1A)
	LDA $0E
	STA ($16)
	TXA
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	STA @LOCAL05
	LDA (@LOCAL05)
	STA @VIRTUAL04
	LDA @LOCAL09
=======
	ADC #.LOWORD(UNKNOWN_7EAA86)
	STA $1A
	LDA ($1A)
	STA $04
	LDA $22
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	TAX
	LDA __BSS_START__,X
	STA ($1A)
	LDA $04
	STA __BSS_START__,X
@UNKNOWN30:
	INY
@UNKNOWN31:
	CPY ENEMIES_IN_BATTLE
	BCC @UNKNOWN29
	INC $02
@UNKNOWN32:
	LDA ENEMIES_IN_BATTLE
	DEC
	STA $04
	LDA $02
	CMP $04
	BCC @UNKNOWN28
	LDA $1E
	BEQ @UNKNOWN27
	LDX #$0000
	STX $22
	TXA
	STA $1C
	BRA @UNKNOWN36
@UNKNOWN33:
	ASL
	TAX
	LDA INSTANT_WIN_SORTED_OFFENSE,X
	ASL
	STA $04
	LDX $22
	TXA
	ASL
	STA $1A
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @VIRTUAL02
	STA @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	STY @LOCAL04
	LDY #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	LDA (@LOCAL05),Y
	STA @LOCAL05
	LDY @LOCAL04
=======
	ADC #.LOWORD(UNKNOWN_7EAA7E)
	STA $02
	STA $16
	LDX $02
	LDA __BSS_START__,X
	TAY
	STY $18
	LDY #.LOWORD(UNKNOWN_7EAA86)
	LDA ($1A),Y
	STA $1A
	LDY $18
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	CLC
	ADC $1A
	STA $02
	LDA $04
	CMP $02
	BCS @UNKNOWN34
	LDA $04
	SEC
	SBC $1A
	STA $02
	TYA
	SEC
	SBC $02
	LDX $16
	STX $02
	STA __BSS_START__,X
	BRA @UNKNOWN35
@UNKNOWN34:
	LDX $22
	INX
	STX $22
	CPX ENEMIES_IN_BATTLE
	BCC @UNKNOWN35
	LDA #$0001
	BRA @UNKNOWN37
@UNKNOWN35:
	LDA $1C
	INC
	STA $1C
@UNKNOWN36:
	CMP $20
	BCC @UNKNOWN33
	LDA #$0000
@UNKNOWN37:
	PLD
	RTL
