
<<<<<<< HEAD
RETURN_BATTLE_ATTACKER_ADDRESS:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	LDA #.LOWORD(BATTLE_ATTACKER_NAME)
	END_C_FUNCTION
=======
RETURN_BATTLE_ATTACKER_ADDRESS: ;$C1AC9B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #.LOWORD(UNKNOWN_7E9CD7)
	RTS
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
