
<<<<<<< HEAD
WEAKEN_SHIELD:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	STZ SHIELD_HAS_NULLIFIED_DAMAGE
	LDA DAMAGE_IS_REFLECTED
=======
WEAKEN_SHIELD: ;$C294CE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	STZ UNKNOWN_7EAA94
	LDA UNKNOWN_7EAA96
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN1
	JSR SWAP_ATTACKER_WITH_TARGET
	LDA CURRENT_TARGET
	CLC
	ADC #battler::shield_hp
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN0
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIELD_OFF
@UNKNOWN0:
	STZ DAMAGE_IS_REFLECTED
@UNKNOWN1:
	PLD
	RTS
