
<<<<<<< HEAD
ATTEMPT_HOMESICKNESS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA PARTY_CHARACTERS+char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL
=======
ATTEMPT_HOMESICKNESS: ;$C1BE4D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CHAR_STRUCT+char_struct::afflictions
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CMP #$0001
	BEQ @FAILED
	LDX #$0000
	LDA #$000F
	STA $0E
	BRA @UNKNOWN5
@UNKNOWN0:
<<<<<<< HEAD
	LDA @LOCAL00
	STA @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::level
=======
	LDA $0E
	STA $02
	LDA CHAR_STRUCT+char_struct::level
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN4
	LDA f:HOMESICKNESS_PROBABILITY,X
	AND #$00FF
	BEQ @UNKNOWN3
	AND #$00FF
	JSL RAND_MOD
	CMP #$0000
	BNE @UNKNOWN3
	LDY #$0002
	LDX #$0006
	LDA #$0001
	JSL INFLICT_STATUS_NONBATTLE
	BRA @RETURN
@UNKNOWN3:
	LDA #$0000
	BRA @RETURN
@UNKNOWN4:
	INX
	LDA $0E
	CLC
	ADC #$000F
	STA $0E
@UNKNOWN5:
	STX $02
	LDA #$0006
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN0
@FAILED:
	LDA #$0000
@RETURN:
	PLD
	RTS
