
<<<<<<< HEAD
FIND_FREE_7E4682:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL02
	LDX #0
	STX @LOCAL01
	LDA @VIRTUAL02
	STA UNREAD_7E4A6A
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA OVERWORLD_SPRITEMAPS + spritemap::special_flags,X
=======
FIND_FREE_7E4682: ;$C01A9D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $02
	LDX #$0000
	STX $10
	LDA $02
	STA UNKNOWN_7E4A6A
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA SPRITE_TABLE_7E467E+4,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CMP #$00FF
	BEQ @UNKNOWN2
	TXA
	CLC
	ADC #$0005
	TAX
	STX $10
@UNKNOWN1:
	CPX #$0380
	BCC @UNKNOWN0
	LDA #$FF01
	BRA @UNKNOWN7
@UNKNOWN2:
	TXA
	CLC
	ADC $02
	CMP #$0380
	BCS @UNKNOWN6
	TXA
	STA $0E
	BRA @UNKNOWN5
@UNKNOWN3:
	TAX
<<<<<<< HEAD
	LDA OVERWORLD_SPRITEMAPS + spritemap::special_flags,X
=======
	LDA SPRITE_TABLE_7E467E+4,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	CMP #$00FF
	BEQ @UNKNOWN4
	LDA $0E
	CLC
	ADC #$0005
	TAX
	STX $10
	BRA @UNKNOWN1
@UNKNOWN4:
	LDA $0E
	CLC
	ADC #$0005
	STA $0E
@UNKNOWN5:
	LDX $10
	TXA
	CLC
	ADC $02
	STA $04
	LDA $0E
	CMP $04
	BCC @UNKNOWN3
	TXA
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA #$FF02
@UNKNOWN7:
	PLD
	RTL
