
<<<<<<< HEAD
FIND_NEARBY_CHECKABLE_TPT_ENTRY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #.LOWORD(-1)
	STA INTERACTING_NPC_ID
	STA INTERACTING_NPC_ENTITY
=======
FIND_NEARBY_CHECKABLE_TPT_ENTRY: ;$C04279
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA #$FFFF
	STA CURRENT_TPT_ENTRY
	STA UNKNOWN_7E5D64
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR UNKNOWN_C041E3
	STA $10
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDX #.LOWORD(GAME_STATE) + game_state::current_party_members
	STX $0E
	LDA __BSS_START__,X
	ASL
	TAX
	LDA $10
	CMP ENTITY_DIRECTIONS,X
	BEQ @UNKNOWN0
	STA GAME_STATE+game_state::leader_direction
	LDX $0E
	LDA __BSS_START__,X
	ASL
	TAX
	LDA $10
	STA ENTITY_DIRECTIONS,X
	LDX $0E
	LDA __BSS_START__,X
	JSL UNKNOWN_C0A780
@UNKNOWN0:
<<<<<<< HEAD
	LDA INTERACTING_NPC_ID
	END_C_FUNCTION
=======
	LDA CURRENT_TPT_ENTRY
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
