
<<<<<<< HEAD
OVERWORLD_INITIALIZE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
=======
;void OW_Initialize(void)
OVERWORLD_INITIALIZE: ;$C0004B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL OVERWORLD_SETUP_VRAM
	LDA #$0000
	STA [$06]
	COPY_TO_VRAM1P $06, $0000, $0000, $03
	.A16
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	END_C_FUNCTION
=======
	LDA #$FFFF
	STA UNKNOWN_7E4370
	STA UNKNOWN_7E436E
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
