
<<<<<<< HEAD
LOAD_SPECIAL_SPRITE_PALETTE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	LDA __BSS_START__ + BPP4PALETTE_SIZE * 2,X
=======
;void LoadSpecialSpritePalette(void)
LOAD_SPECIAL_SPRITE_PALETTE: ;$C00778
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDX #.LOWORD(CUR_MAP_PAL)
	LDA __BSS_START__+64,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN2
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(PALETTES)
	TAX
	STX $10
	LDA #$0040
	STA $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	PHA
	LDA __BSS_START__,X
	PLX
<<<<<<< HEAD
	STA PALETTES + BPP4PALETTE_SIZE * 8,X
	LDX @LOCAL01
=======
	STA CUR_SPRITE_PALS,X
	LDX $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INX
	INX
	STX $10
	LDA $0E
	INC
	STA $0E
@UNKNOWN1:
	CMP #$0050
	BCC @UNKNOWN0
@UNKNOWN2:
	PLD
	RTL
