
LOAD_DAD_PHONE: ;$C0DCC6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA WINDOW_HEAD
	CMP #$FFFF
	BNE @UNKNOWN0
	LDA BATTLE_MODE_FLAG
	BNE @UNKNOWN0
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN0
	LDA DAD_PHONE_QUEUED
	BNE @UNKNOWN0
	LDA #EVENT_FLAG::FLG_SYS_DIS_2H_PAPA
	JSL GET_EVENT_FLAG
	CMP #$0000
	BNE @UNKNOWN0
	LOADPTR MSG_SYS_PAPA_2H, $0E
	LDA #$000A
	JSL UNKNOWN_C064E3
<<<<<<< HEAD
	LDA #1
	STA DAD_PHONE_QUEUED
=======
	LDA #$0001
	STA UNKNOWN_7E9E56
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	PLD
	RTL
