
PREPARE_YOUR_SANCTUARY_LOCATION_TILESET_DATA: ;$C4E08C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	STA $14
	LDA #$0000
	STA $04
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA $04
	ASL
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(LOADED_MAP_BLOCKS)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	BEQ @UNKNOWN1
	LOADPTR BUFFER + $8000, @VIRTUAL06
	LDA @VIRTUAL04
=======
	ADC #.LOWORD(UNKNOWN_7EF000)
	STA $02
	LDX $02
	LDA __BSS_START__,X
	BEQ @UNKNOWN1
	LOADPTR UNKNOWN_7F8000, $06
	LDA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
=======
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA UNKNOWN_7EB4B8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6000
	AND #$7FFF
	TAY
	LDX #$0020
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL PREPARE_VRAM_COPY
	.A16
<<<<<<< HEAD
	LDA NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
	LDX @VIRTUAL02
=======
	LDA UNKNOWN_7EB4B8
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	INC NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
	INC YOUR_SANCTUARY_LOADED_TILESET_TILES
@UNKNOWN1:
	INC $04
@UNKNOWN2:
	LDA $04
	CMP #$0400
	BCC @UNKNOWN0
<<<<<<< HEAD
	LOADPTR BUFFER, @VIRTUAL06
=======
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDY #$0800
	LDA $14
	JSL MULT16
	CLC
	ADC $06
	STA $06
	LDX #$0000
	STX $12
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA [$06]
	STA $14
	AND #$03FF
	ASL
	TAX
	LDA $14
	AND #$FC00
<<<<<<< HEAD
	ORA LOADED_MAP_BLOCKS,X
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDX @LOCAL01
=======
	ORA UNKNOWN_7EF000,X
	STA [$06]
	INC $06
	INC $06
	LDX $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INX
	STX $12
@UNKNOWN4:
	CPX #$03C0
	BCC @UNKNOWN3
	PLD
	RTS
