
<<<<<<< HEAD
PROCESS_ITEM_TRANSFORMATIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA ENEMY_HAS_BEEN_TOUCHED
=======
PROCESS_ITEM_TRANSFORMATIONS: ;$C48FC4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA BATTLE_SWIRL_FLAG
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC BATTLE_SWIRL_COUNTDOWN
	BNEL @UNKNOWN8
	LDA DISABLED_TRANSITIONS
	BNEL @UNKNOWN8
	LDA GAME_STATE + game_state::unknownB0
	CMP #$0002
	BEQL @UNKNOWN8
	SEP #PROC_FLAGS::ACCUM8
	LDA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
	DEC
	STA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN8
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #60
	STA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
=======
	LDA #$003C
	STA UNKNOWN_7E9F2C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(LOADED_TIMED_ITEM_TRANSFORMATIONS)
	STA $02
	LDA #$0001
	STA $14
	LDA #$0000
	STA $04
	STA $12
	JMP @UNKNOWN7
@UNKNOWN4:
	LDA $14
	BEQ @UNKNOWN5
	LDY $02
	INY
	STY $10
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @UNKNOWN5
	LDX $02
	INX
	INX
	STX $0E
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN5
	LDA #$0002
	JSL RAND_MOD
	SEP #PROC_FLAGS::ACCUM8
	STA $00
	LDY $10
	LDA __BSS_START__,Y
	CLC
	ADC $00
	DEC
	LDX $0E
	STA __BSS_START__,X
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	JSL PLAY_SOUND
	STZ $14
@UNKNOWN5:
	LDX $02
	INX
	INX
	INX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN6
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN6
	LOADPTR TIMED_ITEM_TRANSFORMATION_TABLE, $06
	LDA $04
	OPTIMIZED_MULT $04, .SIZEOF(timed_item_transformation)
	TAY
	STY $0E
	TYA
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	TAX
	LDA #$00FF
	JSL TAKE_ITEM_FROM_CHARACTER
	STA $10
	LDY $0E
	TYA
	INC
	INC
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	TAX
	LDA $10
	JSL GIVE_ITEM_TO_CHARACTER
@UNKNOWN6:
	INC $02
	INC $02
	INC $02
	INC $02
	LDA $12
	STA $04
	INC $04
	LDA $04
	STA $12
@UNKNOWN7:
	LDA $04
	CMP #$0004
	BCCL @UNKNOWN4
@UNKNOWN8:
	PLD
	RTL
