
<<<<<<< HEAD
RELOAD_MAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(-1)
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	LDA SCREEN_X_PIXELS
=======
;void ReloadMap(void)
RELOAD_MAP: ;$C018F3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA #$FFFF
	STA UNKNOWN_7E4370
	STA UNKNOWN_7E436E
	LDA UNKNOWN_7E4380
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$FFF8
	STA SCREEN_X_PIXELS
	LDA SCREEN_Y_PIXELS
	AND #$FFF8
	STA SCREEN_Y_PIXELS
	JSL UNKNOWN_C08726
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA CURRENT_MAP_MUSIC_TRACK
=======
	LDA #$FFFF
	STA UNKNOWN_7E5DD4
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #.LOWORD(GAME_STATE) + game_state::leader_x_coord
	STA $04
	LDA #.LOWORD(GAME_STATE) + game_state::leader_y_coord
	STA $02
	LDX $02
	LDA __BSS_START__,X
	TAX
	STX $10
	LDX $04
	LDA __BSS_START__,X
	LDX $10
	JSL UNKNOWN_C068F4
	LDA #$0009
	JSL UNKNOWN_C08D79
	LDY #$0000
	LDX #$3800
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #$2000
	LDX #$5800
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG2_VRAM_LOCATION
	LDY #$6000
	LDX #$7C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LDA #$0062
	JSL SET_OAM_SIZE
	LDX $02
	LDA __BSS_START__,X
	TAX
	STX $0E
	LDX $04
	LDA __BSS_START__,X
	LDX $0E
	JSL RELOAD_MAP_AT_POSITION
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BNE @UNKNOWN0
	LDA #MUSIC::BICYCLE
	JSL CHANGE_MUSIC
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL UNKNOWN_C069AF
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA DEBUG
	BEQ @UNKNOWN2
	JSL UNKNOWN_EFD9F3
@UNKNOWN2:
	JSL UNKNOWN_C08744
	PLD
	RTL
