
<<<<<<< HEAD
RELOAD_MAP_AT_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	END_STACK_VARS
	STA SCREEN_X_PIXELS
	STA SCREEN_X_PIXELS_COPY
	STX SCREEN_Y_PIXELS
	STX SCREEN_Y_PIXELS_COPY
=======
;void ReloadMapAtPos(int x, int y)
RELOAD_MAP_AT_POSITION: ;$C012ED
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	STA UNKNOWN_7E4380
	STA UNKNOWN_7E437C
	STX UNKNOWN_7E4382
	STX UNKNOWN_7E437E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LSR
	LSR
	LSR
	TAY
	STY $14
	TXA
	LSR
	LSR
	LSR
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA #.LOWORD(-1)
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	LDA @VIRTUAL02
=======
	STA $02
	LDA #$FFFF
	STA UNKNOWN_7E4370
	STA UNKNOWN_7E436E
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LSR
	LSR
	LSR
	LSR
	TAX
	TYA
	LSR
	LSR
	LSR
	LSR
	LSR
	JSR LOAD_MAP_AT_SECTOR
	LDY $14
	TYA
	SEC
	SBC #$0010
	STA $12
	LDA $02
	SEC
	SBC #$000E
	STA $10
	TYA
	SEC
	SBC #$0020
	STA $04
	LDA $02
	SEC
	SBC #$0020
	STA $02
	STA $0E
	LDX #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #>-1
	STA LOADED_COLUMNS_Y,X
	STA LOADED_COLUMNS_X,X
	STA LOADED_ROWS_Y,X
	STA LOADED_ROWS_X,X
=======
	LDA #$00FF
	STA UNKNOWN_7E43C0,X
	STA UNKNOWN_7E43B0,X
	STA UNKNOWN_7E43A0,X
	STA UNKNOWN_7E4390,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INX
@UNKNOWN1:
	CPX #$0010
	BCC @UNKNOWN0
	LDY #$0000
	STY $14
	BRA @UNKNOWN3
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA $02
	STY $02
	CLC
	ADC $02
	TAX
	LDA $04
	JSR UNKNOWN_C00AC5
	LDY $14
	INY
	STY $14
@UNKNOWN3:
	CPY #$003C
	BCC @UNKNOWN2
	LDY #$0000
	STY $14
	BRA @UNKNOWN5
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA $02
	STY $02
	CLC
	ADC $02
	TAX
	LDA $04
	JSR LOAD_COLLISION_ROW
	LDY $14
	INY
	STY $14
@UNKNOWN5:
	CPY #$003C
	BCC @UNKNOWN4
	LDY #$FFFF
	STY $14
	BRA @UNKNOWN7
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC $10
	TAX
	LDA $12
	JSR UNKNOWN_C00E16
	LDY $14
	INY
	STY $14
@UNKNOWN7:
	CPY #$001F
	BNE @UNKNOWN6
@UNKNOWN8:
	REP #PROC_FLAGS::ACCUM8
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @UNKNOWN8
	LDA SCREEN_X_PIXELS
	SEC
	SBC #$0080
	STA BG2_X_POS
	STA BG1_X_POS
	LDA SCREEN_Y_PIXELS
	SEC
	SBC #$0070
	STA BG2_Y_POS
	STA BG1_Y_POS
<<<<<<< HEAD
	LDA @LOCAL02
	STA SCREEN_LEFT_X
	LDA @LOCAL01
	STA SCREEN_TOP_Y
	END_C_FUNCTION
=======
	LDA $12
	STA UNKNOWN_7E4374
	LDA $10
	STA UNKNOWN_7E4376
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
