
TALK_TO: ;$C13187
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	MOVE_INT_CONSTANT NULL, $0A
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSL FIND_NEARBY_TALKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQL @UNKNOWN4
<<<<<<< HEAD
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN4
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-2)
	BNE @UNKNOWN2
	MOVE_INT MAP_OBJECT_TEXT, @VIRTUAL0A
	BRA @UNKNOWN4
@UNKNOWN2:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
=======
	LDA CURRENT_TPT_ENTRY
	CMP #$FFFF
	BEQL @UNKNOWN4
	LDA CURRENT_TPT_ENTRY
	CMP #$FFFE
	BNE @UNKNOWN2
	MOVE_INT UNKNOWN_7E5DDE, $0A
	BRA @UNKNOWN4
@UNKNOWN2:
	LOADPTR NPC_CONFIG_TABLE, $06
	MOVE_INT $06, $0E
	LDA CURRENT_TPT_ENTRY
	OPTIMIZED_MULT $04, .SIZEOF(npc_config)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	CMP #NPC_TYPE::PERSON
	BEQ @UNKNOWN3
	CMP #NPC_TYPE::ITEM_BOX
	BEQ @UNKNOWN4
	CMP #NPC_TYPE::OBJECT
	BEQ @UNKNOWN4
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA INTERACTING_NPC_ENTITY
	JSL UNKNOWN_C042C2
<<<<<<< HEAD
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
=======
	LDA CURRENT_TPT_ENTRY
	OPTIMIZED_MULT $04, .SIZEOF(npc_config)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #npc_config::text_pointer
	MOVE_INTX $0E, $06
	CLC
	ADC $06
	STA $06
	DEREFERENCE_PTR_TO $06, $0A
@UNKNOWN4:
	MOVE_INT $0A, $18
	PLD
	RTL
