
UNKNOWN_C200D9: ;$C200D9
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	SEP #PROC_FLAGS::ACCUM8
	STZ RENDER_HPPP_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA #$FFFF
	STA CURRENT_FLASHING_ENEMY_ROW
	STA CURRENT_FLASHING_ENEMY
	STA CURRENT_FLASHING_ROW
	STA UNREAD_7E89CC
	STA BATTLE_MENU_CURRENT_CHARACTER_ID
	SEP #PROC_FLAGS::ACCUM8
	STZ INSTANT_PRINTING
	STZ REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	STZ ACTIONSCRIPT_STATE
	SEP #PROC_FLAGS::ACCUM8
	STZ UPLOAD_HPPP_METER_TILES
	REP #PROC_FLAGS::ACCUM8
	LDA #$FFFF
	STA WINDOW_HEAD
	STA WINDOW_TAIL
	LDA #$0000
	STA $10
	BRA @UNKNOWN1
@UNKNOWN0:
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA #$FFFF
<<<<<<< HEAD
	STA WINDOW_STATS+window_stats::id,X
	LDA @LOCAL01
=======
	STA WINDOW_STATS_TABLE+window_stats::id,X
	LDA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $10
@UNKNOWN1:
	CMP #$0008
	BNE @UNKNOWN0
	LDA #$0000
	STA $10
	BRA @UNKNOWN3
@UNKNOWN2:
	ASL
	TAX
	LDA #$FFFF
<<<<<<< HEAD
	STA OPEN_WINDOW_TABLE,X
	LDA @LOCAL01
=======
	STA WINDOW_EXISTENCE_TABLE,X
	LDA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $10
@UNKNOWN3:
	CMP #$0035
	BNE @UNKNOWN2
	LDA #$0000
	STA $10
	BRA @UNKNOWN5
@UNKNOWN4:
	ASL
	TAX
	LDA #$FFFF
<<<<<<< HEAD
	STA TITLED_WINDOWS,X
	LDA @LOCAL01
=======
	STA UNKNOWN_7E894E,X
	LDA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $10
@UNKNOWN5:
	CMP #$0005
	BNE @UNKNOWN4
	LDA #$FFFF
	STA PAGINATION_WINDOW
	STA PAGINATION_ANIMATION_FRAME
	LDY #.LOWORD(BG2_BUFFER)
	LDX #$0380
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA #$0000
	STA __BSS_START__,Y
	INY
	INY
	DEX
@UNKNOWN7:
	BNE @UNKNOWN6
	LDA #$0000
	STA $10
	BRA @UNKNOWN9
@UNKNOWN8:
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	TAX
	STZ MENU_OPTIONS,X
	LDA $10
	INC
	STA $10
@UNKNOWN9:
	CMP #$0046
	BNE @UNKNOWN8
	LDA #$0000
	STA $0E
	BRA @UNKNOWN13
@UNKNOWN10:
	LDX #$0000
	STX $10
	BRA @UNKNOWN12
@UNKNOWN11:
	STX $02
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA UNKNOWN_7E9D23,X
	LDX $10
	INX
	STX $10
@UNKNOWN12:
	CPX #$0020
	BCC @UNKNOWN11
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	INC
	STA $0E
@UNKNOWN13:
	CMP #$0008
	BCC @UNKNOWN10
	STZ UNKNOWN_7E9E29
	STZ UNKNOWN_7E9E27
	STZ VWF_TILE
	STZ VWF_X
	STZ BLINKING_TRIANGLE_FLAG
	LDA #$0001
	STA TEXT_SOUND_MODE
	STZ BATTLE_MODE_FLAG
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	LDA #$FFFF
	STA CURRENT_FOCUS_WINDOW
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA CHARACTER_PADDING
=======
	LDA #$0001
	STA UNKNOWN_7E5E6D
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C43F53
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA UNREAD_7E9651
	REP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA ENABLE_WORD_WRAP
	SEP #PROC_FLAGS::ACCUM8
	STZ EXTRA_TICK_ON_WINDOW_CLOSE
	STZ VWF_INDENT_NEW_LINE
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDA a:window_stats::current_option,X
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	STZ __BSS_START__+44,X
<<<<<<< HEAD
	STZ NEW_TEXT_PIXEL_OFFSET
	STZ LAST_TEXT_PIXEL_OFFSET_SET
	STZ FORCE_CENTRE_TEXT_ALIGNMENT
	STZ LAST_PRINTED_CHARACTER
	STZ PRINT_TARGET_ARTICLE
	STZ PRINT_ATTACKER_ARTICLE
.IF !.DEFINED(PROTOTYPE19950327)
	STZ FORCE_NORMAL_FONT_FOR_LENGTH_CALCULATIONS
	STZ SKIP_ADDING_COMMAND_TEXT
.ENDIF
=======
	STZ UNKNOWN_7E5E72
	STZ UNKNOWN_7E5E73
	STZ UNKNOWN_7E5E74
	STZ UNKNOWN_7E5E76
	STZ UNKNOWN_7E5E78
	STZ UNKNOWN_7E5E77
	STZ UNKNOWN_7EB4CE
	STZ $5E6C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
