
UNKNOWN_C202AC: ;$C202AC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $02
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	CLC
	ADC #window_stats::title
	STA $04
	LDA a:window_stats::unknown59,Y
	AND #$00FF
	BNE @UNKNOWN3
	LDA #$0000
	STA $10
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	CLC
	ADC #.LOWORD(TITLED_WINDOWS)
	TAX
	STX $0E
	LDA __BSS_START__,X
	CMP #$FFFF
	BEQ @UNKNOWN2
	LDA $10
	INC
	STA $10
@UNKNOWN1:
	CMP #$0005
	BNE @UNKNOWN0
	BRA @UNKNOWN4
@UNKNOWN2:
	LDA $02
	ASL
	TAX
<<<<<<< HEAD
	LDA OPEN_WINDOW_TABLE,X
	LDX @LOCAL00
=======
	LDA WINDOW_EXISTENCE_TABLE,X
	LDX $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LDA $10
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA a:window_stats::unknown59,Y
@UNKNOWN3:
	REP #PROC_FLAGS::ACCUM8
	LDA a:window_stats::unknown59,Y
	AND #$00FF
	DEC
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$7700
	TAX
	LDA $04
	JSL UNKNOWN_C444FB
@UNKNOWN4:
	PLD
	RTS
