
UNKNOWN_C207B6: ;$C207B6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	SEP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	JSL ASL16_ENTRY2
<<<<<<< HEAD
	ORA CURRENTLY_DRAWN_HPPP_WINDOWS
	STA CURRENTLY_DRAWN_HPPP_WINDOWS
	LDA @LOCAL00
	JSR DRAW_HP_PP_WINDOW
	LDA #1
	STA HPPP_METER_AREA_NEEDS_UPDATE
	END_C_FUNCTION
=======
	ORA UNKNOWN_7E9647
	STA UNKNOWN_7E9647
	LDA $0E
	JSR DRAW_HP_PP_WINDOW
	LDA #$0001
	STA UNKNOWN_7E9649
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
