
UNKNOWN_C2108C: ;$C2108C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL UNKNOWN_C21034
	CMP #$0000
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STZ FASTEST_HPPP_METER_SPEED
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	RTL
