
UNKNOWN_C22562: ;$C22562
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	CPX #$FFFF
	BNE @UNKNOWN0
	LDX #$0000
@UNKNOWN0:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA TEMPORARY_WEAPON
	REP #PROC_FLAGS::ACCUM8
	LDA CHARACTER_FOR_EQUIP_MENU
	AND #$00FF
	STA $0E
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	STA TEMPORARY_BODY_GEAR
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	STA TEMPORARY_ARMS_GEAR
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	STA TEMPORARY_OTHER_GEAR
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	JSL UNKNOWN_C1A1D8
	PLD
	RTL
