
UNKNOWN_C226C5: ;$C226C5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	LDA CURRENT_INTERACTING_EVENT_FLAG
	JSL SET_EVENT_FLAG
	TAX
<<<<<<< HEAD
	STX @LOCAL00
	LDA INTERACTING_NPC_ENTITY
=======
	STX $0E
	LDA UNKNOWN_7E5D64
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0C30C
	LDX $0E
	TXA
	PLD
	RTL
