
<<<<<<< HEAD
UNKNOWN_C2260D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA CHARACTER_FOR_EQUIP_MENU
=======
UNKNOWN_C2260D: ;$C2260D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $10
	LDA UNKNOWN_7E9CD6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	STA TEMPORARY_WEAPON
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	STA TEMPORARY_BODY_GEAR
	REP #PROC_FLAGS::ACCUM8
	LDA $10
	CMP #$FFFF
	BNE @UNKNOWN0
	LDX #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	TAX
@UNKNOWN1:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA TEMPORARY_ARMS_GEAR
	REP #PROC_FLAGS::ACCUM8
	LDA CHARACTER_FOR_EQUIP_MENU
	AND #$00FF
	TAX
	STX $0E
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	STA TEMPORARY_OTHER_GEAR
	LDX @LOCAL00
=======
	LDA CHAR_STRUCT+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	STA UNKNOWN_7E9CD3
	LDX $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL UNKNOWN_C1A1D8
	PLD
	RTL
