
UNKNOWN_C24434: ;$C24434
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
<<<<<<< HEAD
	STX @LOCAL00
	LDA NUM_BATTLERS_IN_FRONT_ROW
=======
	STX $0E
	LDA NUM_BATTLERS_IN_BACK_ROW
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC NUM_BATTLERS_IN_BACK_ROW
	JSR RAND_LIMIT
	SEP #PROC_FLAGS::ACCUM8
	INC
	LDX $0E
	STA a:battler::current_target,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP NUM_BATTLERS_IN_FRONT_ROW
	BLTEQ @UNKNOWN0
	SEC
	SBC NUM_BATTLERS_IN_FRONT_ROW
	TAX
	DEX
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	BRA @UNKNOWN1
@UNKNOWN0:
	TAX
	DEX
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
@UNKNOWN1:
	PLD
	RTL
