
<<<<<<< HEAD
UNKNOWN_C2D0AC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #.LOWORD(LETTERBOX_HDMA_TABLE)
=======
UNKNOWN_C2D0AC: ;$C2D0AC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDX #.LOWORD(UNKNOWN_7EADB8)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_TOP_END
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_NONVISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	LDA LETTERBOX_BOTTOM_START
	SEC
<<<<<<< HEAD
	SBC LETTERBOX_TOP_END
	STA @LOCAL00
=======
	SBC UNKNOWN_7EADB2
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$007F
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_VISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	LDA $0E
	SEC
	SBC #$007F
	STA $0E
@UNKNOWN1:
	CMP #$0080
	BCS @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_VISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_NONVISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
