
UNKNOWN_C2E6B3: ;$C2E6B3
	.BYTE $30, $00, $00
<<<<<<< HEAD
UNKNOWN_C2E6B6:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	END_STACK_VARS
.IF .DEFINED(JPN) ;wonder why these got swapped?
	@VIRTUALTMP01 := @VIRTUAL04
	@VIRTUALTMP02 := @VIRTUAL02
.ELSE
	@VIRTUALTMP01 := @VIRTUAL02
	@VIRTUALTMP02 := @VIRTUAL04
.ENDIF
	LDA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
=======
UNKNOWN_C2E6B6: ;$C2E6B6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 27
	LDA UNKNOWN_7E1B9E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BEQL @UNKNOWN12
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::time_until_next_frame
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN4
<<<<<<< HEAD
	LDA #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::total_frames
	STA @VIRTUAL04
	LDX @VIRTUAL04
=======
	LDA #.LOWORD(UNKNOWN_7E1BA0)
	STA $04
	LDX $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN3
	SEP #PROC_FLAGS::ACCUM8
	LDA PSI_ANIMATION_STATE + psi_animation_state::frame_hold_frames
	STA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::frame_data
	STA @VIRTUAL02
	LDY @VIRTUAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	COPY_TO_VRAM1P @VIRTUAL06, $5800, $400, $06
=======
	LDA #.LOWORD(UNKNOWN_7E1BA1)
	STA $02
	LDY $02
	MOVE_INT_YPTRSRC __BSS_START__, $06
	COPY_TO_VRAM1P $06, $5800, $400, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	.A16
	COPY_TO_VRAM1 UNKNOWN_C2E6B3, $5800, $400, $0F
	.A16
	LDY $02
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDA #$0400
	CLC
	ADC $06
	STA $06
	LDY $02
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDX $04
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	LDX $04
	STA __BSS_START__,X
	BRA @UNKNOWN4
@UNKNOWN3:
	.A16
	COPY_TO_VRAM1 UNKNOWN_C2E6B3+1, $5800, $800, $03
	JSL UNKNOWN_C2DE96
@UNKNOWN4:
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::palette_animation_time_until_next_frame
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $1A
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @UNKNOWN12
	SEP #PROC_FLAGS::ACCUM8
	LDA $1A
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN12
	SEP #PROC_FLAGS::ACCUM8
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_frames
	STA __BSS_START__,X
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_upper_index
	SEC
	SBC PSI_ANIMATION_STATE + psi_animation_state::palette_animation_lower_index
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA $02
	INC $02
	LDX #$0000
	STX $18
	BRA @UNKNOWN10
@UNKNOWN7:
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_current_index
	AND #$00FF
	STA $04
	TXA
	CMP $04
	BCS @UNKNOWN8
	TXA
	CLC
	ADC $02
	SEC
	SBC $04
	STA $04
	STA $16
	BRA @UNKNOWN9
@UNKNOWN8:
	TXA
	SEC
	SBC $04
	STA $04
	STA $16
@UNKNOWN9:
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_lower_index
	AND #$00FF
	STA $14
	STX $04
	CLC
	ADC $04
	ASL
	CLC
	ADC PSI_ANIMATION_STATE + psi_animation_state::displayed_palette
	PHA
	LDA $16
	STA $04
	LDA $14
	CLC
	ADC $04
	ASL
<<<<<<< HEAD
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(PSI_ANIMATION_STATE)
	TAX
	LDA a:psi_animation_state::palette,X
.ELSE
	TAX
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette,X
.ENDIF
=======
	TAX
	LDA UNKNOWN_7E1BAA,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	PLX
	STA __BSS_START__,X
	LDX $18
	INX
	STX $18
@UNKNOWN10:
	TXA
	CMP $02
	BCC @UNKNOWN7
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::palette_animation_current_index
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP $02
	BCC @UNKNOWN11
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
@UNKNOWN11:
	REP #PROC_FLAGS::ACCUM8
	LDA #$0018
	JSL UNKNOWN_C0856B
@UNKNOWN12:
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::enemy_colour_change_start_frames_left
	LDA __BSS_START__,X
	BEQ @UNKNOWN18
	DEC
	STA __BSS_START__,X
	BNE @UNKNOWN18
	LDA #$0014
	JSL UNKNOWN_C2FAD8
	LDA #$0000
	STA $02
	BRA @UNKNOWN17
@UNKNOWN13:
	LDA $02
	ASL
	TAX
	LDA PSI_ANIMATION_ENEMY_TARGETS,X
	BEQ @UNKNOWN16
	LDA #$0001
	STA $04
	BRA @UNKNOWN15
@UNKNOWN14:
<<<<<<< HEAD
	LDA PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_blue
	STA @LOCAL00
	LDY PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_green
	LDX PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_red
	LDA @VIRTUALTMP01
=======
	LDA UNKNOWN_7E1BD4
	STA $0E
	LDY UNKNOWN_7E1BD2
	LDX UNKNOWN_7E1BD0
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $04
	JSL UNKNOWN_C2FB35
	INC $04
@UNKNOWN15:
	LDA $04
	CMP #$0010
	BCC @UNKNOWN14
@UNKNOWN16:
	INC $02
@UNKNOWN17:
	LDA $02
	CMP #$0004
	BCC @UNKNOWN13
@UNKNOWN18:
	LDX #.LOWORD(PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_frames_left)
	LDA __BSS_START__,X
	BEQ @UNKNOWN22
	DEC
	STA __BSS_START__,X
	BNE @UNKNOWN22
	LDY #$0000
	STY $12
	BRA @UNKNOWN21
@UNKNOWN19:
	TYA
	ASL
	TAX
	LDA PSI_ANIMATION_ENEMY_TARGETS,X
	BEQ @UNKNOWN20
	TYX
	LDA #$0014
	JSL UNKNOWN_C2FADE
@UNKNOWN20:
	LDY $12
	INY
	STY $12
@UNKNOWN21:
	CPY #$0004
	BCC @UNKNOWN19
@UNKNOWN22:
	PLD
	RTL
