
UNKNOWN_C2E9ED: ;$C2E9ED
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	SEP #PROC_FLAGS::ACCUM8
	STZ FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	LDA SWIRL_HDMA_CHANNEL_OFFSET
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0AE34
	LDY #$0000
	TYX
	TYA
	JSL SET_COLDATA
	LDX #$0000
	TXA
	JSL SET_WINDOW_MASK
	RTL
