
<<<<<<< HEAD
UNKNOWN_C2E9C8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
=======
UNKNOWN_C2E9C8: ;$C2E9C8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7EAEC2
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BEQ @UNKNOWN2
	LDA SWIRL_LENGTH_PADDING
	AND #$00FF
	CLC
	SBC #$0004
	BRANCHLTEQS @UNKNOWN2
	LDA #$0001
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA #$0000
@UNKNOWN3:
	RTL
