
UNKNOWN_C2EA15: ;$C2EA15
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAY
	STY $0E
	TYA
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STA ACTIVE_OVAL_WINDOW
	LDX #0
=======
	STA UNKNOWN_7EAEEF
	LDX #$0000
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL UNKNOWN_C4A67E
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #19
	STA SWIRL_MASK_SETTINGS
	LDY @LOCAL00
=======
	LDA #$0013
	STA UNKNOWN_7EAEC8
	LDY $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	TYA
	CMP #$0002
	BEQ @UNKNOWN0
	CMP #$0001
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	MOVE_INT_CONSTANT UNKNOWN_C3F819, LOADED_OVAL_WINDOW
	BRA @UNKNOWN3
@UNKNOWN1:
	MOVE_INT_CONSTANT UNKNOWN_C4A5FA, LOADED_OVAL_WINDOW
	BRA @UNKNOWN3
@UNKNOWN2:
	MOVE_INT_CONSTANT UNKNOWN_C4A5CE, LOADED_OVAL_WINDOW
@UNKNOWN3:
	PLD
	RTL
