
UNKNOWN_C2EAAA: ;$C2EAAA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	SEP #PROC_FLAGS::ACCUM8
	STZ FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	MOVE_INT_CONSTANT NULL, LOADED_OVAL_WINDOW
	LDA #3
=======
	MOVE_INT_CONSTANT NULL, UNKNOWN_7EAECC
	LDA #$0003
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0AE34
	LDX #$0000
	TXA
	JSL SET_WINDOW_MASK
	RTL
