
UNKNOWN_C2EA74: ;$C2EA74
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #$0000
	TXA
	JSL UNKNOWN_C4A67E
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #19
	STA SWIRL_MASK_SETTINGS
=======
	LDA #$0013
	STA UNKNOWN_7EAEC8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LDA ACTIVE_OVAL_WINDOW
	AND #$00FF
	BEQ @UNKNOWN0
	MOVE_INT_CONSTANT UNKNOWN_C4A652, LOADED_OVAL_WINDOW
	BRA @UNKNOWN1
@UNKNOWN0:
	MOVE_INT_CONSTANT UNKNOWN_C4A626, LOADED_OVAL_WINDOW
@UNKNOWN1:
	RTL
