
<<<<<<< HEAD
UNKNOWN_C2EACF:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
=======
UNKNOWN_C2EACF: ;$C2EACF
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7E1B9E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BNE @UNKNOWN0
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	AND #$00FF
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDA #$0001
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA #$0000
@UNKNOWN2:
	RTL
