
<<<<<<< HEAD
UNKNOWN_C2FAD8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	END_C_FUNCTION
=======
UNKNOWN_C2FAD8: ;$C2FAD8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STA UNKNOWN_7EB37C
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
