
UNKNOWN_C2FB35: ;$C2FB35
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 28
	STY $1A
	STX $04
	STX $18
	STA $16
	LDX $2A
	STX $14
	LSR
	LSR
	LSR
	LSR
	ASL
	TAX
<<<<<<< HEAD
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT,X
	LDA @LOCAL04
	ASL
	TAX
	LDA PALETTES + 12 * BPP4PALETTE_SIZE,X
	STA @LOCAL02
=======
	LDA UNKNOWN_7EB37C
	STA UNKNOWN_7EAEF4,X
	LDA $16
	ASL
	TAX
	LDA $0380,X
	STA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$001F
	STA $02
	LDA $12
	LSR
	LSR
	LSR
	LSR
	LSR
	AND #$001F
	TAX
	STX $10
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000A
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	JSL ASR8_UNKNOWN1
	AND #$001F
	STA $0E
	LDA $04
	CMP $02
	BLTEQ @UNKNOWN0
	LDA $16
	OPTIMIZED_MULT $04, 6
	STA $12
	LDA $18
	STA $04
	SEC
	SBC $02
	REP #PROC_FLAGS::INDEX8
<<<<<<< HEAD
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS)
	STA (@LOCAL02),Y
	LDA #1
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS)
	STA (@LOCAL02),Y
=======
	LDY #.LOWORD(UNKNOWN_7EB1FC)
	STA ($12),Y
	LDA #$0001
	LDY #.LOWORD(UNKNOWN_7EAEFC)
	STA ($12),Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA $04
	CMP $02
	BNE @UNKNOWN1
	LDA $16
	OPTIMIZED_MULT $04, 6
	REP #PROC_FLAGS::INDEX8
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS,X
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA $16
	OPTIMIZED_MULT $04, 6
	STA $12
	LDA $18
	STA $04
	LDA $02
	SEC
	SBC $04
	REP #PROC_FLAGS::INDEX8
<<<<<<< HEAD
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS)
	STA (@LOCAL02),Y
	LDA #$FFFF
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS)
	STA (@LOCAL02),Y
=======
	LDY #.LOWORD(UNKNOWN_7EB1FC)
	STA ($12),Y
	LDA #$FFFF
	LDY #.LOWORD(UNKNOWN_7EAEFC)
	STA ($12),Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN2:
	LDX $10
	STX $02
	LDY $1A
	TYA
	CMP $02
	BLTEQ @UNKNOWN3
	LDA $16
	OPTIMIZED_MULT $04, 6
	STA $02
	STX $04
	TYA
	SEC
<<<<<<< HEAD
	SBC @VIRTUAL04
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 2,X
	LDA #32
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
=======
	SBC $04
	LDX $02
	STA UNKNOWN_7EB1FC + 2,X
	LDA #$0020
	LDX $02
	STA UNKNOWN_7EAEFC + 2,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN5
@UNKNOWN3:
	STX $02
	TYA
	CMP $02
	BNE @UNKNOWN4
	LDA $16
	OPTIMIZED_MULT $04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA $16
	OPTIMIZED_MULT $04, 6
	STA $02
	STY $04
	TXA
	SEC
<<<<<<< HEAD
	SBC @VIRTUAL04
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 2,X
	LDA #$FFE0
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
=======
	SBC $04
	LDX $02
	STA UNKNOWN_7EB1FC + 2,X
	LDA #$FFE0
	LDX $02
	STA UNKNOWN_7EAEFC + 2,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN5:
	LDA $14
	CMP $0E
	BLTEQ @UNKNOWN6
	LDA $16
	OPTIMIZED_MULT $04, 6
	TAX
	LDA $14
	SEC
<<<<<<< HEAD
	SBC @LOCAL00
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 4,X
=======
	SBC $0E
	STA UNKNOWN_7EB1FC + 4,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #$0400
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
	BRA @UNKNOWN8
@UNKNOWN6:
	LDA $14
	CMP $0E
	BNE @UNKNOWN7
	LDA $16
	OPTIMIZED_MULT $04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA $16
	OPTIMIZED_MULT $04, 6
	TAX
	LDA $0E
	SEC
<<<<<<< HEAD
	SBC @LOCAL03
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 4,X
=======
	SBC $14
	STA UNKNOWN_7EB1FC + 4,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #$FC00
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
@UNKNOWN8:
	LDA $16
	OPTIMIZED_MULT $04, 6
	TAX
<<<<<<< HEAD
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 4,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 2,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS,X
	END_C_FUNCTION
=======
	STZ UNKNOWN_7EB07C + 4,X
	STZ UNKNOWN_7EB07C + 2,X
	STZ UNKNOWN_7EB07C,X
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
