
UNKNOWN_C2FCA6: ;$C2FCA6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 24
	STA $02
	STA $16
	LDA $02
	LSR
	LSR
	LSR
	LSR
	ASL
	TAX
<<<<<<< HEAD
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT,X
	LDA @VIRTUAL02
	ASL
	TAX
	LDA PALETTES + 12 * BPP4PALETTE_SIZE,X
	STA @LOCAL03
=======
	LDA UNKNOWN_7EB37C
	STA UNKNOWN_7EAEF4,X
	LDA $02
	ASL
	TAX
	LDA $0380,X
	STA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$001F
	TAY
	STY $12
	LDA $14
	LSR
	LSR
	LSR
	LSR
	LSR
	AND #$001F
	STA $04
	STA $10
	SEP #PROC_FLAGS::INDEX8
	LDY #$000A
	LDA $14
	JSL ASR8_UNKNOWN1
	AND #$001F
	STA $0E
	REP #PROC_FLAGS::INDEX8
	LDY $12
	BEQ @UNKNOWN0
	LDA $02
	OPTIMIZED_MULT $04, 6
	TAX
	TYA
	LSR
	LSR
	STA $02
	TYA
	SEC
<<<<<<< HEAD
	SBC @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS,X
=======
	SBC $02
	STA UNKNOWN_7EB1FC,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #$FFFF
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS,X
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA $02
	OPTIMIZED_MULT $04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS,X
@UNKNOWN1:
	LDA $10
	STA $04
	BEQ @UNKNOWN2
	LDA $16
	STA $02
	OPTIMIZED_MULT $04, 6
	TAX
	LDA $10
	STA $04
	LSR
	LSR
	PHA
	LDA $04
	PLY
	STY $04
	SEC
<<<<<<< HEAD
	SBC @VIRTUAL04
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 2,X
=======
	SBC $04
	STA UNKNOWN_7EB1FC + 2,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #$FFE0
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA $16
	STA $02
	OPTIMIZED_MULT $04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
@UNKNOWN3:
	LDA $0E
	BEQ @UNKNOWN4
	LDA $02
	OPTIMIZED_MULT $04, 6
	TAX
	LDA $0E
	LSR
	LSR
	STA $04
	LDA $0E
	SEC
<<<<<<< HEAD
	SBC @VIRTUAL04
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 4,X
=======
	SBC $04
	STA UNKNOWN_7EB1FC + 4,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #$FC00
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA $02
	OPTIMIZED_MULT $04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
@UNKNOWN5:
	LDA $02
	OPTIMIZED_MULT $04, 6
	TAX
<<<<<<< HEAD
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 4,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 2,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS,X
	END_C_FUNCTION
=======
	STZ UNKNOWN_7EB07C + 4,X
	STZ UNKNOWN_7EB07C + 2,X
	STZ UNKNOWN_7EB07C,X
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
