
UNKNOWN_C2FD99: ;$C2FD99
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 26
	LDA #$0000
	STA $04
	STA $18
	JMP @UNKNOWN15
@UNKNOWN0:
	LDA $04
	ASL
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT)
	TAX
	LDA __BSS_START__,X
	BEQL @UNKNOWN14
	DEC
	STA __BSS_START__,X
	LDA $04
	OPTIMIZED_MULT $04, 96
	STA $16
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS) + 6
	TAY
	LDA $16
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS) + 6
	TAX
	STX $14
	LDA $16
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS) + 6
	STA @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, BPP4PALETTE_SIZE
	CLC
	ADC #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 12 + 1 * COLOUR_SIZE
	STA @VIRTUAL02
	LDA #1
	STA @LOCAL01
=======
	ADC #.LOWORD(UNKNOWN_7EB1FC) + 6
	STA $12
	LDA $18
	STA $04
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$0382
	STA $02
	LDA #$0001
	STA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JMP @UNKNOWN12
@UNKNOWN2:
	LDA __BSS_START__,Y
	BEQ @UNKNOWN5
	STX $16
	LDA $12
	TAX
	LDA __BSS_START__,X
	CLC
	ADC ($16)
	STA ($16)
	BRA @UNKNOWN4
@UNKNOWN3:
	STX $16
	LDA $0E
	SEC
<<<<<<< HEAD
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL04)
	LDA @VIRTUAL02
	STA @LOCAL04
=======
	SBC UNKNOWN_7EB37C
	STA ($16)
	LDA $02
	STA $16
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,Y
	CLC
	ADC ($16)
	STA ($16)
@UNKNOWN4:
	LDX $14
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
=======
	STA $0E
	LDA UNKNOWN_7EB37C
	CMP $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BLTEQ @UNKNOWN3
@UNKNOWN5:
	INY
	INY
	INX
	INX
	STX $16
	LDA $12
	INC
	INC
	STA $14
	LDA __BSS_START__,Y
	BEQ @UNKNOWN8
	STX $12
	LDA $14
	TAX
	LDA __BSS_START__,X
	CLC
	ADC ($12)
	STA ($12)
	BRA @UNKNOWN7
@UNKNOWN6:
	STX $12
	LDA $0E
	SEC
<<<<<<< HEAD
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL02)
	LDA @VIRTUAL02
	STA @LOCAL02
=======
	SBC UNKNOWN_7EB37C
	STA ($12)
	LDA $02
	STA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,Y
	CLC
	ADC ($12)
	STA ($12)
@UNKNOWN7:
	LDX $16
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
=======
	STA $0E
	LDA UNKNOWN_7EB37C
	CMP $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BLTEQ @UNKNOWN6
@UNKNOWN8:
	INY
	INY
	INX
	INX
	STX $16
	LDA $14
	INC
	INC
	STA $12
	LDA __BSS_START__,Y
	BEQ @UNKNOWN11
	STX $14
	LDA $12
	TAX
	LDA __BSS_START__,X
	CLC
	ADC ($14)
	STA ($14)
	BRA @UNKNOWN10
@UNKNOWN9:
	STX $14
	LDA $0E
	SEC
<<<<<<< HEAD
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL03)
	LDA @VIRTUAL02
	STA @LOCAL03
=======
	SBC UNKNOWN_7EB37C
	STA ($14)
	LDA $02
	STA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,Y
	CLC
	ADC ($14)
	STA ($14)
@UNKNOWN10:
	LDX $16
	LDA __BSS_START__,X
<<<<<<< HEAD
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
=======
	STA $0E
	LDA UNKNOWN_7EB37C
	CMP $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BLTEQ @UNKNOWN9
@UNKNOWN11:
	INY
	INY
	INX
	INX
	STX $14
	LDA $12
	INC
	INC
	STA $12
	INC $02
	INC $02
	INC $10
@UNKNOWN12:
	LDA $10
	CMP #$0010
	BCCL @UNKNOWN2
	LDA #$0010
	JSL UNKNOWN_C0856B
@UNKNOWN14:
	INC $04
	LDA $04
	STA $18
@UNKNOWN15:
	LDA $04
	CMP #$0004
	BCCL @UNKNOWN0
	PLD
	RTL
