
<<<<<<< HEAD
UNKNOWN_C1004E:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA RENDER_HPPP_WINDOWS
=======
UNKNOWN_C1004E: ;$C1004E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7E89C9
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BEQ @UNKNOWN0
	JSR UNKNOWN_C3E450
@UNKNOWN0:
	LDA BATTLE_MODE_FLAG
	BEQ @UNKNOWN1
	JSL UNKNOWN_C43568
	BRA @UNKNOWN2
@UNKNOWN1:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@UNKNOWN2:
	RTL
