
UNKNOWN_C10004: ;$C10004
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, $06
	JSL UNKNOWN_C0943C
	MOVE_INT $06, $0E
	JSL DISPLAY_TEXT
@UNKNOWN0:
	JSL WINDOW_TICK
<<<<<<< HEAD
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
=======
	LDA UNKNOWN_7EB4A8
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN0
	JSL UNKNOWN_C09451
	PLD
	RTL
