
<<<<<<< HEAD
UNKNOWN_C10D7C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDX #.LOWORD(NUMBER_TEXT_BUFFER) + 6
	LDA #1
	STA @LOCAL01
=======
UNKNOWN_C10D7C: ;$C10D7C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	MOVE_INT $26, $06
	MOVE_INT $06, $14
	LDX #.LOWORD(UNKNOWN_7E895A) + 6
	LDA #$0001
	STA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL MODULUS32
	SEP #PROC_FLAGS::ACCUM8
	LDA $06
	STA __BSS_START__,X
	DEX
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $0E, $0A
	MOVE_INT $14, $06
	JSL DIVISION32S_DIVISOR_POSITIVE
	MOVE_INT $06, $14
	LDA $12
	INC
	STA $12
@UNKNOWN1:
	MOVE_INT_CONSTANT $0000000A, $0A
	MOVE_INT $0A, $0E
	LDA $06
	CMP $0A
	LDA $08
	SBC $0C
	BCS @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA $06
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	PLD
	RTS
