
UNKNOWN_C10D60: ;$C10D60
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSR UNKNOWN_C10BA1
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #1
	STA REDRAW_ALL_WINDOWS
=======
	LDA #$0001
	STA UNKNOWN_7E9623
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	RTS
