
UNKNOWN_C12070: ;$C12070
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	STY $14
	STX $12
	STA $10
	BNE @UNKNOWN0
<<<<<<< HEAD
=======
	LDX NUM_BATTLERS_IN_BACK_ROW
	TXA
	DEC
	CLC
	ADC #.LOWORD(UNKNOWN_7EAD5A)
	STA $04
	BRA @UNKNOWN1
@UNKNOWN0:
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDX NUM_BATTLERS_IN_FRONT_ROW
	TXA
	DEC
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(BATTLER_FRONT_ROW_X_POSITIONS)
	STA @VIRTUAL04
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX NUM_BATTLERS_IN_BACK_ROW
	TXA
	DEC
	CLC
	ADC #.LOWORD(BATTLER_BACK_ROW_X_POSITIONS)
	STA @VIRTUAL04
=======
	ADC #.LOWORD(UNKNOWN_7EAD6A)
	STA $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN1:
	TXA
	DEC
	STA $02
	BRA @UNKNOWN4
@UNKNOWN2:
	LDX $04
	LDA __BSS_START__,X
	AND #$00FF
	STA $0E
	LDA $04
	DEC
	STA $04
	LDA $0E
	CMP $12
	BCS @UNKNOWN3
	LDY $14
	LDX $02
	LDA $10
	JSR UNKNOWN_C11FD4
	CMP #$0000
	BEQ @UNKNOWN3
	LDA $02
	BRA @UNKNOWN5
@UNKNOWN3:
	LDA $02
	DEC
	STA $02
@UNKNOWN4:
	LDA $02
	INC
	BNE @UNKNOWN2
	LDA #$FFFF
@UNKNOWN5:
	PLD
	RTS
