
UNKNOWN_C12CCC: ;$C12CCC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	TAY
<<<<<<< HEAD
	STY @LOCAL01
	LDX #.LOWORD(NUMBER_TEXT_BUFFER)
	LDA #10000
	STA @LOCAL00
=======
	STY $10
	LDX #.LOWORD(UNKNOWN_7E895A)
	LDA #$2710
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	PHA
	LDY $10
	TYA
	PLY
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #$0030
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	PHA
	LDY $10
	TYA
	PLY
	JSL MODULUS16
	TAY
	STY $10
	LDY #$000A
	LDA $0E
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA $0E
@UNKNOWN1:
	CMP #$0000
	BNE @UNKNOWN0
	PLD
	RTS
