
UNKNOWN_C17889: ;$C17889
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	TXA
	CMP #$0001
	BEQ @UNKNOWN0
	CMP #$0002
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	SEP #PROC_FLAGS::ACCUM8
	STZ TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	STZ CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(UNKNOWN_C17796)
	BRA @UNKNOWN3
@UNKNOWN1:
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	SEP #PROC_FLAGS::ACCUM8
	STZ TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	PROMOTENEARPTR TEXT_NEW_MENU_OPTION_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E97D7, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	MOVE_INT_CONSTANT NULL, $12
	JSR UNKNOWN_C113D1
	LDA #NULL
	BRA @UNKNOWN3
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(UNKNOWN_C17889)
@UNKNOWN3:
	PLD
	RTS
