
UNKNOWN_C193E7: ;$C193E7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
<<<<<<< HEAD
	STX @LOCAL01
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
=======
	STX $12
	LDA #.LOWORD(UNKNOWN_7E9C8A)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C20A20
	JSL SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN28
	LOADPTR MISC_TARGET_TEXT, $06
	LDX $12
	TXA
	OPTIMIZED_MULT $04, 10
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA #$000A
	JSR PRINT_STRING
<<<<<<< HEAD
	JSR CLEAR_INSTANT_PRINTING
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
=======
	JSL CLEAR_INSTANT_PRINTING
	LDA #.LOWORD(UNKNOWN_7E9C8A)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C20ABC
	PLD
	RTS
