
<<<<<<< HEAD
UNKNOWN_C19441:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
=======
UNKNOWN_C19441: ;$C19441
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 26
	LDA #$0000
	STA $02
	LDA #.LOWORD(UNKNOWN_7E9C8A)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C20A20
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU_ITEMLIST
	LOADPTR PHONE_CALL_TEXT, $0E
	LDX #.SIZEOF(char_struct::name)
	LDA #$0007
	JSL SET_WINDOW_TITLE
	LDY #$0001
	STY $18
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA $16
	CLC
	ADC #$0019
	CLC
	ADC $06
	STA $06
	LDA [$06]
	JSL GET_EVENT_FLAG
	CMP #$0000
	BEQ @UNKNOWN1
<<<<<<< HEAD
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	LDX #.SIZEOF(telephone_contact::label)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + .SIZEOF(telephone_contact::label)
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	MOVE_INT $0A, $06
	MOVE_INT $06, $0E
	LDX #$0019
	LDA #.LOWORD(UNKNOWN_7E9C9F)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7E9C9F+25
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	MOVE_INT_CONSTANT NULL, $12
	LDY $18
	TYA
	JSR UNKNOWN_C115F4
@UNKNOWN1:
	LDY $18
	INY
	STY $18
@UNKNOWN2:
	LOADPTR TELEPHONE_CONTACTS_TABLE, $06
	TYA
	LDY #$001F
	JSL MULT168
	STA $16
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	BNEL @UNKNOWN0
	LDA #$0000
	JSR UNKNOWN_C12BD5
	CMP #$0000
	BEQ @UNKNOWN4
	LDY #$0001
	LDX #$0000
	TYA
	JSR UNKNOWN_C1180D
	LDA #$0001
	JSR SELECTION_MENU
	STA $02
@UNKNOWN4:
	JSR CLOSE_FOCUS_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20ABC
	LDA $02
	PLD
	RTS
