
<<<<<<< HEAD
UNKNOWN_C19A43:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDY #.LOWORD(TEMPORARY_TEXT_BUFFER) + 12
	STY @LOCAL03
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20A20
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN0D
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_7, @LOCAL00
	LDX #12
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
=======
UNKNOWN_C19A43: ;$C19A43
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 26
	LDY #.LOWORD(UNKNOWN_7E9C9F) + 12
	STY $18
	LDA #.LOWORD(UNKNOWN_7E9C8A)
	JSL UNKNOWN_C20A20
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN0D
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_7, $0E
	LDX #$000C
	LDA #.LOWORD(UNKNOWN_7E9C9F)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0058
	LDY $18
	STA __BSS_START__,Y
	TYX
	INX
	LDA #$0061
	STA __BSS_START__,X
	INX
	LDA #$0059
	STA __BSS_START__,X
	INX
	LDA #$0000
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$FFFF
	LDA #$000D
	JSL SET_WINDOW_TITLE
	LDA #$0000
	STA $02
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX $02
	LDA GAME_STATE+game_state::escargo_express_items,X
	AND #$00FF
	TAY
	STY $16
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
	LDY @LOCAL02
	BEQ @UNKNOWN1
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	STZ UNKNOWN_7E9C9F+.SIZEOF(item::name)
	LDY $16
	BEQ @UNKNOWN1
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	MOVE_INT_CONSTANT NULL, $12
	JSR UNKNOWN_C113D1
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	INC $02
@UNKNOWN2:
	LDA $02
	CMP #$0024
	BCC @UNKNOWN0
	LDY #$0001
	LDX #$0000
	LDA #$0002
	JSR UNKNOWN_C1180D
	LDA #$0001
	JSR SELECTION_MENU
	TAX
	STX $18
	LDA #$000D
	JSL UNKNOWN_EF0115
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20ABC
	LDX $18
	TXA
	PLD
	RTS
