
UNKNOWN_C19F29: ;$C19F29
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 30
	TAX
	DEC
	STA $1C
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN0
<<<<<<< HEAD
	LDA #6
	STA PAGINATION_WINDOW
=======
	LDA #$0006
	STA UNKNOWN_7E5E7A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
=======
	ADC #.LOWORD(CHAR_STRUCT)
	PROMOTENEARPTRA $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #.SIZEOF(char_struct::name)
	LDA #$0006
	JSL SET_WINDOW_TITLE
	LDA #$0000
	STA $02
	STA $1A
	JMP @UNKNOWN14
@UNKNOWN1:
<<<<<<< HEAD
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDA @VIRTUAL02
=======
	LDA #$0001
	STA UNKNOWN_7E5E71
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN4
	CMP #$0001
	BEQ @UNKNOWN5
	CMP #$0002
	BEQL @UNKNOWN6
	CMP #$0003
	BEQL @UNKNOWN7
	JMP @UNKNOWN8
@UNKNOWN4:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, $06
	LDA $02
	OPTIMIZED_MULT $04, 11
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	MOVE_INT_CONSTANT NULL, $12
	LDX $02
	LDA #$0000
	JSR UNKNOWN_C114B1
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA $04
	STA $18
	JMP @UNKNOWN8
@UNKNOWN5:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, $06
	LDA $02
	OPTIMIZED_MULT $04, 11
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	MOVE_INT_CONSTANT NULL, $12
	LDX $02
	LDA #$0000
	JSR UNKNOWN_C114B1
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA $04
	STA $18
	JMP @UNKNOWN8
@UNKNOWN6:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, $06
	LDA $02
	OPTIMIZED_MULT $04, 11
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	MOVE_INT_CONSTANT NULL, $12
	LDX $02
	LDA #$0000
	JSR UNKNOWN_C114B1
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA $04
	STA $18
	BRA @UNKNOWN8
@UNKNOWN7:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, $06
	LDA $02
	OPTIMIZED_MULT $04, 11
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	MOVE_INT_CONSTANT NULL, $12
	LDX $02
	LDA #$0000
	JSR UNKNOWN_C114B1
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA $04
	STA $18
@UNKNOWN8:
	LDA $18
	STA $04
	BEQL @UNKNOWN12
	LDA $04
	DEC
	STA $02
	LDA $1C
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	TAY
	STY $16
	LDX $04
	LDA $1C
	INC
	JSL CHECK_ITEM_EQUIPPED
	CMP #$0000
	BEQ @UNKNOWN10
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #34
	STA TEMPORARY_TEXT_BUFFER
=======
	LDA #$0022
	STA UNKNOWN_7E9C9F
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDY $16
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)+1
	JSL MEMCPY16
	BRA @UNKNOWN11
@UNKNOWN10:
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDY $16
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
@UNKNOWN11:
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
	BRA @UNKNOWN13
@UNKNOWN12:
	.A16
<<<<<<< HEAD
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, @LOCAL00
	LDX #10
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
=======
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, $0E
	LDX #$000A
	LDA #.LOWORD(UNKNOWN_7E9C9F)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+10
@UNKNOWN13:
	REP #PROC_FLAGS::ACCUM8
	LDA $1A
	STA $02
	LDX $02
	LDA #$0006
	JSL UNKNOWN_C438A5
	LDA #$006A
	JSR PRINT_LETTER
	LDA #$0050
	JSR PRINT_LETTER
<<<<<<< HEAD
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA #$0031
	JSR PRINT_STRING
	INC $02
	LDA $02
	STA $1A
@UNKNOWN14:
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC $02
	JUMPGTS @UNKNOWN1
	JSR PRINT_MENU_ITEMS
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	JSL CLEAR_INSTANT_PRINTING
	PLD
	RTS
