
UNKNOWN_C19F29: ;$C19F29
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 30
	TAX
	DEC
	STA $02
	STA $1C
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN0
<<<<<<< HEAD
	LDA #6
	STA PAGINATION_WINDOW
=======
	LDA #$0006
	STA UNKNOWN_7E5E7A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	LDA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
=======
	ADC #.LOWORD(CHAR_STRUCT)
	PROMOTENEARPTRA $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #.SIZEOF(char_struct::name)
	LDA #$0006
	JSL SET_WINDOW_TITLE
	LDY #$0000
	STY $1A
	JMP @UNKNOWN14
@UNKNOWN1:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, $06
	TYA
	OPTIMIZED_MULT $04, 4
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	MOVE_INT_CONSTANT NULL, $12
	TYX
	LDA #$0000
	JSR UNKNOWN_C114B1
	LDY $1A
	TYA
	BEQ @UNKNOWN4
	CMP #$0001
	BEQ @UNKNOWN5
	CMP #$0002
	BEQ @UNKNOWN6
	CMP #$0003
	BEQ @UNKNOWN7
	BRA @UNKNOWN8
@UNKNOWN4:
	LDA $1C
	STA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA $04
	STA $18
	BRA @UNKNOWN8
@UNKNOWN5:
	LDA $1C
	STA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA $04
	STA $18
	BRA @UNKNOWN8
@UNKNOWN6:
	LDA $1C
	STA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA $04
	STA $18
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA $1C
	STA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA $04
	STA $18
@UNKNOWN8:
	LDA $18
	STA $04
	BEQL @UNKNOWN12
	LDA $04
	DEC
	PHA
	LDA $1C
	STA $02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY $02
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA $16
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDA $16
	OPTIMIZED_MULT $04, .SIZEOF(item)
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + 10
	REP #PROC_FLAGS::ACCUM8
	LDA $18
	STA $04
	LDX $04
	LDA $1C
	STA $02
	INC
	JSL $C3E560
	CMP #$0000
	BEQ @UNKNOWN13
<<<<<<< HEAD
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	JSL STRLEN
	TAX
@UNKNOWN11:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$22
	STA TEMPORARY_TEXT_BUFFER,X
	STZ TEMPORARY_TEXT_BUFFER + 1,X
	BRA @UNKNOWN13
@UNKNOWN12:
	.A16
<<<<<<< HEAD
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, @LOCAL00
	LDX #4
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
=======
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, $0E
	LDX #$0004
	LDA #.LOWORD(UNKNOWN_7E9C9F)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+4
@UNKNOWN13:
	LDY $1A
	TYX
	REP #PROC_FLAGS::ACCUM8
	LDA #$0004
	JSR UNKNOWN_C438A5
	LDA #$005B
	JSR PRINT_LETTER
<<<<<<< HEAD
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA #$000A
	JSR PRINT_STRING
	LDY $1A
	INY
	STY $1A
@UNKNOWN14:
	STY $02
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC $02
	JUMPGTS @UNKNOWN1
	JSR PRINT_MENU_ITEMS
	JSR CLEAR_INSTANT_PRINTING
	PLD
	RTS
