
<<<<<<< HEAD
UNKNOWN_C1AA5D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
=======
UNKNOWN_C1AA5D: ;$C1AA5D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA #.LOWORD(UNKNOWN_7E9C8A)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C20A20
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX $16
@UNKNOWN0:
	LDX $16
	TXA
	JSL UNKNOWN_C1A778
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN2
	LDA #$0000
	JSR UNKNOWN_C193E7
	LOADPTR UNKNOWN_C1A778, $0E
	MOVE_INT_CONSTANT NULL, $12
	LDX #$0001
	LDA #$0000
	JSR CHAR_SELECT_PROMPT
	TAX
	STX $16
	JSR UNKNOWN_C19437
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX $16
	LDA #$0000
	JSR UNKNOWN_C43573
@UNKNOWN3:
	LDX $16
	BEQ @UNKNOWN4
	TXA
	JSR UNKNOWN_C1A795
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN0
@UNKNOWN4:
	LDA #$002D
	JSR CLOSE_WINDOW
	LDA #$0006
	JSR CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20ABC
	LDX $16
	TXA
	PLD
	RTS
