
<<<<<<< HEAD
UNKNOWN_C1ACA1:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL03
	STA @LOCAL02
	PROMOTENEARPTR BATTLE_TARGET_NAME, @VIRTUAL06
=======
UNKNOWN_C1ACA1: ;$C1ACA1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 26
	STX $18
	STA $16
	PROMOTENEARPTR UNKNOWN_7E9CF5, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA $16
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	TXA
	JSL MEMCPY24
	LDX $18
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_TARGET_NAME,X
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
.IF .DEFINED(USA)
	LDA #.LOWORD(-1)
	STA TARGET_ENEMY_ID
.ENDIF
	END_C_FUNCTION
=======
	LDA #$FFFF
	STA UNKNOWN_7E965A
	PLD
	RTS
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
