
UNKNOWN_C1AD42: ;$C1AD42
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
	JSL FIND_NEARBY_CHECKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQ @UNKNOWN0
<<<<<<< HEAD
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN0
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-2)
=======
	LDA CURRENT_TPT_ENTRY
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDA CURRENT_TPT_ENTRY
	CMP #$FFFE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	BRA @UNKNOWN2
@UNKNOWN1:
<<<<<<< HEAD
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
=======
	LDA CURRENT_TPT_ENTRY
	OPTIMIZED_MULT @VIRTUAL04, 17
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:NPC_CONFIG_TABLE,X
@UNKNOWN2:
	PLD
	RTS
