
UNKNOWN_C1BB06: ;$C1BB06
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
<<<<<<< HEAD
	STX @LOCAL01
.IF .DEFINED(USA)
	LDA LAST_SELECTED_PSI_DESCRIPTION
=======
	STX $12
	LDA UNKNOWN_7E9D19
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CMP #$00FF
	BEQ @UNKNOWN0
	CPX LAST_SELECTED_PSI_DESCRIPTION
	BEQ @UNKNOWN1
@UNKNOWN0:
	TXA
	JSL UNKNOWN_C1C8BC
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN2F
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
<<<<<<< HEAD
	LDX @LOCAL01
	STX LAST_SELECTED_PSI_DESCRIPTION
.ENDIF
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL0A
.IF !.DEFINED(USA)
	LDX @LOCAL01
.ENDIF
=======
	LDX $12
	STX UNKNOWN_7E9D19
	LOADPTR PSI_ABILITY_TABLE, $0A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	OPTIMIZED_MULT $04, 15
	CLC
	ADC #$000B
	CLC
	ADC $0A
	STA $0A
	DEREFERENCE_PTR_TO $0A, $06
	MOVE_INT $06, $0E
	JSL DISPLAY_TEXT
	JSL CLEAR_INSTANT_PRINTING
@UNKNOWN1:
	PLD
	RTL
