
UNKNOWN_C1EC8F: ;$C1EC8F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
	STX $12
	LDA #.LOWORD(GAME_STATE)+game_state::text_flavour
	STA $02
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $00
	LDX $12
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA __BSS_START__,X
	JSL LOAD_WINDOW_GFX
	.A16
<<<<<<< HEAD
	COPY_TO_VRAM3 BUFFER, VRAM::TEXT_LAYER_TILES, $3800, 0
	JSL UNKNOWN_C47F87
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDA @VIRTUAL00
	LDX @VIRTUAL02
=======
	COPY_TO_VRAM3 UNKNOWN_7F0000, $6000, $3800, $00
	JSL UNKNOWN_C47F87
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0018
	STA UNKNOWN_7E0030
	LDA $00
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
