
<<<<<<< HEAD
UNKNOWN_C1FF6B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
.IF .DEFINED(USA)
	STZ ENABLE_WORD_WRAP
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA ALLOW_TEXT_OVERFLOW
.ENDIF
=======
UNKNOWN_C1FF6B: ;$C1FF6B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STZ UNKNOWN_7E5E6E
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7EB49D
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSR FILE_MENU_LOOP
	JSL CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	.A16
<<<<<<< HEAD
	STZ DISABLED_TRANSITIONS
	STZ LAST_PARTY_MEMBER_STATUS_LAST_CHECK
.IF .DEFINED(USA)
	LDA #<-1
	STA ENABLE_WORD_WRAP
=======
	STZ UNKNOWN_7EB4B6
	STZ UNKNOWN_7EB4A2
	LDA #$00FF
	STA UNKNOWN_7E5E6E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	STZ ALLOW_TEXT_OVERFLOW
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	RTL
