
UNKNOWN_C1FF99: ;$C1FF99
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TXY
	STY $12
	TAX
	MOVE_INT $22, $06
	MOVE_INT $06, $0E
	TXA
	JSL UNKNOWN_C43E31
	STA $02
	LDY $12
	TYA
	ASL
	ASL
	ASL
	SEC
	SBC $02
	LSR
	STA VWF_X
	LSR
	LSR
	LSR
<<<<<<< HEAD
	STA VWF_TILE
	END_C_FUNCTION
=======
	STA UNKNOWN_7E9E25
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
