
INITIALIZE_SPC700: ;$C4FB58
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA #$FFFF
	STA CURRENT_SEQUENCE_PACK
	STA CURRENT_PRIMARY_SAMPLE_PACK
	LDA f:MUSIC_DATASET_TABLE + (0 * .SIZEOF(pack_table_entry)) + pack_table_entry::sequence_pack
	AND #$00FF
	STA $10
	STA UNKNOWN_7EB543
	STA CURRENT_SECONDARY_SAMPLE_PACK
	LOADPTR MUSIC_PACK_POINTER_TABLE, $06
	LDA $10
	OPTIMIZED_MULT $04, .SIZEOF(music_pack_pointer)
	TAY
	STY $0E
	TYA
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A] ;music_pack_pointer::bank
	AND #$00FF
	JSR UNKNOWN_C4FB42
	TAX
	LDY $0E
	TYA
	INC
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06] ;music_pack_pointer::addr
	AND SEQUENCE_PACK_MASK
	JSL LOAD_SPC700_DATA
	LDA #$0001
	STA ENABLE_AUTO_SECTOR_MUSIC_CHANGES
	END_C_FUNCTION
=======
	ADC $06
	STA $06
	LDA [$06] ;music_pack_pointer::addr
	AND UNKNOWN_7EB547
	JSL LOAD_SPC700_DATA
	LDA #$0001
	STA SECTOR_BOUNDARY_BEHAVIOUR_FLAG
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
