
<<<<<<< HEAD
UNKNOWN_C005E7:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT f:MAP_PALETTE_PTR_TABLE+4, @VIRTUAL06
	LDY #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	STY @LOCAL01
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
=======
UNKNOWN_C005E7: ;$C005E7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA f:MAP_PALETTE_PTR_TABLE+4
	STA $06
	LDA f:MAP_PALETTE_PTR_TABLE+6
	STA $08
	LDY #.LOWORD(CUR_MAP_PAL)
	STY $12
	MOVE_INT $06, $0E
	LDX #$00C0
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	JSL MEMCPY16
	LDY $12
	TYA
	JSR GET_COLOUR_AVERAGE
<<<<<<< HEAD
	LDA COLOUR_AVERAGE_RED
	STA SAVED_COLOUR_AVERAGE_RED
	LDA COLOUR_AVERAGE_GREEN
	STA SAVED_COLOUR_AVERAGE_GREEN
	LDA COLOUR_AVERAGE_BLUE
	STA SAVED_COLOUR_AVERAGE_BLUE
	END_C_FUNCTION
=======
	LDA UNKNOWN_7E43D0
	STA UNKNOWN_7E43D6
	LDA UNKNOWN_7E43D2
	STA UNKNOWN_7E43D8
	LDA UNKNOWN_7E43D4
	STA UNKNOWN_7E43DA
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
