
UNKNOWN_C01731: ;$C01731
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $04
	TAY
	STY $10
	STY BG2_X_POS
	STY BG1_X_POS
	LDA $04
	STA BG2_Y_POS
	LDA $04
	STA BG1_Y_POS
	TYA
	AND #$8000
	BEQ @UNKNOWN0
	TYA
	LSR
	LSR
	LSR
	ORA #$E000
	STA $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	TYA
	LSR
	LSR
	LSR
	STA $0E
@UNKNOWN1:
	LDA $04
	AND #$8000
	BEQ @UNKNOWN2
	LDA $04
	LSR
	LSR
	LSR
	ORA #$E000
	STA $02
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA $04
	LSR
	LSR
	LSR
	STA $02
	BRA @UNKNOWN5
@UNKNOWN3:
	AND #$8000
	BEQ @UNKNOWN4
	LDA SCREEN_LEFT_X
	INC
<<<<<<< HEAD
	STA SCREEN_LEFT_X
	LDX @VIRTUAL02
=======
	STA UNKNOWN_7E4374
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #$0020
	JSR UNKNOWN_C0122A
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA SCREEN_LEFT_X
	DEC
<<<<<<< HEAD
	STA SCREEN_LEFT_X
	LDX @VIRTUAL02
=======
	STA UNKNOWN_7E4374
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	DEC
	JSR UNKNOWN_C0122A
@UNKNOWN5:
	LDA SCREEN_LEFT_X
	SEC
	SBC $0E
	BNE @UNKNOWN3
	BRA @UNKNOWN8
@UNKNOWN6:
	AND #$8000
	BEQ @UNKNOWN7
	LDA SCREEN_TOP_Y
	INC
	STA SCREEN_TOP_Y
	CLC
	ADC #$001C
	TAX
	LDA $0E
	JSR UNKNOWN_C01181
	BRA @UNKNOWN8
@UNKNOWN7:
	LDX SCREEN_TOP_Y
	DEX
	STX SCREEN_TOP_Y
	DEX
	LDA $0E
	JSR UNKNOWN_C01181
@UNKNOWN8:
	LDA SCREEN_TOP_Y
	SEC
	SBC $02
	BNE @UNKNOWN6
<<<<<<< HEAD
	LDY @LOCAL01
	STY BG12_POSITION_X_COPY
	LDA @VIRTUAL04
	STA BG12_POSITION_Y_COPY
	END_C_FUNCTION
=======
	LDY $10
	STY UNKNOWN_7E4386
	LDA $04
	STA UNKNOWN_7E4388
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
