
UNKNOWN_C020F1: ;$C020F1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CURRENT_ENTITY_SLOT
	STA $02
	ASL
	TAY
	STY $0E
	LDA ENTITY_SPRITEMAP_POINTER_LOW,Y
	JSL UNKNOWN_C01B15
	LDX #$0000
	LDA $02
	JSL ALLOC_SPRITE_MEM
<<<<<<< HEAD
	LDY @LOCAL00
	LDA ENTITY_NPC_IDS,Y
=======
	LDY $0E
	LDA ENTITY_TPT_ENTRIES,Y
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$F000
	CMP #$8000
	BNE @UNKNOWN0
	DEC OVERWORLD_ENEMY_COUNT
@UNKNOWN0:
	LDA $02
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @UNKNOWN1
	STZ MAGIC_BUTTERFLY_SPAWNED
@UNKNOWN1:
	LDA $02
	ASL
	TAX
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA ENTITY_SPRITE_IDS,X
	STA ENTITY_NPC_IDS,X
	END_C_FUNCTION
=======
	LDA #$FFFF
	STA ENTITY_TPT_ENTRY_SPRITES,X
	STA ENTITY_TPT_ENTRIES,X
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
