
<<<<<<< HEAD
UNKNOWN_C021E6:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ MAGIC_BUTTERFLY_SPAWNED
	STZ ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
=======
UNKNOWN_C021E6: ;$C021E6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	STZ MAGIC_BUTTERFLY
	STZ UNKNOWN_7E4A68
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STZ OVERWORLD_ENEMY_COUNT
	LDX #$0000
	STX $0E
	BRA @UNKNOWN2
@UNKNOWN0:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	INC
	CMP #$0002
	BLTEQ @UNKNOWN1
	LDX $0E
	CPX #$0017
	BEQ @UNKNOWN1
	TXA
	JSL UNKNOWN_C02140
@UNKNOWN1:
	LDX $0E
	INX
	STX $0E
@UNKNOWN2:
	CPX #$001E
	BNE @UNKNOWN0
	LDA #$0017
	JSL UNKNOWN_C09C35
	PLD
	RTL
