
<<<<<<< HEAD
UNKNOWN_C03A94:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	STACK_RESERVE_INT16 "LOCAL09"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@LOCAL07ALT := @LOCALM2
	@LOCAL08ALT := @LOCAL07
.ELSE
	@LOCAL07ALT := @LOCAL07
	@LOCAL08ALT := @LOCAL08
.ENDIF
	STA @LOCAL09
	LDA CURRENT_TELEPORT_DESTINATION_X
	ORA CURRENT_TELEPORT_DESTINATION_Y
	BEQ @UNKNOWN0
	LDA CURRENT_TELEPORT_DESTINATION_X
	OPTIMIZED_MULT @VIRTUAL04, 8
	STA @LOCAL08
	LDA CURRENT_TELEPORT_DESTINATION_Y
	OPTIMIZED_MULT @VIRTUAL04, 8
=======
UNKNOWN_C03A94: ;$C03A94
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 32
	STA $1E
	LDA UNKNOWN_7E438A
	ORA UNKNOWN_7E438C
	BEQ @UNKNOWN0
	LDA UNKNOWN_7E438A
	ASL
	ASL
	ASL
	STA $1C
	LDA UNKNOWN_7E438C
	ASL
	ASL
	ASL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAX
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA GAME_STATE+game_state::leader_x_coord
	STA $1C
	LDX GAME_STATE+game_state::leader_y_coord
@UNKNOWN1:
	LDA $1C
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	STA $1A
	STA GAME_STATE+game_state::unknown92
	ASL
	STA FOOTSTEP_SOUND_ID
	STZ FOOTSTEP_SOUND_ID_OVERRIDE
	LDA $1A
	CMP #$0003
	BEQ @UNKNOWN2
	STZ GAME_STATE+game_state::walking_style
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA #WALKING_STYLE::SLOWEST
	STA GAME_STATE+game_state::walking_style
@UNKNOWN3:
	LDA CURRENT_ENTITY_SLOT
	STA $18
	LDA #$FFFF
	STA CURRENT_ENTITY_SLOT
	STZ $16
	JMP @UNKNOWN9
@UNKNOWN4:
	LDY #.LOWORD(GAME_STATE) + game_state::unknown96
	LDA ($16),Y
	AND #$00FF
	TAX
	BEQL @UNKNOWN8
	TXA
	DEC
	STA $04
	LDA $16
	ASL
	TAY
	LDA GAME_STATE + game_state::unknownA2,Y
	STA $02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA NEW_ENTITY_VAR0
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	STA NEW_ENTITY_VAR1
	STY NEW_ENTITY_VAR5
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	STA $14
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	STA $1A
	LDA $02
	JSL UNKNOWN_C02140
<<<<<<< HEAD
	LDA @VIRTUAL02
	STA MOVING_PARTY_MEMBER_ENTITY_ID
=======
	LDA $02
	STA UNKNOWN_7E9F73
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA GAME_STATE+game_state::unknown92
	CMP #$0003
	BEQ @UNKNOWN6
	LDA $16
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #$0000
	LDA $04
	JSL UNKNOWN_C0780F
	STA $1C
	LDA GAME_STATE+game_state::leader_x_coord
	STA $0E
	LDA GAME_STATE+game_state::leader_y_coord
	STA $10
	LDY $02
	LDA $04
	OPTIMIZED_MULT $04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA $1C
	JSL CREATE_ENTITY
	STA $12
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA $16
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #$000A
	LDA $04
	JSL UNKNOWN_C0780F
	STA $1C
	LDA GAME_STATE+game_state::leader_x_coord
	STA $0E
	LDA GAME_STATE+game_state::leader_y_coord
	STA $10
	LDY $02
	LDA $04
	OPTIMIZED_MULT $04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA $1C
	JSL CREATE_ENTITY
	STA $12
@UNKNOWN7:
	ASL
	TAX
	LDA $14
	STA ENTITY_SPRITEMAP_POINTER_HIGH,X
	LDA $1A
	STA ENTITY_TICK_CALLBACK_HIGH,X
	LDA $1E
	STA ENTITY_DIRECTIONS,X
	STZ ENTITY_ANIMATION_FRAME,X
	LDA $12
	JSL UNKNOWN_C0A780
@UNKNOWN8:
	INC $16
@UNKNOWN9:
	LDA $16
	CMP #$0006
	BCCL @UNKNOWN4
	LDA $18
	STA CURRENT_ENTITY_SLOT
	JSL UNKNOWN_C039E5
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDA PENDING_INTERACTIONS
	STA @VIRTUAL02
	STZ PENDING_INTERACTIONS
	LDA #4
	STA @LOCAL00
=======
	LDA #$FFFF
	STA UNKNOWN_7E5DA8
	LDA UNKNOWN_7E5D9A
	STA $02
	STZ UNKNOWN_7E5D9A
	LDA #$0004
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C05B7B
<<<<<<< HEAD
	LDA @VIRTUAL02
	STA PENDING_INTERACTIONS
	LDA LADDER_STAIRS_TILE_X
	CMP #.LOWORD(-1)
=======
	LDA $02
	STA UNKNOWN_7E5D9A
	LDA UNKNOWN_7E5DA8
	CMP #$FFFF
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN11
	LDX LADDER_STAIRS_TILE_Y
	LDA LADDER_STAIRS_TILE_X
	JSL UNKNOWN_C07526
@UNKNOWN11:
	PLD
	RTL
