
UNKNOWN_C03FA9: ;$C03FA9
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STY $02
	STA $0E
	STA GAME_STATE+game_state::leader_x_coord
	STX GAME_STATE+game_state::leader_y_coord
	LDA $02
	STA GAME_STATE+game_state::leader_direction
	LDY GAME_STATE+game_state::current_party_members
	LDA $0E
	JSL UNKNOWN_C05F33
	STA GAME_STATE+game_state::trodden_tile_type
	LDA $02
	JSL UNKNOWN_C03A94
	JSL UNKNOWN_C03F1E
	LDA #$0000
	STA $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	TAX
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA ENTITY_ANIMATION_FINGERPRINTS + 24 * 2,X
	LDA @LOCAL00
=======
	LDA #$FFFF
	STA UNKNOWN_7E3456 + 24 * 2,X
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC
	STA $0E
@UNKNOWN1:
	CMP #$0006
	BCC @UNKNOWN0
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA MINI_GHOST_ENTITY_ID
	STZ CURRENT_TELEPORT_DESTINATION_Y
	STZ CURRENT_TELEPORT_DESTINATION_X
=======
	LDA #$FFFF
	STA UNKNOWN_7E9F6B
	STZ UNKNOWN_7E438C
	STZ UNKNOWN_7E438A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA f:NESS_PAJAMA_FLAG
	JSL GET_EVENT_FLAG
	STA PAJAMA_FLAG
	JSL UNKNOWN_C07B52
	PLD
	RTL
