
UNKNOWN_C048D3: ;$C048D3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 32
	TAX
	STX $1E
	LDA GAME_STATE+game_state::walking_style
	JSL MAP_INPUT_TO_DIRECTION
	TAY
	STY $1C
	STY $02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN1
	LDX BATTLE_SWIRL_COUNTDOWN
	DEX
	STX BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN0
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @UNKNOWN9
@UNKNOWN0:
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA BATTLE_MODE
=======
	LDA #$FFFF
	STA BATTLE_DEBUG
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JMP @UNKNOWN9
@UNKNOWN1:
	LDA PAD_PRESS
	AND #PAD::R_BUTTON
	BEQ @UNKNOWN2
	LDA #SFX::BICYCLE_BELL
	JSL PLAY_SOUND
@UNKNOWN2:
	LDY $1C
	CPY #$FFFF
	BNE @UNKNOWN4
	LDX $1E
	BEQ @UNKNOWN3
	LDY GAME_STATE+game_state::leader_direction
	STY $1C
	BRA @UNKNOWN4
@UNKNOWN3:
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @UNKNOWN9
@UNKNOWN4:
	TYA
	AND #$0001
	BEQ @UNKNOWN5
<<<<<<< HEAD
	LDA #4
	STA BICYCLE_DIAGONAL_TURN_COUNTER
=======
	LDA #$0004
	STA UNKNOWN_7E5D5A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN7
@UNKNOWN5:
	LDA BICYCLE_DIAGONAL_TURN_COUNTER
	BEQ @UNKNOWN7
	LDX BICYCLE_DIAGONAL_TURN_COUNTER
	DEX
	STX BICYCLE_DIAGONAL_TURN_COUNTER
	BEQ @UNKNOWN6
	LDY GAME_STATE+game_state::leader_direction
	STY $1C
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA $02
	CMP #$FFFF
	BNE @UNKNOWN7
	LDY GAME_STATE+game_state::leader_direction
	STY $1C
@UNKNOWN7:
	STY GAME_STATE+game_state::leader_direction
	LDA #.LOWORD(GAME_STATE) + game_state::unknown80
	STA $1A
	TYA
	ASL
	ASL
	STA $18
	CLC
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS)
	CLC
	ADC #96
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $0A
	LDY $1A
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $10
	LDA #.LOWORD(GAME_STATE) + game_state::unknown84
	STA $04
	LDA $18
	CLC
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS)
	CLC
	ADC #96
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $0A
	LDY $04
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CLC
<<<<<<< HEAD
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDY @LOCAL05
	STY @LOCAL00
	LDY #24
	LDX @LOCAL02 + fixed_point::integer
	LDA @LOCAL01 + fixed_point::integer
=======
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $14
	LDA #$FFFF
	STA UNKNOWN_7E5DA8
	LDY $1C
	STY $0E
	LDY #$0018
	LDX $16
	LDA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C05CD7
	STA $02
	LDY GAME_STATE + game_state::current_party_members
	LDX $16
	LDA $12
	JSL NPC_COLLISION_CHECK
	LDA ENTITY_COLLIDED_OBJECTS + 46
	CMP #ENTITY_COLLISION_NO_OBJECT
	BNE @UNKNOWN9
	LDX #.LOWORD(GAME_STATE) + game_state::unknown90
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
<<<<<<< HEAD
	INC PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	LDA @VIRTUAL02
=======
	INC UNKNOWN_7E2890
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00C0
	BEQ @UNKNOWN8
	LDA #$0000
	STA __BSS_START__,X
	BRA @UNKNOWN9
@UNKNOWN8:
	MOVE_INT $10, $06
	LDY $1A
	MOVE_INT_YPTRDEST $06, __BSS_START__
	MOVE_INT $14, $06
	LDY $04
	MOVE_INT_YPTRDEST $06, __BSS_START__
@UNKNOWN9:
	PLD
	RTS
