
<<<<<<< HEAD
UNKNOWN_C04AAD:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CAMERA_MODE_3_FRAMES_LEFT
=======
UNKNOWN_C04AAD: ;$C04AAD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDX UNKNOWN_7E5D7C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	DEX
	STX CAMERA_MODE_3_FRAMES_LEFT
	BEQL @UNKNOWN5
	LDA GAME_STATE+game_state::walking_style
	JSL MAP_INPUT_TO_DIRECTION
	STA $04
	STA $10
	LDA $04
	CMP #$FFFF
	BEQL @UNKNOWN6
	LDA #$0018
	STA $02
	BRA @UNKNOWN4
@UNKNOWN2:
	LDA $02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #$FFFF
	BEQ @UNKNOWN3
	TXA
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAY
	STY $0E
	LDA $10
	STA $04
	LDA __BSS_START__,Y
	CMP $04
	BEQ @UNKNOWN3
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	STX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,X
	OPTIMIZED_MULT $04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	LDA a:player_position_buffer_entry::walking_style,X
	CMP #WALKING_STYLE::ROPE
	BEQ @UNKNOWN3
	CMP #WALKING_STYLE::LADDER
	BEQ @UNKNOWN3
	LDA $10
	STA $04
	LDY $0E
	STA __BSS_START__,Y
	LDA $02
	JSL UNKNOWN_C0A780
@UNKNOWN3:
	INC $02
@UNKNOWN4:
	LDA $02
	CMP #$001D
	BLTEQ @UNKNOWN2
	LDA $10
	STA $04
	STA GAME_STATE+game_state::leader_direction
	BRA @UNKNOWN6
@UNKNOWN5:
	JSL UNKNOWN_C04A7B
@UNKNOWN6:
	PLD
	RTS
