
UNKNOWN_C04F60: ;$C04F60
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN0
<<<<<<< HEAD
	LDA PALETTES
	STA BACKGROUND_COLOUR_BACKUP
	LDA #RGBVAL 31, 0, 0
	STA PALETTES
=======
	LDA CUR_TEXT_PAL
	STA UNKNOWN_7E5D72
	LDA #$001F
	STA CUR_TEXT_PAL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	STZ TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #$0008
	JSL UNKNOWN_C0856B
	LOADPTR UNKNOWN_C04F47, $0E
	LDA #$0001
	JSL SCHEDULE_OVERWORLD_TASK
@UNKNOWN0:
	PLD
	RTS
