
UNKNOWN_C054C9: ;$C054C9
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $10
	STA $0E
	AND #$003F
	STA $02
	TXA
	AND #$003F
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	TAX
	LDA LOADED_COLLISION_TILES,X
	AND #$00FF
	TAY
	AND #$0010
	BEQ @UNKNOWN0
<<<<<<< HEAD
	LDA @LOCAL00
	STA LADDER_STAIRS_TILE_X
	LDX @LOCAL01
	STX LADDER_STAIRS_TILE_Y
=======
	LDA $0E
	STA UNKNOWN_7E5DA8
	LDX $10
	STX UNKNOWN_7E5DAA
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	TYA
	PLD
	RTS
