
UNKNOWN_C05B4E: ;$C05B4E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
<<<<<<< HEAD
	STX @LOCAL00
	STZ TEMP_ENTITY_SURFACE_FLAGS
	INC SET_TEMP_ENTITY_SURFACE_FLAGS
=======
	STX $0E
	STZ UNKNOWN_7E5DA4
	INC UNKNOWN_7E5DB4
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	LSR
	ASL
	TAX
	LDA f:UNKNOWN_C200D1,X
	JSR UNKNOWN_C05769
	CMP #$0000
	BEQ @UNKNOWN0
	LDA #$FF00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX $0E
	TXA
@UNKNOWN1:
	PLD
	RTS
