
UNKNOWN_C05D8B: ;$C05D8B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STY $12
	STX $10
	STA $0E
	TYA
	ASL
	STA $02
	LDX $02
	LDA $0E
	SEC
	SBC f:UNKNOWN_C42A1F,X
<<<<<<< HEAD
	STA @LOCAL00
	STA CHECKED_COLLISION_LEFT_X
	LDX @LOCAL01
=======
	STA $0E
	STA UNKNOWN_7E5DAC
	LDX $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	LDX $02
	SEC
	SBC f:UNKNOWN_C42A41,X
	LDX $02
	CLC
	ADC f:UNKNOWN_C42AEB,X
	STA CHECKED_COLLISION_TOP_Y
	TYX
	LDA $0E
	JSR UNKNOWN_C05503
	LDY $12
	TYX
	LDA CHECKED_COLLISION_LEFT_X
	JSR UNKNOWN_C0559C
	LDY $12
	TYX
	LDA CHECKED_COLLISION_TOP_Y
	JSR UNKNOWN_C05639
	LDY $12
	TYX
	LDA CHECKED_COLLISION_TOP_Y
	JSR UNKNOWN_C056D0
<<<<<<< HEAD
	LDA TEMP_ENTITY_SURFACE_FLAGS
	END_C_FUNCTION
=======
	LDA UNKNOWN_7E5DA4
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
