
<<<<<<< HEAD
UNKNOWN_C05F82:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL02
	STA @LOCAL01
	STZ TEMP_ENTITY_SURFACE_FLAGS
=======
UNKNOWN_C05F82: ;$C05F82
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STX $12
	STA $10
	STZ UNKNOWN_7E5DA4
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	ASL
	TAX
	LDY ENTITY_SIZES,X
	STY $0E
	TYA
	ASL
	STA $02
	LDX $12
	TXA
	LDX $02
	SEC
	SBC f:UNKNOWN_C42A41,X
	LDX $02
	CLC
	ADC f:UNKNOWN_C42AEB,X
<<<<<<< HEAD
	STA CHECKED_COLLISION_TOP_Y
	LDX @VIRTUAL02
	LDA @LOCAL01
=======
	STA UNKNOWN_7E5DAE
	LDX $02
	LDA $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEC
	SBC f:UNKNOWN_C42A1F,X
	STA CHECKED_COLLISION_LEFT_X
	TYX
	JSR UNKNOWN_C05503
	LDY $0E
	TYX
	LDA CHECKED_COLLISION_LEFT_X
	JSR UNKNOWN_C0559C
<<<<<<< HEAD
	LDA TEMP_ENTITY_SURFACE_FLAGS
	END_C_FUNCTION
=======
	LDA UNKNOWN_7E5DA4
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
