
UNKNOWN_C064E3: ;$C064E3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	MOVE_INT $1E, $06
	LDA $0E
	CMP CURRENT_QUEUED_INTERACTION_TYPE
	BEQ @UNKNOWN0
	LDA NEXT_QUEUED_INTERACTION
	OPTIMIZED_MULT $04, .SIZEOF(queued_interaction)
	TAX
	LDA $0E
	STA QUEUED_INTERACTIONS + queued_interaction::type,X
	LDA NEXT_QUEUED_INTERACTION
	OPTIMIZED_MULT $04, .SIZEOF(queued_interaction)
	CLC
	ADC #.LOWORD(QUEUED_INTERACTIONS) + queued_interaction::text_ptr
	TAY
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA NEXT_QUEUED_INTERACTION
	INC
	AND #$0003
	STA NEXT_QUEUED_INTERACTION
<<<<<<< HEAD
	LDA #1
	STA PENDING_INTERACTIONS
=======
	LDA #$0001
	STA UNKNOWN_7E5D9A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	PLD
	RTL
