
<<<<<<< HEAD
UNKNOWN_C068F4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA DISABLE_MUSIC_CHANGES
=======
UNKNOWN_C068F4: ;$C068F4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $10
	LDA UNKNOWN_7E5DD8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNEL @UNKNOWN4
	LDA $10
	XBA
	AND #$00FF
	STA $02
	LDY #MAP_WIDTH_TILES
	TXA
	JSL DIVISION16S_DIVISOR_POSITIVE
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	TAX
	LDA f:MAP_DATA_PER_SECTOR_MUSIC,X
	AND #$00FF
	STA $10
	LOADPTR DOOR_DATA&$FF0000, $0A
	LDA $10
	ASL
	TAX
	LDA f:OVERWORLD_EVENT_MUSIC_PTR_TABLE,X
	AND #$7FFF
	CLC
	ADC $0A
	STA $0A
@UNKNOWN1:
	MOVE_INT $0A, $06
	LDA [$06]
	BEQ @UNKNOWN3
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA $0E
	LDX #$0000
	LDA [$06]
	CMP #$8000
	BLTEQ @UNKNOWN2
	LDX #$0001
@UNKNOWN2:
	STX $02
	LDA $0E
	CMP $02
	BEQ @UNKNOWN3
	LDA #$0004
	CLC
	ADC $0A
	STA $0A
	BRA @UNKNOWN1
@UNKNOWN3:
<<<<<<< HEAD
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, LOADED_MAP_MUSIC_ENTRY
=======
	MOVE_INT $0A, $06
	MOVE_INT $06, UNKNOWN_7E5E38
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	LDY #$0002
	LDA [$0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX NEXT_MAP_MUSIC_TRACK
	LDA DO_MAP_MUSIC_FADE
	BNE @UNKNOWN4
	CPX CURRENT_MAP_MUSIC_TRACK
	BEQ @UNKNOWN4
	LDA #$0002
	JSL UNKNOWN_C0AC0C
@UNKNOWN4:
	PLD
	RTL
