
<<<<<<< HEAD
UNKNOWN_C06ACA:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA PLAYER_HAS_DONE_SOMETHING_THIS_FRAME
=======
UNKNOWN_C06ACA: ;$C06ACA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	LDA UNKNOWN_7E0A34
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN0
	LDA GAME_STATE + game_state::unknownB0
	CMP #$0002
	BEQ @UNKNOWN0
	LDA PENDING_INTERACTIONS
	BNE @UNKNOWN0
	LDA ENEMY_HAS_BEEN_TOUCHED
	ORA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA $12
	AND #$7FFF
<<<<<<< HEAD
	STA @LOCAL01
	LDA #1
	STA USING_DOOR
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
=======
	STA $12
	LDA #$0001
	STA UNKNOWN_7E5DC2
	LDA #$0000
	STA $06
	LDA #$00CF
	STA $08
	LDA $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA #$0002
	JSL UNKNOWN_C064E3
	JSL UNKNOWN_C07C5B
@UNKNOWN0:
	PLD
	RTS
