
<<<<<<< HEAD
UNKNOWN_C06E6E:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL05
	STX @LOCAL04
	STA @LOCAL03
	LDA DEMO_FRAMES_LEFT
=======
UNKNOWN_C06E6E: ;$C06E6E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 28
	STY $1A
	STX $18
	STA $16
	LDA UNKNOWN_7E0081
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNEL @UNKNOWN4
	JSL UNKNOWN_C48C69
	LDX $18
	TXA
	ASL
	ASL
	ASL
	TAX
	STX $14
	LDY $1A
	TYA
	ASL
	ASL
	ASL
	STA $12
	LDA $16
	AND #$8000
	BEQ @UNKNOWN2
	LDY #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA __BSS_START__,Y
	CMP #$000C
	BNEL @UNKNOWN4
	LDA #$0000
	STA __BSS_START__,Y
<<<<<<< HEAD
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA ESCALATOR_ENTRANCE_DIRECTION
=======
	LDA #$0003
	STA MISC_DEBUG_FLAGS
	LDA UNKNOWN_7E5DC6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	XBA
	AND #$00FF
	ASL
	STA $02
	TXA
	LDX $02
	CLC
	ADC f:UNKNOWN_C06E02+8,X
	STA $04
	LDA $12
	STA $0E
	LDY $04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAY
	STY $1A
	LDX #$0010
	STX $18
	LDX $02
	LDA f:UNKNOWN_C06E02+16,X
	LDX $18
	JSL UNKNOWN_C48E6B
	LOADPTR UNKNOWN_C06E4A, $0E
	LDY $1A
	TYA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL UNKNOWN_C48E95
<<<<<<< HEAD
	STZ ESCALATOR_ENTRANCE_DIRECTION
	LDA #1
	STA UNREAD_7E5DBA
=======
	STZ UNKNOWN_7E5DC6
	LDA #$0001
	STA UNKNOWN_7E5DBA
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @UNKNOWN4
<<<<<<< HEAD
	LDA #1
	STA UNREAD_7E5DBA
	LDA @LOCAL03
	STA ESCALATOR_ENTRANCE_DIRECTION
=======
	LDA #$0001
	STA UNKNOWN_7E5DBA
	LDA $16
	STA UNKNOWN_7E5DC6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	XBA
	AND #$00FF
	ASL
	STA $16
	TAX
	LDA f:UNKNOWN_C06E02+16,X
	STA GAME_STATE+game_state::leader_direction
<<<<<<< HEAD
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA @LOCAL03
=======
	LDA #$0003
	STA MISC_DEBUG_FLAGS
	LDA $16
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	PHA
	LDX $14
	TXA
	PLX
	CLC
	ADC f:UNKNOWN_C06E02,X
	STA $04
	LDA $12
	STA $0E
	LDY $04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAX
	LOADPTR UNKNOWN_C06E2C, $0E
	TXA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL UNKNOWN_C48E95
@UNKNOWN3:
<<<<<<< HEAD
	LDA @VIRTUAL04
	STA ESCALATOR_NEW_X
	LDA @LOCAL01
	STA ESCALATOR_NEW_Y
	LDA #.LOWORD(-1)
	STA STAIRS_DIRECTION
=======
	LDA $04
	STA UNKNOWN_7E5DD0
	LDA $12
	STA UNKNOWN_7E5DD2
	LDA #$FFFF
	STA UNKNOWN_7E5DC4
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN4:
	PLD
	RTS
