
<<<<<<< HEAD
UNKNOWN_C06F82:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL01
	LDA STAIRS_DIRECTION
	BEQ @UNKNOWN0
	LDA STAIRS_DIRECTION
	CMP #256
=======
UNKNOWN_C06F82: ;$C06F82
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA #$0000
	STA $12
	LDA UNKNOWN_7E5DC4
	BEQ @UNKNOWN0
	LDA UNKNOWN_7E5DC4
	CMP #$0100
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN1
@UNKNOWN0:
	LDA STAIRS_NEW_Y
	DEC
	CMP GAME_STATE+game_state::leader_y_coord
	BLTEQ @UNKNOWN2
	LDA #$0001
	STA $12
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA STAIRS_NEW_Y
	INC
	CMP GAME_STATE+game_state::leader_y_coord
	BCS @UNKNOWN2
	LDA #$0001
	STA $12
@UNKNOWN2:
	LDA $12
	BEQ @UNKNOWN3
	LDA #WALKING_STYLE::STAIRS
	STA GAME_STATE+game_state::walking_style
	LDA STAIRS_NEW_X
	STA GAME_STATE+game_state::leader_x_coord
	LDA STAIRS_NEW_Y
	STA GAME_STATE+game_state::leader_y_coord
	STZ GAME_STATE + game_state::unknown84
	STZ GAME_STATE + game_state::unknown80
	BRA @UNKNOWN4
@UNKNOWN3:
	LOADPTR UNKNOWN_C06F82, $0E
	LDA #$0001
	JSL SCHEDULE_OVERWORLD_TASK
@UNKNOWN4:
	PLD
	RTL
