
<<<<<<< HEAD
UNKNOWN_C07A56:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	STX @VIRTUAL02
	STX @LOCAL03
	STA @LOCAL02
	LDA @VIRTUAL04
	STA MOVING_PARTY_MEMBER_ENTITY_ID
	LDY CURRENT_PARTY_MEMBER_TICK
	LDX @VIRTUAL02
	LDA @LOCAL02
=======
UNKNOWN_C07A56: ;$C07A56
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 24
	STY $04
	STX $02
	STX $16
	STA $14
	LDA $04
	STA UNKNOWN_7E9F73
	LDY UNKNOWN_7E4DC6
	LDX $02
	LDA $14
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0780F
	STA $12
	CMP #$FFFF
	BNE @UNKNOWN0
	LDA $04
	ASL
	TAX
	LDA $12
	STA ENTITY_ANIMATION_FRAME,X
	JMP @UNKNOWN3
@UNKNOWN0:
	LOADPTR SPRITE_GROUPING_PTR_TABLE, $0A
	LDA $12
	ASL
	ASL
	CLC
	ADC $0A
	STA $0A
	DEREFERENCE_PTR_TO $0A, $06
	MOVE_INT $06, $0E
	LDA $04
	ASL
	TAX
	LDA $10
	STA ENTITY_GRAPHICS_PTR_HIGH,X
	LDA $0E
	CLC
	ADC #$0009
	STA ENTITY_GRAPHICS_PTR_LOW,X
	LDY #$0008
	LDA [$0E],Y
	AND #$00FF
<<<<<<< HEAD
	STA ENTITY_GRAPHICS_SPRITE_BANK,X
	LDA @VIRTUAL02
	STA ENTITY_WALKING_STYLES,X
	LDA CURRENT_PARTY_MEMBER_TICK
=======
	STA UNKNOWN_30X2_TABLE_31,X
	LDA $02
	STA UNKNOWN_30X2_TABLE_40,X
	LDA UNKNOWN_7E4DC6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #char_struct::unknown55
	TAY
	LDA __BSS_START__,Y
	PHA
<<<<<<< HEAD
	LDA @VIRTUAL02
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL02
	LDA TEMP_REGISTER
	CMP @VIRTUAL02
=======
	LDA $02
	STA UNKNOWN_7E00C0
	PLA
	STA $02
	LDA UNKNOWN_7E00C0
	CMP $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN1
	LDA $16
	STA $02
	STA __BSS_START__,Y
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN15
	STA __BSS_START__,X
@UNKNOWN1:
	LDA GAME_STATE + game_state::unknown90
	BEQ @UNKNOWN2
	LDA $16
	STA $02
	CMP #$000C
	BEQ @UNKNOWN2
	LDA $04
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (SPRITE_TABLE_10_FLAGS::UNKNOWN15 | SPRITE_TABLE_10_FLAGS::UNKNOWN14 | SPRITE_TABLE_10_FLAGS::UNKNOWN13)
	STA __BSS_START__,X
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA $04
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN14 | SPRITE_TABLE_10_FLAGS::UNKNOWN13
	STA __BSS_START__,X
@UNKNOWN3:
	LDA GAME_STATE + game_state::unknownB0
	CMP #$0002
	BNE @UNKNOWN4
	LDA $04
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN12
	STA __BSS_START__,X
@UNKNOWN4:
	PLD
	RTL
