
<<<<<<< HEAD
UNKNOWN_C07C5B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PLAYER_INTANGIBILITY_FRAMES
=======
UNKNOWN_C07C5B: ;$C07C5B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA UNKNOWN_7E5D58
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN2
	LDA #$0018
	STA $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	LDA $0E
	INC
	STA $0E
@UNKNOWN1:
	CMP #$001E
	BCC @UNKNOWN0
@UNKNOWN2:
	PLD
	RTL
