
<<<<<<< HEAD
UNKNOWN_C09D03:
	LDY LAST_ALLOCATED_SCRIPT
=======
UNKNOWN_C09D03: ;$C09D03
	LDY UNKNOWN_7E0A54
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BPL @UNKNOWN0
	SEC
	RTS
@UNKNOWN0:
	LDA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	STA LAST_ALLOCATED_SCRIPT
	CLC
	RTS
