
UNKNOWN_C0B67F: ;$C0B67F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
.IF .DEFINED(JPN)
	RESERVE_STACK_SPACE_CLOBBER 18
.ELSE
	RESERVE_STACK_SPACE_CLOBBER 15
.ENDIF
	JSL UNKNOWN_C0927C
	JSL UNKNOWN_C01A86
	LDX #$0000
	LDA #$8000
	JSL ALLOC_SPRITE_MEM
	JSL INITIALIZE_MISC_OBJECT_DATA
	STZ BATTLE_MODE
	STZ INPUT_DISABLE_FRAME_COUNTER
<<<<<<< HEAD
	LDA #1
	STA NPC_SPAWNS_ENABLED
	LDA #.LOWORD(-1)
	STA ENEMY_SPAWNS_ENABLED
	LDA #10
	STA OVERWORLD_ENEMY_MAXIMUM
	STZ BATTLE_SWIRL_COUNTDOWN
	STZ PENDING_INTERACTIONS
	LDA #1
=======
	LDA #$0001
	STA UNKNOWN_7E4A58
	LDA #$FFFF
	STA UNKNOWN_7E4A5A
	LDA #$000A
	STA UNKNOWN_7E4A5E
	STZ BATTLE_SWIRL_COUNTDOWN
	STZ UNKNOWN_7E5D9A
	LDA #$0001
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL SET_BOUNDARY_BEHAVIOR
	LDA #$0697
	STA DAD_PHONE_TIMER
	LDA #.LOWORD(PROCESS_OVERWORLD_TASKS)
	JSL SET_IRQ_CALLBACK
<<<<<<< HEAD
	STZ PSI_TELEPORT_STYLE
	STZ PSI_TELEPORT_DESTINATION
	LDA #.LOWORD(-1)
	STA ENTITY_FADE_ENTITY
	LDA #23
=======
	STZ TELEPORT_STYLE
	STZ TELEPORT_DESTINATION
	LDA #$FFFF
	STA UNKNOWN_7EB4A8
	LDA #$0017
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #$0018
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #$0000
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL UNKNOWN_C02D29
	JSL UNKNOWN_C03A24
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT $0E
	LDX #$0200
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #.LOWORD(PALETTES)
=======
	LDA #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMSET16
	JSL UNKNOWN_C47F87
	JSL OVERWORLD_INITIALIZE
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_MAP_AT_POSITION
	JSL SPAWN_BUZZ_BUZZ
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
<<<<<<< HEAD
	COPY_TO_VRAM1 BUFFER, VRAM::TEXT_LAYER_TILES, $3800, 0
=======
	.I8
	LOADPTR UNKNOWN_7F0000, $0E
	LDY #$00
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
.ELSE
	LDA #$0001
	JSL UNKNOWN_C44963
	JSL UNKNOWN_C039E5
	PLD
.ENDIF
	RTS
