
UNKNOWN_C0C0B4: ;$C0C0B4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	LDY CURRENT_ENTITY_SLOT
	STY $10
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	TAX
	LDA f:UNKNOWN_C3DFE8,X
	AND #$00FF
	BEQL @UNKNOWN6
	LDY $10
	TYA
	ASL
	STA $04
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(ENTITY_PATHFINDING_STATES)
	STA @VIRTUAL02
	LDA #.LOWORD(-1)
	LDX @VIRTUAL02
=======
	ADC #.LOWORD(UNKNOWN_30X2_TABLE_41)
	STA $02
	LDA #$FFFF
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LDY #$0030
	TYX
	LDA #$0001
	JSL FIND_PATH_TO_PARTY
	CMP #$0000
	BNEL @UNKNOWN6
	LDA #$0000
	LDX $02
	STA __BSS_START__,X
	LDA $04
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINTS)
	TAX
	LDA __BSS_START__,X
	INC
	INC
	INC
	INC
	STA __BSS_START__,X
	LDA $04
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	TAY
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	BNE @UNKNOWN2
	LDA #$0001
	BRA @UNKNOWN7
@UNKNOWN2:
	LDA __BSS_START__,X
	STA $02
	LDA $12
	STA $04
	ASL
	ASL
	ADC $04
	ASL
	ASL
	ASL
	ASL
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(DELIVERY_PATHS)
	STA @LOCAL00
=======
	ADC #.LOWORD(UNKNOWN_7E4A96)
	STA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LDA __BSS_START__,Y
	TAY
	LDX #$0000
	STX $10
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA $0E
	PHA
	LDX $02
	LDA __BSS_START__,X
	PLX
	STA __BSS_START__,X
	LDA $0E
	PHA
	LDX $02
	LDA __BSS_START__+2,X
	PLX
	STA __BSS_START__+2,X
	INC $02
	INC $02
	INC $02
	INC $02
	LDA $0E
	INC
	INC
	INC
	INC
	STA $0E
	DEY
	LDX $10
	INX
	STX $10
@UNKNOWN4:
	CPY #$0000
	BEQ @UNKNOWN5
	CPX #$0014
	BCC @UNKNOWN3
@UNKNOWN5:
	LDA #$0000
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA #$0001
@UNKNOWN7:
	PLD
	RTL
