
<<<<<<< HEAD
UNKNOWN_C0C6B6:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	CMP #04
=======
UNKNOWN_C0C6B6: ;$C0C6B6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA UNKNOWN_7E9F47
	CMP #$0004
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BCC @UNKNOWN0
	LDA #$FFFF
	BRA @UNKNOWN4
@UNKNOWN0:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	SEC
	SBC #$0080
	STA $02
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC $02
	STA $0E
	LDA GAME_STATE+game_state::leader_y_coord
	SEC
	SBC #$0070
	STA $02
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC $02
	TAX
	LDA $0E
	CMP #$FFC0
	BCS @UNKNOWN1
	CMP #$0140
	BCS @UNKNOWN3
@UNKNOWN1:
	CPX #$FFC0
	BCS @UNKNOWN2
	CPX #$0140
	BCS @UNKNOWN3
@UNKNOWN2:
	LDA #$FFFF
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #$0000
@UNKNOWN4:
	PLD
	RTL
