
UNKNOWN_C0CBD3: ;$C0CBD3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	LDA CURRENT_SCRIPT_SLOT
	ASL
	PHA
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
<<<<<<< HEAD
	LDA ENTITY_MOVEMENT_SPEEDS,X
	STORE_INT1632 @VIRTUAL0A
=======
	LDA UNKNOWN_30X2_TABLE_35,X
	STORE_INT1632 $0A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0008
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT1632 $0E, $06
	JSL ASL32_ENTRY2
	REP #PROC_FLAGS::INDEX8
	JSL DIVISION32
	LDA $06
	PLX
<<<<<<< HEAD
	STA ENTITY_SCRIPT_SLEEP_FRAMES,X
	END_C_FUNCTION
=======
	STA ENTITY_SLEEP_FRAMES,X
	PLD
	RTL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
