
UNKNOWN_C0CCCC: ;$C0CCCC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDY CURRENT_ENTITY_SLOT
	STY $14
	TYA
	ASL
	TAX
	STX $12
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR6_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	CLC
	ADC #$0010
	STA ENTITY_SCRIPT_VAR7_TABLE,X
<<<<<<< HEAD
	STZ @LOCAL00 + fixed_point::fraction
	LDA ENTITY_MOVEMENT_SPEEDS,X
=======
	STZ $0E
	LDA UNKNOWN_30X2_TABLE_35,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LSR
	LSR
	LSR
	LSR
	STA $10
	MOVE_INT_CONSTANT $64800, $0A
	MOVE_INT $0E, $06
	JSL DIVISION32
	LDA $06
	XBA
	AND #$FF00
	STA ENTITY_SCRIPT_VAR5_TABLE,X
	JSL RAND
	AND #$0001
	BEQ @UNKNOWN0
	LDX $12
	STZ ENTITY_DIRECTIONS,X
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #DIRECTION::DOWN
	LDX $12
	STA ENTITY_DIRECTIONS,X
@UNKNOWN1:
	LDY $14
	TYA
	ASL
	TAX
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::DOWN
	BCS @UNKNOWN2
	STZ ENTITY_UNKNOWN_2DC6,X
	BRA @UNKNOWN3
@UNKNOWN2:
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA ENTITY_UNKNOWN_2DC6,X
=======
	LDA #$FFFF
	STA UNKNOWN_30X2_TABLE_45,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN3:
	TYA
	ASL
	TAX
	STZ ENTITY_SCRIPT_VAR4_TABLE,X
	PLD
	RTL
