
UNKNOWN_C0D0E6: ;$C0D0E6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CURRENT_ENTITY_SLOT
	STA $02
	JSL UNKNOWN_C0C363
	CMP #$0000
	BNE @UNKNOWN0
	LDA $02
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @UNKNOWN0
	LDA GAME_STATE+game_state::leader_x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA ENTITY_ABS_Y_TABLE,X
	LDA #$FFFF
	BRA @UNKNOWN2
@UNKNOWN0:
	JSL UNKNOWN_C09EFF
<<<<<<< HEAD
	LDA #4
	STA @LOCAL00
	LDY @VIRTUAL02
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
=======
	LDA #$0004
	STA $0E
	LDY $02
	LDX UNKNOWN_7E284A
	LDA UNKNOWN_7E2848
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C05CD7
	AND #$00C0
	BEQ @UNKNOWN1
	LDA $02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_MOVEMENT_SPEEDS)
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #$1000
	STA __BSS_START__,X
	LDA #$0000
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA $02
	ASL
	TAX
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	STA ENTITY_ABS_X_TABLE,X
	LDA ENTITY_MOVEMENT_PROSPECTIVE_Y
	STA ENTITY_ABS_Y_TABLE,X
	LDA #$FFFF
@UNKNOWN2:
	PLD
	RTL
