
<<<<<<< HEAD
UNKNOWN_C0D5B0:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA BATTLE_MODE
=======
UNKNOWN_C0D5B0: ;$C0D5B0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA BATTLE_DEBUG
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN0
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN0:
	LDA USING_DOOR
	BEQ @UNKNOWN1
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN1:
	LDA CURRENT_ENTITY_SLOT
	STA $02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN2
	LDA $02
	CMP TOUCHED_ENEMY
	BEQ @UNKNOWN8
@UNKNOWN2:
	LDA GAME_STATE + game_state::unknownB0
	CMP #$0002
	BNE @UNKNOWN3
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN3:
<<<<<<< HEAD
	LDA PLAYER_MOVEMENT_FLAGS
	AND #02
=======
	LDA MISC_DEBUG_FLAGS
	AND #$0002
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN4
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN4:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BNE @UNKNOWN5
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN5:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @UNKNOWN6
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN6:
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN7
	LDA $02
	ASL
	TAX
	LDA ENTITY_PATH_POINT_COUNTS,X
	BEQ @UNKNOWN8
@UNKNOWN7:
	JSL UNKNOWN_C0D15C
	CMP #$0000
	BNE @UNKNOWN8
	LDA #$0000
	JMP @UNKNOWN25
@UNKNOWN8:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN9
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN9
	LDA $02
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @UNKNOWN9
	LDA #$0001
	JMP @UNKNOWN25
@UNKNOWN9:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN15
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN15
<<<<<<< HEAD
	LDA #1
	STA ENEMY_HAS_BEEN_TOUCHED
=======
	LDA #$0001
	STA BATTLE_SWIRL_FLAG
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL UNKNOWN_C0D4DE
	LDA $02
	CMP ENTITY_COLLIDED_OBJECTS+46
	BNE @UNKNOWN10
<<<<<<< HEAD
	LDA #24
	STA ENEMY_PATHFINDING_TARGET_ENTITY
=======
	LDA #$0018
	STA UNKNOWN_7E4DB8
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA $02
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	STA ENEMY_PATHFINDING_TARGET_ENTITY
@UNKNOWN11:
	LDA $02
	STA TOUCHED_ENEMY
	LDA #$0000
	STA $14
	BRA @UNKNOWN14
@UNKNOWN12:
	CMP #$0017
	BEQ @UNKNOWN13
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@UNKNOWN13:
	LDA $14
	INC
	STA $14
@UNKNOWN14:
	CMP #$001E
	BCC @UNKNOWN12
	JSL UNKNOWN_C04A88
	LDA #$0001
	JMP @UNKNOWN25
@UNKNOWN15:
	LDA $02
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	STZ $12
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQL @UNKNOWN24
	LDA $02
	CMP TOUCHED_ENEMY
	BNE @UNKNOWN17
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA #$0001
	STA $12
	JMP @UNKNOWN24
@UNKNOWN17:
<<<<<<< HEAD
	LDA ENTITY_ENEMY_IDS,X
	STA @VIRTUAL04
	LDY #0
	STZ @LOCAL02
=======
	LDA ENTITY_ENEMY_ID,X
	STA $04
	LDY #$0000
	STZ $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	STA $10
	BRA @UNKNOWN20
@UNKNOWN18:
	ASL
	TAX
<<<<<<< HEAD
	LDA @VIRTUAL04
	CMP PATHFINDING_ENEMY_IDS,X
=======
	LDA $04
	CMP UNKNOWN_7E4A7C,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN19
	TXA
	CLC
	ADC #.LOWORD(PATHFINDING_ENEMY_COUNTS)
	TAX
	LDA __BSS_START__,X
	STA $0E
	BEQ @UNKNOWN19
	LDA $0E
	DEC
	STA __BSS_START__,X
	LDA #$0001
	STA $12
	LDA $02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
<<<<<<< HEAD
	LDA @VIRTUAL04
	STA ENEMIES_IN_BATTLE_IDS,X
=======
	LDA $04
	STA UNKNOWN_7E9F8C,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	INC ENEMIES_IN_BATTLE
@UNKNOWN19:
	LDA $10
	ASL
	TAX
	TYA
	CLC
	ADC PATHFINDING_ENEMY_COUNTS,X
	TAY
	LDA $10
	INC
	STA $10
@UNKNOWN20:
	CMP #$0004
	BNE @UNKNOWN18
	CPY #$0000
	BNE @UNKNOWN24
	JSL UNKNOWN_C2E9C8
	CMP #$0000
	BNE @UNKNOWN24
	LDA #$0000
	STA $14
	BRA @UNKNOWN23
@UNKNOWN21:
	CMP #$0017
	BEQ @UNKNOWN22
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@UNKNOWN22:
	LDA $14
	INC
	STA $14
@UNKNOWN23:
	CMP #$001E
	BCC @UNKNOWN21
	LDA #$0001
	STA BATTLE_SWIRL_COUNTDOWN
@UNKNOWN24:
	LDA $12
@UNKNOWN25:
	PLD
	RTL
