
UNKNOWN_C0D7F7: ;$C0D7F7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 32
	LDA CURRENT_ENTITY_SLOT
	STA $1E
	ASL
	TAX
<<<<<<< HEAD
	LDA ENTITY_PATHFINDING_STATES,X
	CMP #.LOWORD(-1)
	BNEL @UNKNOWN15
	LDA ENTITY_SIZES,X
	STA @LOCAL07
	LDA ENTITY_PATH_POINTS,X
	STA @VIRTUAL02
	STA @LOCAL06
=======
	LDA UNKNOWN_30X2_TABLE_41,X
	CMP #$FFFF
	BNEL @UNKNOWN15
	LDA ENTITY_SIZES,X
	STA $1C
	LDA UNKNOWN_30X2_TABLE_46,X
	STA $02
	STA $1A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA ENTITY_ABS_X_TABLE,X
	STA $18
	LDA ENTITY_ABS_Y_TABLE,X
	STA $16
	LDA $1C
	ASL
	TAX
	STX $14
	LDX $02
	LDA __BSS_START__+2,X
	ASL
	ASL
	ASL
	LDX $14
	CLC
	ADC f:UNKNOWN_C42A1F,X
<<<<<<< HEAD
	STA @VIRTUAL04
	LDA PATHFINDING_TARGET_CENTRE_X
=======
	STA $04
	LDA UNKNOWN_7E4A8E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	ASL
	ASL
	ASL
	CLC
	ADC $04
	STA $12
	LDX $02
	LDA __BSS_START__,X
	ASL
	ASL
	ASL
	LDX $14
	SEC
	SBC f:UNKNOWN_C42AEB,X
	CLC
	ADC f:UNKNOWN_C42A41,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
=======
	STA $02
	LDA UNKNOWN_7E4A90
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	ASL
	ASL
	ASL
	CLC
	ADC $02
	STA $04
	LDA $18
	SEC
	SBC $12
	STA $10
	STA $02
	LDA #$0000
	CLC
	SBC $02
	BRANCHLTEQS @UNKNOWN3
	LDA $10
	EOR #$FFFF
	INC
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA $10
@UNKNOWN4:
	STA $02
	LDA #$0003
	CLC
	SBC $02
	JUMPLTEQS @UNKNOWN13
	LDA $16
	SEC
	SBC $04
	STA $10
	STA $02
	LDA #$0000
	CLC
	SBC $02
	BRANCHLTEQS @UNKNOWN9
	LDA $10
	EOR #$FFFF
	INC
	BRA @UNKNOWN10
@UNKNOWN9:
	LDA $10
@UNKNOWN10:
	STA $02
	LDA #$0003
	CLC
	SBC $02
	BRANCHLTEQS @UNKNOWN13
	LDA $1E
	ASL
	STA $10
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	TAX
	LDA __BSS_START__,X
	TAY
	DEY
	TYA
	STA __BSS_START__,X
	BEQ @UNKNOWN13
	LDA $1A
	STA $02
	LDX $02
	INX
	INX
	INX
	INX
	STX $14
	PHX
	LDA $10
	TAX
	PLA
<<<<<<< HEAD
	STA ENTITY_PATH_POINTS,X
	LDA @LOCAL07
=======
	STA UNKNOWN_30X2_TABLE_46,X
	LDA $1C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $1C
	PHA
	LDX $14
	LDA __BSS_START__+2,X
	ASL
	ASL
	ASL
	PLX
	CLC
	ADC f:UNKNOWN_C42A1F,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_X
=======
	STA $02
	LDA UNKNOWN_7E4A8E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	ASL
	ASL
	ASL
	CLC
	ADC $02
	STA $12
	LDA $1C
	PHA
	PHA
	LDX $14
	LDA __BSS_START__,X
	ASL
	ASL
	ASL
	PLX
	SEC
	SBC f:UNKNOWN_C42AEB,X
	PLX
	CLC
	ADC f:UNKNOWN_C42A41,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
=======
	STA $02
	LDA UNKNOWN_7E4A90
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	ASL
	ASL
	ASL
	CLC
	ADC $02
	STA $04
@UNKNOWN13:
	LDA $1E
	ASL
<<<<<<< HEAD
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA ENTITY_PATH_POINT_COUNTS,X
=======
	STA $02
	LDX $02
	LDA UNKNOWN_7E2E3E,X
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN14
	LDA $04
	STA $0E
	LDY $12
	LDX $16
	LDA $18
	JSL UNKNOWN_C41EFF
	JSL UNKNOWN_C47044
	JSL UNKNOWN_C46B0A
	LDX $02
	STA ENTITY_DIRECTIONS,X
	BRA @UNKNOWN15
@UNKNOWN14:
<<<<<<< HEAD
	LDX @VIRTUAL02
	STZ ENTITY_PATHFINDING_STATES,X
	LDA @VIRTUAL02
=======
	LDX $02
	STZ UNKNOWN_30X2_TABLE_41,X
	LDA $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #.LOWORD(ENTITY_OBSTACLE_FLAGS)
	TAX
	LDA __BSS_START__,X
	ORA #$0080
	STA __BSS_START__,X
@UNKNOWN15:
	PLD
	RTL
