
UNKNOWN_C0D98F: ;$C0D98F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	STA @VIRTUAL04
	LDX @VIRTUAL04
=======
	ADC #.LOWORD(UNKNOWN_7E2E3E)
	STA $04
	LDX $04
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	BNE @UNKNOWN0
	LDA #$0000
	JMP @UNKNOWN1
@UNKNOWN0:
	LDA ENTITY_SIZES,Y
	STA $12
	TYA
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(ENTITY_PATH_POINTS)
	STA @VIRTUAL02
	STA @LOCAL01
	LDX @VIRTUAL02
=======
	ADC #.LOWORD(UNKNOWN_30X2_TABLE_46)
	STA $02
	STA $10
	LDX $02
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,X
	TAX
	STX $0E
	LDA $12
	ASL
	STA $12
	PHA
	LDA __BSS_START__+2,X
	ASL
	ASL
	ASL
	PLX
	CLC
	ADC f:UNKNOWN_C42A1F,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_X
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	OPTIMIZED_MULT @VIRTUAL04, 8
=======
	STA $02
	LDA UNKNOWN_7E4A8E
	SEC
	SBC UNKNOWN_7E4A92
	ASL
	ASL
	ASL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $02
	STA ENTITY_SCRIPT_VAR6_TABLE,Y
	LDA $12
	PHA
	PHA
	LDX $0E
	LDA __BSS_START__,X
	ASL
	ASL
	ASL
	PLX
	SEC
	SBC f:UNKNOWN_C42AEB,X
	PLX
	CLC
	ADC f:UNKNOWN_C42A41,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	OPTIMIZED_MULT @VIRTUAL04, 8
=======
	STA $02
	LDA UNKNOWN_7E4A90
	SEC
	SBC UNKNOWN_7E4A94
	ASL
	ASL
	ASL
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC $02
	STA ENTITY_SCRIPT_VAR7_TABLE,Y
	LDX $04
	LDA __BSS_START__,X
	DEC
	LDX $04
	STA __BSS_START__,X
	LDX $0E
	TXA
	INC
	INC
	INC
	INC
	LDX $10
	STX $02
	STA __BSS_START__,X
	LDA #$0001
@UNKNOWN1:
	PLD
	RTL
