
<<<<<<< HEAD
UNKNOWN_C0DD79:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_DESTINATION
	STA @VIRTUAL02
	LDY #1
	STY @LOCAL01
=======
UNKNOWN_C0DD79: ;$C0DD79
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA TELEPORT_DESTINATION
	STA $02
	LDY #$0001
	STY $10
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX #$0000
	TYA
	JSL SET_EVENT_FLAG
	LDY $10
	INY
	STY $10
@UNKNOWN1:
	CPY #$000A
	BLTEQ @UNKNOWN0
	LOADPTR PSI_TELEPORT_DEST_TABLE, $06
	LDA $02
	LDY #.SIZEOF(psi_teleport_destination)
	JSL MULT168
	STA $10
	CLC
	ADC #psi_teleport_destination::dest_x
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	TAX
<<<<<<< HEAD
	STX CURRENT_TELEPORT_DESTINATION_X
	LDA @LOCAL01
	CLC
	ADC #psi_teleport_destination::dest_y
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL01
	STA CURRENT_TELEPORT_DESTINATION_Y
=======
	STX UNKNOWN_7E438A
	LDA $10
	CLC
	ADC #psi_teleport_destination::dest_y
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $10
	STA UNKNOWN_7E438C
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TXA
	ASL
	ASL
	ASL
	STA $02
	LDA $10
	ASL
	ASL
	ASL
<<<<<<< HEAD
	STA @LOCAL00
	LDA PSI_TELEPORT_STYLE
=======
	STA $0E
	LDA TELEPORT_STYLE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @UNKNOWN2
	LDA $02
	CLC
	ADC #$013C
	STA $02
@UNKNOWN2:
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	STA CURRENT_MAP_MUSIC_TRACK
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	LDY #6
	LDA @LOCAL00
=======
	LDA #$FFFF
	STA UNKNOWN_7E5DD4
	STA UNKNOWN_7E4370
	STA UNKNOWN_7E436E
	LDY #$0006
	LDA $0E
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TAX
	LDA $02
	JSL INITIALIZE_MAP
	PLD
	RTL
