
<<<<<<< HEAD
UNKNOWN_C0DE7C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(PARTY_CHARACTERS)
	STA CURRENT_PARTY_MEMBER_TICK
	LDY #24
=======
UNKNOWN_C0DE7C: ;$C0DE7C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA #.LOWORD(CHAR_STRUCT)
	STA UNKNOWN_7E4DC6
	LDY #$0018
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BRA @UNKNOWN1
@UNKNOWN0:
	TYA
	ASL
	STA $0E
	TAX
	LDA #$0008
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA $0E
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::UNKNOWN11
	STA __BSS_START__,X
	LDA $0E
	CLC
	ADC #.LOWORD(ENTITY_COLLIDED_OBJECTS)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
<<<<<<< HEAD
	LDA #.LOWORD(-1)
	LDX CURRENT_PARTY_MEMBER_TICK
=======
	LDA #$FFFF
	LDX UNKNOWN_7E4DC6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA a:char_struct::unknown55,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #.SIZEOF(char_struct)
	STA CURRENT_PARTY_MEMBER_TICK
	INY
@UNKNOWN1:
	CPY #$001E
	BCC @UNKNOWN0
	JSL CHANGE_MUSIC_5DD6
	PLD
	RTS
