
<<<<<<< HEAD
UNKNOWN_C0E44D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
=======
UNKNOWN_C0E44D: ;$C0E44D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA TELEPORT_STYLE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CMP #TELEPORT_STYLE::PSI_BETTER
	BEQ @UNKNOWN3
	LDA PAD_STATE
	STA $0E
	AND #PAD::UP
	BEQ @UNKNOWN0
	DEC PSI_TELEPORT_BETA_Y_ADJUSTMENT
@UNKNOWN0:
	LDA $0E
	AND #PAD::DOWN
	BEQ @UNKNOWN1
	INC PSI_TELEPORT_BETA_Y_ADJUSTMENT
@UNKNOWN1:
	LDA $0E
	AND #PAD::LEFT
	BEQ @UNKNOWN2
	DEC PSI_TELEPORT_BETA_X_ADJUSTMENT
@UNKNOWN2:
	LDA $0E
	AND #PAD::RIGHT
	BEQ @UNKNOWN3
	INC PSI_TELEPORT_BETA_X_ADJUSTMENT
@UNKNOWN3:
	PLD
	RTS
