
<<<<<<< HEAD
UNKNOWN_C0E815:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
=======
UNKNOWN_C0E815: ;$C0E815
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 26
	LDA TELEPORT_STYLE
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @UNKNOWN2
	LDA #$0018
	STA $18
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA $18
	INC
	STA $18
@UNKNOWN1:
	CMP #$001E
	BCC @UNKNOWN0
<<<<<<< HEAD
	LDY #.LOWORD(PSI_TELEPORT_SPEED_Y) + fixed_point::integer
	STY @LOCAL02
	LDA #00
	STA __BSS_START__,Y
	LDX #.LOWORD(PSI_TELEPORT_SPEED_X) + fixed_point::integer
	STX @LOCAL03
=======
	LDY #.LOWORD(UNKNOWN_7E9F4D) + 2
	STY $16
	LDA #$0000
	STA __BSS_START__,Y
	LDX #.LOWORD(UNKNOWN_7E9F49) + 2
	STX $18
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	STA __BSS_START__,X
	LOADPTR UNKNOWN_C0E674, $0E
	LOADPTR UNKNOWN_C0E3C1, $12
	LDA #$0017
	JSL SET_PARTY_TICK_CALLBACKS
	LDX $18
	LDA __BSS_START__,X
	STA PSI_TELEPORT_SUCCESS_SCREEN_SPEED_X
	LDA GAME_STATE+game_state::leader_x_coord
<<<<<<< HEAD
	STA PSI_TELEPORT_SUCCESS_SCREEN_X
	LDY @LOCAL02
=======
	STA UNKNOWN_7E9F5B
	LDY $16
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA __BSS_START__,Y
	STA PSI_TELEPORT_SUCCESS_SCREEN_SPEED_Y
	LDA GAME_STATE+game_state::leader_y_coord
<<<<<<< HEAD
	STA PSI_TELEPORT_SUCCESS_SCREEN_Y
	LDX #4
	LDA #1
=======
	STA UNKNOWN_7E9F5F
	LDX #$0004
	LDA #$0001
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL FADE_OUT
	JSR UNKNOWN_C0DD0F
@UNKNOWN2:
	PLD
	RTS
