
<<<<<<< HEAD
UNKNOWN_C0E9BA:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA DISABLED_TRANSITIONS
=======
UNKNOWN_C0E9BA: ;$C0E9BA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA #$0001
	STA UNKNOWN_7EB4B6
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	LDA #MUSIC::TELEPORT_FAIL
	JSL CHANGE_MUSIC
	LDA #PARTY_LEADER_ENTITY_INDEX
	STA $16
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN15
	STA __BSS_START__,X
	LDA $16
	INC
	STA $16
@UNKNOWN1:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN0
	LOADPTR UNKNOWN_C0E979, $0E
	LOADPTR UNKNOWN_C0E97C, $12
	LDA #$0017
	JSL SET_PARTY_TICK_CALLBACKS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA GAME_STATE + game_state::party_status
	LDX #$0000
	STX $16
	BRA @UNKNOWN3
@UNKNOWN2:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX $16
	INX
	STX $16
@UNKNOWN3:
	CPX #$00B4
	BCC @UNKNOWN2
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_status
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STZ DISABLED_TRANSITIONS
	END_C_FUNCTION
=======
	STZ UNKNOWN_7EB4B6
	PLD
	RTS
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
