
UNKNOWN_C0EC77: ;$C0EC77
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	BNE @UNKNOWN0
<<<<<<< HEAD
	LOADPTR UNKNOWN_E1AE83, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	BRA @UNKNOWN1
@UNKNOWN0:
	LOADPTR UNKNOWN_E1AEFD, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
=======
	LOADPTR UNKNOWN_E1AE83, $0E
	LOADPTR UNKNOWN_7F0000, $12
	JSL DECOMP
	BRA @UNKNOWN1
@UNKNOWN0:
	LOADPTR UNKNOWN_E1AEFD, $0E
	LOADPTR UNKNOWN_7F0000, $12
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL DECOMP
@UNKNOWN1:
	PLD
	RTL
