
UNKNOWN_C0ECB7: ;$C0ECB7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LOADPTR TITLE_SCREEN_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR TITLE_SCREEN_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
	JSL UNKNOWN_C496F9
	SEP #PROC_FLAGS::ACCUM8
	STZ $0E
	LDX #$0100
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #.LOWORD(PALETTES)
=======
	LDA #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMSET16
	LDX #$00FF
	LDA #$00A5
	JSL UNKNOWN_C496E7
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
