
UNKNOWN_C0EDDA: ;$C0EDDA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
	STY $16
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	STA $14
	LDA ENTITY_SCRIPT_VAR2_TABLE,X
<<<<<<< HEAD
	STA @VIRTUAL02
	LOADPTR BUFFER, @VIRTUAL06
=======
	STA $02
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #$0020
	LDA $14
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PALETTES)
=======
	ADC #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	LDY $16
	TYA
	INC
	STA $12
	CMP $02
	BNE @UNKNOWN0
	LDA #$0000
	STA $12
@UNKNOWN0:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA $12
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
