
UNKNOWN_C0ED41:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
<<<<<<< HEAD
	STY @LOCAL02
	LOADPTR BUFFER, @VIRTUAL06
=======
	STY $14
	LOADPTR UNKNOWN_7F0000, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	LDY #$0200
	JSL MULT16
	CLC
<<<<<<< HEAD
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #BPP4PALETTE_SIZE * 16
	LDA #.LOWORD(PALETTES)
=======
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #$0200
	LDA #$0200
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	LDY $14
	TYA
	INC
	STA $12
	CMP #$0009
	BNE @UNKNOWN0
	LDA #$0000
	STA $12
@UNKNOWN0:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA $12
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL