
UNKNOWN_C0ED5C: ;$C0ED5C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LOADPTR TITLE_SCREEN_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
	LOADPTR TITLE_SCREEN_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
	LDA #$0000
	JSL UNKNOWN_C0EC77
<<<<<<< HEAD
	LOADPTR BUFFER+$1A0, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 8
=======
	LOADPTR UNKNOWN_7F0000+$1A0, $0E
	LDX #$0020
	LDA #$0300
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	JSL MEMCPY16
	LDA #$0001
	JSL UNKNOWN_C0EC77
<<<<<<< HEAD
	LOADPTR BUFFER+$260, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 7
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
=======
	LOADPTR UNKNOWN_7F0000+$260, $0E
	LDX #$0020
	LDA #$02E0
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0018
	STA UNKNOWN_7E0030
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
