
<<<<<<< HEAD
UNKNOWN_C0F3E8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR GAS_STATION_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
=======
UNKNOWN_C0F3E8: ;$C0F3E8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LOADPTR GAS_STATION_PALETTE, $0E
	PROMOTENEARPTR $0200, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL DECOMP
	LDA #$0018
	JSL UNKNOWN_C0856B
	PLD
	RTL
