
<<<<<<< HEAD
LOAD_BG_OFFSET_PARAMETERS:
	STA BACKGROUND_DISTORTION_STYLE
	STX BACKGROUND_DISTORTION_TARGET_LAYER
	STY BACKGROUND_DISTORTION_IS_SECONDARY_LAYER
=======
LOAD_BG_OFFSET_PARAMETERS: ;$C0AE4C
	STA UNKNOWN_7E1ACC
	STX UNKNOWN_7E1ACE
	STY UNKNOWN_7E1AD2
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	RTL
