
;void PathfindToParty(int partycount)
FIND_PATH_TO_PARTY: ;$C0BC74
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 44
	STA $2A
	LDA GAME_STATE+game_state::current_party_members
<<<<<<< HEAD
	STA @LOCAL0B
	LDA #.LOWORD(PATHFINDING_STATE)
	STA @LOCAL0A
	STX PATHFINDING_STATE + pathfinding::radius
	STY PATHFINDING_STATE + pathfinding::radius + 2
	LDA PATHFINDING_STATE + pathfinding::radius
	LSR
	STA @VIRTUAL04
	STA PATHFINDING_TARGET_WIDTH
	LDA PATHFINDING_STATE + pathfinding::radius + 2
	LSR
	STA @VIRTUAL02
	STA @LOCAL09
	LDA @VIRTUAL02
	STA PATHFINDING_TARGET_HEIGHT
	LDA @LOCAL0B
=======
	STA $28
	LDA #.LOWORD(UNKNOWN_7EF200)
	STA $26
	STX UNKNOWN_7EF200 + pathfinding::radius
	STY UNKNOWN_7EF200 + pathfinding::radius + 2
	LDA UNKNOWN_7EF200 + pathfinding::radius
	LSR
	STA $04
	STA UNKNOWN_7E4A92
	LDA UNKNOWN_7EF200 + pathfinding::radius + 2
	LSR
	STA $02
	STA $24
	LDA $02
	STA UNKNOWN_7E4A94
	LDA $28
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $28
	CLC
	ADC #.LOWORD(ENTITY_ABS_X_TABLE)
	TAY
	STY $22
	LOADPTR UNKNOWN_C42A1F, $0A
	LDA $28
	CLC
	ADC #.LOWORD(ENTITY_SIZES)
	STA $20
	LDA ($20)
	ASL
	MOVE_INTX $0A, $06
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $02
	LDA __BSS_START__,Y
	SEC
	SBC $02
	LSR
	LSR
	LSR
<<<<<<< HEAD
	STA PATHFINDING_TARGET_CENTRE_X
	LDA @LOCAL0BALT
=======
	STA UNKNOWN_7E4A8E
	LDA $28
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	CLC
	ADC #.LOWORD(ENTITY_ABS_Y_TABLE)
	TAX
	LOADPTR UNKNOWN_C42A41, $06
	MOVE_INT $06, $1C
	LDA ($20)
	ASL
	STA $1A
	LOADPTR UNKNOWN_C42AEB, $16
	LDA $1A
	TAY
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $02
	LDA __BSS_START__,X
	SEC
	SBC $02
	CLC
	ADC [$16],Y
	LSR
	LSR
	LSR
<<<<<<< HEAD
	STA PATHFINDING_TARGET_CENTRE_Y
	LDA (@LOCAL07)
=======
	STA UNKNOWN_7E4A90
	LDA ($20)
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	ASL
	STA $1A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	STA $02
	LDY $22
	LDA __BSS_START__,Y
	SEC
	SBC $02
	LSR
	LSR
	LSR
	SEC
	SBC $04
	STA $04
	LDA $1A
	TAY
	PHA
	MOVE_INT $1C, $06
	PLA
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $02
	LDA __BSS_START__,X
	SEC
	SBC $02
	CLC
	ADC [$16],Y
	LSR
	LSR
	LSR
	LDX $24
	STX $02
	SEC
	SBC $02
	STA $02
	STA $0E
	LDY $04
	LDX $2A
	LDA $26
	JSR UNKNOWN_C0B9BC
	MOVE_INT1632 $02, $0E
	LDA #$0040
	STA $12
	LDA #$0032
	STA $14
	LDY $04
	LDX $2A
	LDA $26
	JSR UNKNOWN_C0BA35
	PLD
	RTL
