
<<<<<<< HEAD
HP_PP_ROLLER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA DISABLE_HPPP_ROLLING
=======
HP_PP_ROLLER: ;$C2109F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA UNKNOWN_7E9697
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BNEL @UNKNOWN30
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0003
	TAX
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	BEQL @UNKNOWN30
	AND #$00FF
	STA $12
	CLC
	SBC #$0004
	JUMPGTS @UNKNOWN30
	LDA $12
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @LOCAL01
	LDA HPPP_METER_FLIPOUT_MODE
=======
	ADC #.LOWORD(CHAR_STRUCT)
	STA $10
	LDA UNKNOWN_7E9698
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BNE @UNKNOWN4
	LDA $10
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	STX $0E
	LDA __BSS_START__,X
	AND #$0001
	BEQL @UNKNOWN14
@UNKNOWN4:
	LDA $10
	TAX
	LDY a:char_struct::current_hp,X
	TAX
	LDA a:char_struct::current_hp_target,X
	STA $02
	TYA
	CMP $02
	BCS @UNKNOWN9
	LDA $10
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	TXY
<<<<<<< HEAD
	STY @LOCAL00
	LDA FASTEST_HPPP_METER_SPEED
=======
	STY $0E
	LDA UNKNOWN_7E9696
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	AND #$00FF
	BNE @UNKNOWN5
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @UNKNOWN6
@UNKNOWN5:
	MOVE_INT_CONSTANT $00064000, $06
	BRA @UNKNOWN7
@UNKNOWN6:
	JSR UNKNOWN_C20F58
@UNKNOWN7:
	MOVE_INT $06, $0A
	LDY $0E
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA $10
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	CMP $02
	BCCL @UNKNOWN15
	LDA $02
	STA __BSS_START__,X
	LDA $10
	TAX
	LDA #$0001
	STA a:char_struct::current_hp_fraction,X
	JMP @UNKNOWN15
@UNKNOWN9:
	TYA
	CMP $02
	BNE @UNKNOWN10
	LDA $10
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	LDA __BSS_START__,X
	CMP #$0001
	BNE @UNKNOWN10
	LDA #$0000
	STA __BSS_START__,X
	JMP @UNKNOWN15
@UNKNOWN10:
	LDA $10
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	TXY
<<<<<<< HEAD
	STY @LOCAL00
	LDA HPPP_METER_FLIPOUT_MODE
=======
	STY $0E
	LDA UNKNOWN_7E9698
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	BEQ @UNKNOWN11
	MOVE_INT_CONSTANT $00064000, $06
	BRA @UNKNOWN12
@UNKNOWN11:
	JSR UNKNOWN_C20F58
@UNKNOWN12:
	MOVE_INT $06, $0A
	LDY $0E
	MOVE_INT_YPTRSRC __BSS_START__, $06
	SEC
	SUB_INT_ASSIGN $06, $0A
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA $10
	TAX
	LDY a:char_struct::current_hp,X
	TYA
	CMP $02
	BCC @UNKNOWN13
	CPY #1000
	BLTEQ @UNKNOWN15
@UNKNOWN13:
	LDA $10
	TAX
	LDA $02
	STA a:char_struct::current_hp,X
	LDA $10
	TAX
	LDA #$0001
	STA a:char_struct::current_hp_fraction,X
	BRA @UNKNOWN15
@UNKNOWN14:
	LDA $10
	PHA
	TAX
	LDA a:char_struct::current_hp,X
	PLX
	CMP a:char_struct::current_hp_target,X
	BEQ @UNKNOWN15
	LDA #$0001
	LDX $0E
	STA __BSS_START__,X
@UNKNOWN15:
	LDA HPPP_METER_FLIPOUT_MODE
	BNE @UNKNOWN16
	LDA $10
	CLC
	ADC #$0049
	TAX
	STX $0E
	LDA __BSS_START__,X
	AND #$0001
	BEQL @UNKNOWN25
@UNKNOWN16:
	LDA $10
	TAX
	LDY a:char_struct::current_pp,X
	TAX
	LDA a:char_struct::current_pp_target,X
	STA $02
	TYA
	CMP $02
	BCS @UNKNOWN20
	LDA $10
	CLC
	ADC #$0049
	TAX
	TXY
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @UNKNOWN17
	MOVE_INT_CONSTANT $00064000, $06
	BRA @UNKNOWN18
@UNKNOWN17:
	MOVE_INT_CONSTANT $00019000, $06
@UNKNOWN18:
	MOVE_INT $06, $0A
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA $10
	CLC
	ADC #$004B
	TAX
	LDA __BSS_START__,X
	CMP $02
	BCCL @UNKNOWN26
	LDA $02
	STA __BSS_START__,X
	LDA $10
	TAX
	LDA #$0001
	STA __BSS_START__+73,X
	JMP @UNKNOWN26
@UNKNOWN20:
	TYA
	CMP $02
	BNE @UNKNOWN21
	LDA $10
	CLC
	ADC #$0049
	TAX
	LDA __BSS_START__,X
	CMP #$0001
	BNE @UNKNOWN21
	LDA #$0000
	STA __BSS_START__,X
	JMP @UNKNOWN26
@UNKNOWN21:
	LDA $10
	CLC
	ADC #$0049
	TAX
	TXY
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @UNKNOWN22
	MOVE_INT_CONSTANT $00064000, $06
	BRA @UNKNOWN23
@UNKNOWN22:
	MOVE_INT_CONSTANT $00019000, $06
@UNKNOWN23:
	MOVE_INT $06, $0A
	MOVE_INT_YPTRSRC __BSS_START__, $06
	SEC
	SUB_INT_ASSIGN $06, $0A
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA $10
	TAX
	LDY a:char_struct::current_pp,X
	TYA
	CMP $02
	BCC @UNKNOWN24
	CPY #1000
	BLTEQ @UNKNOWN26
@UNKNOWN24:
	LDA $10
	TAX
	LDA $02
	STA a:char_struct::current_pp,X
	LDA $10
	TAX
	LDA #$0001
	STA __BSS_START__+73,X
	BRA @UNKNOWN26
@UNKNOWN25:
	LDA $10
	PHA
	TAX
	LDA a:char_struct::current_pp,X
	PLX
	CMP a:char_struct::current_pp_target,X
	BEQ @UNKNOWN26
	LDA #$0001
	LDX $0E
	STA __BSS_START__,X
@UNKNOWN26:
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @UNKNOWN30
	LDA $10
	TAX
	LDY a:char_struct::current_hp,X
	CPY #$03E7
	BNE @UNKNOWN27
	TAX
	LDA #$0001
	STA a:char_struct::current_hp_target,X
	BRA @UNKNOWN28
@UNKNOWN27:
	CPY #$0001
	BNE @UNKNOWN28
	TAX
	LDA #$03E7
	STA a:char_struct::current_hp_target,X
@UNKNOWN28:
	LDA $10
	TAX
	LDY a:char_struct::current_pp,X
	CPY #$03E7
	BNE @UNKNOWN29
	TAX
	STZ a:char_struct::current_pp_target,X
	BRA @UNKNOWN30
@UNKNOWN29:
	CPY #$0000
	BNE @UNKNOWN30
	TAX
	LDA #$03E7
	STA a:char_struct::current_pp_target,X
@UNKNOWN30:
	PLD
	RTL
