
INVENTORY_GET_ITEM_NAME: ;$C198DE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 26
	TXY
	STY $18
	TAX
	DEC
	STA $04
	TYA
	JSR CREATE_WINDOW
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN0
<<<<<<< HEAD
	LDY @LOCAL04
	STY PAGINATION_WINDOW
=======
	LDY $18
	STY UNKNOWN_7E5E7A
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
@UNKNOWN0:
	LDA $04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
<<<<<<< HEAD
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::name
	PROMOTENEARPTRA @VIRTUAL06
=======
	ADC #.LOWORD(CHAR_STRUCT) + char_struct::name
	PROMOTENEARPTRA $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #.SIZEOF(char_struct::name)
	LDY $18
	TYA
	JSL SET_WINDOW_TITLE
	LDA #$0000
	STA $02
	JMP @UNKNOWN5
@UNKNOWN1:
	LDA $04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	TAY
	STY $16
	LDX $02
	INX
	LDA $04
	INC
	JSL CHECK_ITEM_EQUIPPED
	CMP #$0000
	BEQ @UNKNOWN2
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	LDA #CHAR::EQUIPPED
	STA TEMPORARY_TEXT_BUFFER
	REP #PROC_FLAGS::ACCUM8
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDY @LOCAL02
.ELSE
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
.ENDIF
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(item::name)
.IF .DEFINED(JPN)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
	LDX @VIRTUAL02
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	INC
	JSL CHECK_ITEM_EQUIPPED
	CMP #0
	BEQ @UNKNOWN2
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::EQUIPPED
	STA TEMPORARY_TEXT_BUFFER, X
	STZ TEMPORARY_TEXT_BUFFER + 1, X
@UNKNOWN2:
.ELSE
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)+1
	JSL MEMCPY16
	BRA @UNKNOWN3
@UNKNOWN2:
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDY @LOCAL02
=======
	LDA #$0022
	STA UNKNOWN_7E9C9F
	REP #PROC_FLAGS::ACCUM8
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDY $16
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(UNKNOWN_7E9C9F)+1
	JSL MEMCPY16
	BRA @UNKNOWN3
@UNKNOWN2:
	LOADPTR ITEM_CONFIGURATION_TABLE, $06
	LDY $16
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
@UNKNOWN3:
	SEP #PROC_FLAGS::ACCUM8
<<<<<<< HEAD
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
.ENDIF
	LDY @LOCAL02
	BEQ @UNKNOWN4
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
=======
	STZ UNKNOWN_7E9C9F+.SIZEOF(item::name)
	LDY $16
	BEQ @UNKNOWN4
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR UNKNOWN_7E9C9F, $06
>>>>>>> parent of e89e3811 (switch to new stack macro, delete old one and replace some magic numbers)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	MOVE_INT_CONSTANT NULL ,$12
	JSR UNKNOWN_C113D1
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	INC $02
@UNKNOWN5:
	LDA #.SIZEOF(char_struct::items)
	CLC
	SBC $02
	JUMPGTS @UNKNOWN1
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDY #$0000
	TYX
	LDA #$0002
	JSR UNKNOWN_C1180D
	PLD
	RTS
